# Generated by Django 6.0.6 on 2026-07-27 06:42

import apps.core.models.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'allergen',
                    models.CharField(
                        db_index=True, help_text='Allergen name.', max_length=255
                    ),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('medication', 'Medication'),
                            ('food', 'Food'),
                            ('environmental', 'Environmental'),
                            ('latex', 'Latex'),
                            ('insect', 'Insect'),
                            ('other', 'Other'),
                        ],
                        db_index=True,
                        default='medication',
                        help_text='Allergy category.',
                        max_length=20,
                    ),
                ),
                (
                    'severity',
                    models.CharField(
                        choices=[
                            ('mild', 'Mild'),
                            ('moderate', 'Moderate'),
                            ('severe', 'Severe'),
                            ('life_threatening', 'Life Threatening'),
                        ],
                        db_index=True,
                        default='moderate',
                        help_text='Allergy severity.',
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('resolved', 'Resolved'),
                            ('entered_in_error', 'Entered In Error'),
                        ],
                        db_index=True,
                        default='active',
                        help_text='Current allergy status.',
                        max_length=20,
                    ),
                ),
                (
                    'reaction',
                    models.TextField(
                        blank=True, help_text='Observed allergic reaction.'
                    ),
                ),
                (
                    'onset_date',
                    models.DateField(
                        blank=True,
                        help_text='Date when the allergy was first identified.',
                        null=True,
                    ),
                ),
                (
                    'resolved_date',
                    models.DateField(
                        blank=True,
                        help_text='Date when the allergy resolved.',
                        null=True,
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True, help_text='Additional clinical notes.'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Allergy',
                'verbose_name_plural': 'Allergies',
                'db_table': 'allergies',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
    ]
