# Generated by Django 6.0.6 on 2026-07-28 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allergies', '0001_initial'),
        ('encounters', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='encounter',
            field=models.ForeignKey(
                help_text='Encounter associated with this allergy.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='allergies',
                to='encounters.encounter',
            ),
        ),
        migrations.AddField(
            model_name='allergy',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization that owns this allergy.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='allergies',
                to='organizations.organization',
            ),
        ),
    ]
