# Generated by Django 6.0.6 on 2026-07-28 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allergies', '0003_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='provider',
            field=models.ForeignKey(
                help_text='Provider who recorded this allergy.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='allergies',
                to='providers.provider',
            ),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(
                fields=['organization'], name='allergies_organiz_89abff_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(fields=['patient'], name='allergies_patient_3fdc80_idx'),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(
                fields=['provider'], name='allergies_provide_ae567e_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(
                fields=['encounter'], name='allergies_encount_29fe7e_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(
                fields=['allergen'], name='allergies_allerge_880e69_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(
                fields=['category'], name='allergies_categor_12cd45_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(
                fields=['severity'], name='allergies_severit_e6c788_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(fields=['status'], name='allergies_status_52a549_idx'),
        ),
        migrations.AddConstraint(
            model_name='allergy',
            constraint=models.UniqueConstraint(
                fields=('organization', 'patient', 'allergen'),
                name='unique_patient_allergy_per_organization',
            ),
        ),
    ]
