# Generated by Django 6.0.6 on 2026-07-14 09:07

import apps.platform.accounts.models.managers.user
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("GOOGLE", "Google"), ("MICROSOFT", "Microsoft")],
                        db_index=True,
                        help_text="OAuth provider.",
                        max_length=20,
                    ),
                ),
                (
                    "provider_user_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique user identifier provided by the OAuth provider.",
                        max_length=255,
                    ),
                ),
                (
                    "provider_username",
                    models.CharField(
                        blank=True,
                        help_text="Display name returned by the OAuth provider.",
                        max_length=255,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address received from the OAuth provider.",
                        max_length=254,
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True, help_text="Provider profile image URL."
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional provider-specific profile information.",
                    ),
                ),
                (
                    "token_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Non-sensitive OAuth token information such as scopes and expiration metadata.",
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, help_text="Last successful OAuth login.", null=True
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last profile synchronization with the provider.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this OAuth account is currently active.",
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth Account",
                "verbose_name_plural": "OAuth Accounts",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrganizationRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this organization role.",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates whether this is a platform-provided role that cannot be deleted.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this role is currently active.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Role",
                "verbose_name_plural": "Organization Roles",
                "ordering": ("organization", "group"),
            },
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="Destination where the OTP was delivered.",
                        max_length=255,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("AUTHENTICATOR", "Authenticator App"),
                        ],
                        db_index=True,
                        default="EMAIL",
                        help_text="Delivery channel.",
                        max_length=20,
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("EMAIL_VERIFICATION", "Email Verification"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("LOGIN", "Login"),
                            ("MFA", "Multi-Factor Authentication"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("is_used", models.BooleanField(db_index=True, default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("failure_reason", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="profiles/avatars/"
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=100)),
                ("language", models.CharField(default="en", max_length=20)),
                ("theme", models.CharField(default="system", max_length=20)),
                ("locale", models.CharField(default="en", max_length=20)),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Primary email used for authentication.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number in E.164 format.",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid international phone number. Example: +919876543210.",
                                regex="^\\+?[1-9]\\d{9,14}$",
                            )
                        ],
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True, unique=True
                    ),
                ),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                (
                    "is_internal_user",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the user belongs to the internal workforce.",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ("email",),
            },
            managers=[
                ("objects", apps.platform.accounts.models.managers.user.UserManager()),
            ],
        ),
    ]
