# Generated by Django 6.0.6 on 2026-07-28 06:19

import apps.common.validators.fields.phone
import apps.platform.accounts.models.managers.user
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        db_index=True,
                        help_text='Email used during login attempt.',
                        max_length=254,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('SUCCESS', 'Success'),
                            ('FAILED', 'Failed'),
                            ('BLOCKED', 'Blocked'),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    'failure_reason',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('INVALID_PASSWORD', 'Invalid Password'),
                            ('USER_NOT_FOUND', 'User Not Found'),
                            ('USER_INACTIVE', 'User Inactive'),
                            ('EMAIL_NOT_VERIFIED', 'Email Not Verified'),
                            ('ACCOUNT_LOCKED', 'Account Locked'),
                        ],
                        max_length=50,
                    ),
                ),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OAuthAccount',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'provider',
                    models.CharField(
                        choices=[('GOOGLE', 'Google'), ('MICROSOFT', 'Microsoft')],
                        db_index=True,
                        help_text='OAuth provider.',
                        max_length=20,
                    ),
                ),
                (
                    'provider_user_id',
                    models.CharField(
                        db_index=True,
                        help_text='Unique user identifier provided by the OAuth provider.',
                        max_length=255,
                    ),
                ),
                (
                    'provider_username',
                    models.CharField(
                        blank=True,
                        help_text='Display name returned by the OAuth provider.',
                        max_length=255,
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        db_index=True,
                        help_text='Email address received from the OAuth provider.',
                        max_length=254,
                    ),
                ),
                (
                    'avatar_url',
                    models.URLField(
                        blank=True, help_text='Provider profile image URL.'
                    ),
                ),
                (
                    'metadata',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Additional provider-specific profile information.',
                    ),
                ),
                (
                    'token_metadata',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Non-sensitive OAuth token information such as scopes and expiration metadata.',
                    ),
                ),
                (
                    'last_login_at',
                    models.DateTimeField(
                        blank=True, help_text='Last successful OAuth login.', null=True
                    ),
                ),
                (
                    'last_synced_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Last profile synchronization with the provider.',
                        null=True,
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Whether this OAuth account is currently active.',
                    ),
                ),
            ],
            options={
                'verbose_name': 'OAuth Account',
                'verbose_name_plural': 'OAuth Accounts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('recipient', models.CharField(max_length=255)),
                (
                    'channel',
                    models.CharField(
                        choices=[
                            ('EMAIL', 'Email'),
                            ('SMS', 'SMS'),
                            ('WHATSAPP', 'WhatsApp'),
                            ('AUTHENTICATOR', 'Authenticator App'),
                        ],
                        db_index=True,
                        default='EMAIL',
                        max_length=20,
                    ),
                ),
                ('code_hash', models.CharField(max_length=255)),
                (
                    'purpose',
                    models.CharField(
                        choices=[
                            ('EMAIL_VERIFICATION', 'Email Verification'),
                            ('PASSWORD_RESET', 'Password Reset'),
                            ('LOGIN', 'Login'),
                            ('MFA', 'Multi-Factor Authentication'),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    'delivery_status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('sent', 'Sent'),
                            ('failed', 'Failed'),
                            ('delivered', 'Delivered'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('resend_count', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'avatar',
                    models.ImageField(
                        blank=True,
                        help_text='Profile avatar image.',
                        null=True,
                        upload_to='profiles/avatars/',
                    ),
                ),
                (
                    'timezone',
                    models.CharField(
                        default='Asia/Kolkata',
                        help_text='Preferred user timezone.',
                        max_length=100,
                    ),
                ),
                (
                    'language',
                    models.CharField(
                        default='en',
                        help_text='Preferred application language.',
                        max_length=20,
                    ),
                ),
                (
                    'theme',
                    models.CharField(
                        default='system', help_text='Preferred UI theme.', max_length=20
                    ),
                ),
                (
                    'locale',
                    models.CharField(
                        default='en', help_text='Preferred locale.', max_length=20
                    ),
                ),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'refresh_token_id',
                    models.CharField(
                        db_index=True,
                        help_text='JWT refresh token identifier (jti).',
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('ACTIVE', 'Active'),
                            ('REVOKED', 'Revoked'),
                            ('EXPIRED', 'Expired'),
                        ],
                        db_index=True,
                        default='ACTIVE',
                        max_length=20,
                    ),
                ),
                (
                    'device',
                    models.CharField(
                        blank=True,
                        help_text='Client device information.',
                        max_length=255,
                    ),
                ),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'username',
                    models.CharField(
                        error_messages={
                            'unique': 'A user with that username already exists.'
                        },
                        help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name='username',
                    ),
                ),
                (
                    'first_name',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='first name'
                    ),
                ),
                (
                    'last_name',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='last name'
                    ),
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False,
                        help_text='Designates whether the user can log into this admin site.',
                        verbose_name='staff status',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                        verbose_name='active',
                    ),
                ),
                (
                    'date_joined',
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name='date joined'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        db_index=True,
                        help_text='Primary email used for authentication.',
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    'phone',
                    models.CharField(
                        blank=True,
                        help_text='Phone number in E.164 format.',
                        max_length=20,
                        validators=[
                            apps.common.validators.fields.phone.validate_phone_number
                        ],
                    ),
                ),
                (
                    'employee_id',
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True, unique=True
                    ),
                ),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                (
                    'is_internal_user',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Whether the user belongs to the internal workforce.',
                    ),
                ),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups',
                    ),
                ),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('email',),
            },
            managers=[
                ('objects', apps.platform.accounts.models.managers.user.UserManager()),
            ],
        ),
    ]
