# Generated by Django 6.0.6 on 2026-07-31 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                help_text='Temporary default organization. Will be replaced by OrganizationMembership.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='users',
                to='organizations.organization',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(
                blank=True,
                help_text='Specific permissions for this user.',
                related_name='user_set',
                related_query_name='user',
                to='auth.permission',
                verbose_name='user permissions',
            ),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='login_attempts',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='oauthaccount',
            name='user',
            field=models.ForeignKey(
                help_text='User associated with this OAuth account.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='oauth_accounts',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='otps',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(
                help_text='User associated with this profile.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sessions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['organization'], name='accounts_us_organiz_7a60e0_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['is_verified'], name='accounts_us_is_veri_fa45d6_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['is_internal_user'], name='accounts_us_is_inte_91b8db_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(
                fields=['email', 'status'], name='accounts_lo_email_5d3fbb_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(
                fields=['user', 'created_at'], name='accounts_lo_user_id_b2e94d_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(
                fields=['ip_address', 'created_at'],
                name='accounts_lo_ip_addr_71e387_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='oauthaccount',
            index=models.Index(
                fields=['provider'], name='accounts_oa_provide_4609ae_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='oauthaccount',
            index=models.Index(
                fields=['provider_user_id'], name='accounts_oa_provide_14a567_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='oauthaccount',
            index=models.Index(fields=['email'], name='accounts_oa_email_d95399_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthaccount',
            index=models.Index(fields=['user'], name='accounts_oa_user_id_18cba3_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthaccount',
            index=models.Index(
                fields=['is_active'], name='accounts_oa_is_acti_5bfc0f_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='oauthaccount',
            constraint=models.UniqueConstraint(
                fields=('provider', 'provider_user_id'),
                name='unique_oauth_provider_user',
            ),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(
                fields=['user', 'purpose', 'is_used'],
                name='accounts_ot_user_id_2dc7bd_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(
                fields=['expires_at'], name='accounts_ot_expires_57ad4f_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(
                fields=['user', 'status'], name='accounts_us_user_id_37ae0c_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(
                fields=['refresh_token_id'], name='accounts_us_refresh_ae3f4b_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(
                fields=['ip_address', 'created_at'],
                name='accounts_us_ip_addr_a924f0_idx',
            ),
        ),
    ]
