# Generated by Django 6.0.6 on 2026-09-16 02:16

import apps.core.models.managers
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0002_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='address',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
    ]
