# Generated by Django 6.0.6 on 2026-09-21 04:59

import apps.core.models.managers
import apps.patient_management.communication.managers
import apps.patient_management.consents.managers
import apps.patient_management.medical_history.validators
import apps.patient_management.mpi.managers
import apps.patient_management.patient_documents.managers
import apps.patient_management.referrals.managers
import apps.patient_management.timeline.managers
import apps.patient_management.timeline.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('patient_core', '0001_initial'),
        (
            'patient_management',
            '0005_patientpreference_patientcommunicationpreference_and_more',
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MPIRecord',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'enterprise_identifier',
                    models.CharField(db_index=True, max_length=100),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('ACTIVE', 'Active'),
                            ('MERGED', 'Merged'),
                            ('RETIRED', 'Retired'),
                        ],
                        db_index=True,
                        default='ACTIVE',
                        max_length=20,
                    ),
                ),
                ('source_system', models.CharField(blank=True, max_length=100)),
                (
                    'source_patient_identifier',
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    'match_score',
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    'confidence',
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ('demographics_snapshot', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by_id', models.UUIDField(blank=True, null=True)),
                (
                    'merged_into',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='merged_records',
                        to='patient_management.mpirecord',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='mpi_records',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='mpi_record',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'db_table': 'patient_mpi_records',
                'ordering': ('enterprise_identifier',),
            },
            managers=[
                ('objects', apps.patient_management.mpi.managers.MPIRecordManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='MPIMatchCandidate',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('score', models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('CONFIRMED', 'Confirmed'),
                            ('REJECTED', 'Rejected'),
                            ('EXPIRED', 'Expired'),
                        ],
                        db_index=True,
                        default='PENDING',
                        max_length=20,
                    ),
                ),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by_id', models.UUIDField(blank=True, null=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='mpi_match_candidates',
                        to='organizations.organization',
                    ),
                ),
                (
                    'left_record',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='left_match_candidates',
                        to='patient_management.mpirecord',
                    ),
                ),
                (
                    'right_record',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='right_match_candidates',
                        to='patient_management.mpirecord',
                    ),
                ),
            ],
            options={
                'db_table': 'patient_mpi_match_candidates',
                'ordering': ('-score', '-created_at'),
            },
            managers=[
                ('objects', apps.patient_management.mpi.managers.MPIMatchManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientCommunication',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'channel',
                    models.CharField(
                        choices=[
                            ('sms', 'SMS'),
                            ('email', 'Email'),
                            ('phone', 'Phone'),
                            ('portal', 'Patient Portal'),
                            ('letter', 'Letter'),
                            ('in_person', 'In Person'),
                            ('other', 'Other'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'direction',
                    models.CharField(
                        choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')],
                        max_length=20,
                    ),
                ),
                (
                    'communication_type',
                    models.CharField(
                        choices=[
                            ('general', 'General'),
                            ('appointment', 'Appointment'),
                            ('clinical', 'Clinical'),
                            ('billing', 'Billing'),
                            ('follow_up', 'Follow Up'),
                            ('reminder', 'Reminder'),
                            ('administrative', 'Administrative'),
                        ],
                        default='general',
                        max_length=30,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('queued', 'Queued'),
                            ('sent', 'Sent'),
                            ('delivered', 'Delivered'),
                            ('read', 'Read'),
                            ('failed', 'Failed'),
                            ('cancelled', 'Cancelled'),
                            ('archived', 'Archived'),
                        ],
                        db_index=True,
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                (
                    'occurred_at',
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_patient_communications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='patient_communications',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='communications',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'db_table': 'patient_communications',
                'ordering': ('-occurred_at', '-created_at'),
            },
            managers=[
                (
                    'objects',
                    apps.patient_management.communication.managers.CommunicationManager(),
                ),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'purpose',
                    models.CharField(
                        choices=[
                            ('treatment', 'Treatment'),
                            ('payment', 'Payment'),
                            ('operations', 'Operations'),
                            ('research', 'Research'),
                        ],
                        help_text='Purpose covered by the consent.',
                        max_length=30,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('granted', 'Granted'),
                            ('revoked', 'Revoked'),
                            ('expired', 'Expired'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, default='1', max_length=50)),
                (
                    'evidence_reference',
                    models.CharField(
                        blank=True,
                        help_text='Reference to the consent evidence or source record.',
                        max_length=255,
                    ),
                ),
                (
                    'granted_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='granted_patient_consents',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns the consent.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='patient_consents',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        help_text='Patient to whom the consent applies.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='patient_consents',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Patient Consent',
                'verbose_name_plural': 'Patient Consents',
                'db_table': 'patient_management_consents',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.patient_management.consents.managers.ConsentManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('medical_record', 'Medical Record'),
                            ('lab_result', 'Laboratory Result'),
                            ('imaging', 'Imaging'),
                            ('prescription', 'Prescription'),
                            ('insurance', 'Insurance'),
                            ('consent', 'Consent'),
                            ('referral', 'Referral'),
                            ('identification', 'Identification'),
                            ('administrative', 'Administrative'),
                            ('other', 'Other'),
                        ],
                        db_index=True,
                        default='other',
                        max_length=40,
                        verbose_name='Category',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('active', 'Active'),
                            ('archived', 'Archived'),
                        ],
                        db_index=True,
                        default='draft',
                        max_length=20,
                        verbose_name='Status',
                    ),
                ),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Description'),
                ),
                (
                    'original_filename',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Original Filename'
                    ),
                ),
                (
                    'storage_key',
                    models.CharField(max_length=500, verbose_name='Storage Key'),
                ),
                (
                    'mime_type',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='MIME Type'
                    ),
                ),
                (
                    'file_size',
                    models.PositiveBigIntegerField(default=0, verbose_name='File Size'),
                ),
                (
                    'checksum',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Checksum'
                    ),
                ),
                (
                    'is_confidential',
                    models.BooleanField(
                        db_index=True, default=False, verbose_name='Confidential'
                    ),
                ),
                (
                    'metadata',
                    models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
                ),
                (
                    'uploaded_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Uploaded At'
                    ),
                ),
                (
                    'archived_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Archived At'
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_patient_documents',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization owning the patient document.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='patient_documents',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        help_text='Canonical patient owning the document.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='patient_documents',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'db_table': 'patient_documents',
                'ordering': ('-created_at',),
            },
            managers=[
                (
                    'objects',
                    apps.patient_management.patient_documents.managers.PatientDocumentManager(),
                ),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientDocumentAccessLog',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('view', 'View'),
                            ('download', 'Download'),
                            ('preview', 'Preview'),
                            ('share', 'Share'),
                        ],
                        max_length=20,
                    ),
                ),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'patient_document',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='access_logs',
                        to='patient_management.patientdocument',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='patient_document_access_logs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'patient_document_access_logs',
                'ordering': ('-accessed_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientDocumentVersion',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('version_number', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=150)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=255)),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('superseded', 'Superseded')],
                        default='active',
                        max_length=20,
                    ),
                ),
                ('notes', models.TextField(blank=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_patient_document_versions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'patient_document',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='versions',
                        to='patient_management.patientdocument',
                    ),
                ),
            ],
            options={
                'db_table': 'patient_document_versions',
                'ordering': ('-version_number',),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'history_type',
                    models.CharField(
                        choices=[
                            ('condition', 'Condition'),
                            ('surgery', 'Surgery'),
                            ('hospitalization', 'Hospitalization'),
                            ('allergy', 'Allergy'),
                            ('family_history', 'Family History'),
                            ('social_history', 'Social History'),
                            ('immunization', 'Immunization'),
                            ('other', 'Other'),
                        ],
                        db_index=True,
                        default='condition',
                        max_length=30,
                        validators=[
                            apps.patient_management.medical_history.validators.validate_history_type
                        ],
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=255,
                        validators=[
                            apps.patient_management.medical_history.validators.validate_title
                        ],
                    ),
                ),
                ('description', models.TextField(blank=True)),
                (
                    'clinical_status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('resolved', 'Resolved'),
                            ('inactive', 'Inactive'),
                            ('history', 'History'),
                        ],
                        db_index=True,
                        default='active',
                        max_length=20,
                        validators=[
                            apps.patient_management.medical_history.validators.validate_clinical_status
                        ],
                    ),
                ),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                (
                    'relationship',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('spouse', 'Spouse'),
                            ('parent', 'Parent'),
                            ('child', 'Child'),
                            ('sibling', 'Sibling'),
                            ('guardian', 'Guardian'),
                            ('grandparent', 'Grandparent'),
                            ('other', 'Other'),
                        ],
                        max_length=30,
                    ),
                ),
                ('is_smoker', models.BooleanField(blank=True, null=True)),
                (
                    'alcohol_use',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('none', 'None'),
                            ('occasional', 'Occasional'),
                            ('moderate', 'Moderate'),
                            ('heavy', 'Heavy'),
                            ('unknown', 'Unknown'),
                        ],
                        max_length=20,
                        validators=[
                            apps.patient_management.medical_history.validators.validate_alcohol_use
                        ],
                    ),
                ),
                ('recorded_by', models.CharField(blank=True, max_length=150)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='patient_medical_histories',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='medical_history_entries',
                        to='patient_core.patient',
                    ),
                ),
                (
                    'verified_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='verified_medical_history_entries',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Patient Medical History',
                'verbose_name_plural': 'Patient Medical Histories',
                'db_table': 'patient_medical_histories',
                'ordering': ('-onset_date', '-created_at'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientPortalAccount',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('INVITED', 'Invited'),
                            ('ACTIVE', 'Active'),
                            ('SUSPENDED', 'Suspended'),
                            ('LOCKED', 'Locked'),
                            ('DEACTIVATED', 'Deactivated'),
                        ],
                        db_index=True,
                        default='INVITED',
                        max_length=20,
                    ),
                ),
                (
                    'auth_provider',
                    models.CharField(
                        choices=[
                            ('LOCAL', 'Local'),
                            ('GOOGLE', 'Google'),
                            ('MICROSOFT', 'Microsoft'),
                            ('SSO', 'Single Sign-On'),
                        ],
                        default='LOCAL',
                        max_length=20,
                    ),
                ),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                (
                    'preferred_language',
                    models.CharField(default='English', max_length=50),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='patient_portal_accounts',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='portal_account',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'db_table': 'patient_portal_accounts',
                'ordering': ('username',),
            },
            managers=[
                (
                    'objects',
                    django.db.models.manager.Manager(),
                ),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientReferral',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'referral_number',
                    models.CharField(
                        help_text='Unique referral reference number within the organization.',
                        max_length=40,
                    ),
                ),
                ('referring_provider', models.CharField(blank=True, max_length=150)),
                ('referred_to', models.CharField(max_length=150)),
                (
                    'referred_to_organization',
                    models.CharField(blank=True, max_length=255),
                ),
                ('reason', models.TextField()),
                (
                    'priority',
                    models.CharField(
                        choices=[
                            ('ROUTINE', 'Routine'),
                            ('URGENT', 'Urgent'),
                            ('STAT', 'Stat'),
                        ],
                        default='ROUTINE',
                        max_length=20,
                    ),
                ),
                (
                    'urgency',
                    models.CharField(
                        choices=[
                            ('ROUTINE', 'Routine'),
                            ('URGENT', 'Urgent'),
                            ('EMERGENT', 'Emergent'),
                        ],
                        default='ROUTINE',
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('DRAFT', 'Draft'),
                            ('PENDING', 'Pending'),
                            ('ACCEPTED', 'Accepted'),
                            ('SCHEDULED', 'Scheduled'),
                            ('IN_PROGRESS', 'In Progress'),
                            ('COMPLETED', 'Completed'),
                            ('DECLINED', 'Declined'),
                            ('CANCELLED', 'Cancelled'),
                        ],
                        db_index=True,
                        default='DRAFT',
                        max_length=20,
                    ),
                ),
                ('clinical_notes', models.TextField(blank=True)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'created_by_id',
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    'updated_by_id',
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='patient_referrals',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='referrals',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Patient Referral',
                'verbose_name_plural': 'Patient Referrals',
                'db_table': 'patient_referrals',
                'ordering': ('-created_at',),
            },
            managers=[
                (
                    'objects',
                    apps.patient_management.referrals.managers.PatientReferralManager(),
                ),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientRelationship',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'relationship_type',
                    models.CharField(
                        choices=[
                            ('spouse', 'Spouse'),
                            ('partner', 'Partner'),
                            ('parent', 'Parent'),
                            ('child', 'Child'),
                            ('sibling', 'Sibling'),
                            ('grandparent', 'Grandparent'),
                            ('grandchild', 'Grandchild'),
                            ('guardian', 'Guardian'),
                            ('dependent', 'Dependent'),
                            ('caregiver', 'Caregiver'),
                            ('emergency_contact', 'Emergency Contact'),
                            ('other', 'Other'),
                        ],
                        help_text='Type of relationship.',
                        max_length=30,
                    ),
                ),
                (
                    'relationship_name',
                    models.CharField(
                        blank=True,
                        help_text="External person's or entity's relationship name when related_patient is not supplied.",
                        max_length=150,
                    ),
                ),
                (
                    'is_primary',
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the patient's primary relationship.",
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('inactive', 'Inactive'),
                            ('terminated', 'Terminated'),
                        ],
                        db_index=True,
                        default='active',
                        max_length=20,
                    ),
                ),
                (
                    'verification_status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('verified', 'Verified'),
                            ('rejected', 'Rejected'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns the relationship.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='patient_relationships',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        help_text='Primary patient.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='patient_relationships',
                        to='patient_core.patient',
                    ),
                ),
                (
                    'related_patient',
                    models.ForeignKey(
                        blank=True,
                        help_text='Related patient, when the relationship is internal.',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='related_patient_relationships',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Patient Relationship',
                'verbose_name_plural': 'Patient Relationships',
                'db_table': 'patient_relationships',
                'ordering': ('-is_primary', 'relationship_type', 'created_at'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('clinical', 'Clinical'),
                            ('appointment', 'Appointment'),
                            ('medication', 'Medication'),
                            ('document', 'Document'),
                            ('communication', 'Communication'),
                            ('system', 'System'),
                        ],
                        default='system',
                        max_length=32,
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=255,
                        validators=[
                            apps.patient_management.timeline.validators.validate_timeline_title
                        ],
                    ),
                ),
                ('description', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('active', 'Active'),
                            ('archived', 'Archived'),
                        ],
                        default='active',
                        max_length=32,
                    ),
                ),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_timeline_entries',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='timeline_entries',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='timeline_entries',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
            },
            managers=[
                (
                    'objects',
                    apps.patient_management.timeline.managers.TimelineEntryManager(),
                ),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='mpirecord',
            index=models.Index(
                fields=['organization', 'status'], name='mpi_record_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='mpirecord',
            index=models.Index(
                fields=['organization', 'source_system', 'source_patient_identifier'],
                name='mpi_record_source_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='mpirecord',
            constraint=models.UniqueConstraint(
                fields=('organization', 'enterprise_identifier'),
                name='unique_mpi_enterprise_id_per_org',
            ),
        ),
        migrations.AddIndex(
            model_name='mpimatchcandidate',
            index=models.Index(
                fields=['organization', 'status', '-score'],
                name='mpi_match_status_score_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='mpimatchcandidate',
            constraint=models.UniqueConstraint(
                fields=('organization', 'left_record', 'right_record'),
                name='unique_mpi_candidate_pair',
            ),
        ),
        migrations.AddConstraint(
            model_name='mpimatchcandidate',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('left_record', models.F('right_record')), _negated=True
                ),
                name='mpi_candidate_records_distinct',
            ),
        ),
        migrations.AddIndex(
            model_name='patientcommunication',
            index=models.Index(
                fields=['organization', 'patient', 'occurred_at'],
                name='patient_com_organiz_370bf1_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='patientcommunication',
            index=models.Index(
                fields=['organization', 'status', 'is_deleted'],
                name='patient_com_organiz_99559f_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='patientcommunication',
            index=models.Index(
                fields=['organization', 'channel', 'occurred_at'],
                name='patient_com_organiz_f587dc_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='patientconsent',
            constraint=models.Index(
                fields=['organization', 'patient', 'status'],
                name='pm_consent_org_patient_status_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='patientdocument',
            index=models.Index(
                fields=['organization', 'patient', 'status'],
                name='pd_org_patient_status_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='patientdocument',
            index=models.Index(
                fields=['organization', 'category', 'created_at'],
                name='pd_org_category_created_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='patientdocument',
            index=models.Index(
                fields=['patient', 'created_at'], name='pd_patient_created_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='patientdocument',
            constraint=models.UniqueConstraint(
                fields=('organization', 'storage_key'),
                name='uq_patient_document_org_storage_key',
            ),
        ),
        migrations.AddIndex(
            model_name='patientdocumentaccesslog',
            index=models.Index(
                fields=['patient_document', 'accessed_at'],
                name='pdal_document_access_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='patientdocumentaccesslog',
            index=models.Index(
                fields=['user', 'accessed_at'], name='pdal_user_access_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='patientdocumentaccesslog',
            index=models.Index(
                fields=['action', 'accessed_at'], name='pdal_action_access_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='patientdocumentversion',
            index=models.Index(
                fields=['patient_document', 'version_number'],
                name='pdv_document_version_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='patientdocumentversion',
            index=models.Index(
                fields=['patient_document', 'status'], name='pdv_document_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='patientdocumentversion',
            index=models.Index(fields=['checksum'], name='pdv_checksum_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientdocumentversion',
            constraint=models.UniqueConstraint(
                fields=('patient_document', 'version_number'),
                name='uq_patient_document_version_number',
            ),
        ),
        migrations.AddConstraint(
            model_name='patientdocumentversion',
            constraint=models.CheckConstraint(
                condition=models.Q(('version_number__gt', 0)),
                name='ck_patient_document_version_positive',
            ),
        ),
        migrations.AddIndex(
            model_name='patientmedicalhistory',
            index=models.Index(
                fields=['organization', 'patient', 'history_type'],
                name='medhist_org_pat_type_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='patientmedicalhistory',
            index=models.Index(
                fields=['organization', 'patient', 'clinical_status'],
                name='medhist_org_pat_status_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='patientmedicalhistory',
            index=models.Index(
                fields=['patient', 'onset_date'], name='medhist_patient_onset_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='patientportalaccount',
            index=models.Index(
                fields=['organization', 'patient', 'status'],
                name='portal_org_patient_status_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='patientportalaccount',
            constraint=models.UniqueConstraint(
                fields=('organization', 'username'),
                name='unique_portal_username_per_org',
            ),
        ),
        migrations.AddIndex(
            model_name='patientreferral',
            index=models.Index(
                fields=['organization', 'patient', 'status'],
                name='referral_org_pat_status_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='patientreferral',
            index=models.Index(
                fields=['organization', 'referral_number'],
                name='referral_org_number_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='patientreferral',
            constraint=models.UniqueConstraint(
                fields=('organization', 'referral_number'),
                name='unique_referral_number_per_organization',
            ),
        ),
        migrations.AddIndex(
            model_name='patientrelationship',
            index=models.Index(
                fields=['organization', 'patient', 'status'],
                name='rel_org_pat_status_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='patientrelationship',
            index=models.Index(
                fields=['organization', 'related_patient'], name='rel_org_related_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='patientrelationship',
            index=models.Index(
                fields=['patient', 'relationship_type'], name='rel_patient_type_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='patientrelationship',
            index=models.Index(
                fields=['verification_status'], name='rel_verification_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='patientrelationship',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('is_active', True), ('related_patient__isnull', False)
                ),
                fields=(
                    'organization',
                    'patient',
                    'related_patient',
                    'relationship_type',
                ),
                name='uq_patient_relationship_internal',
            ),
        ),
        migrations.AddConstraint(
            model_name='patientrelationship',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('is_active', True), ('related_patient__isnull', True)
                ),
                fields=(
                    'organization',
                    'patient',
                    'relationship_name',
                    'relationship_type',
                ),
                name='uq_patient_relationship_external',
            ),
        ),
        migrations.AddConstraint(
            model_name='patientrelationship',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_active', True), ('is_primary', True)),
                fields=('organization', 'patient'),
                name='uq_patient_primary_relationship',
            ),
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(
                fields=['organization', 'patient', 'occurred_at'],
                name='patient_man_organiz_4981fc_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(
                fields=['organization', 'status', 'is_deleted'],
                name='patient_man_organiz_28d878_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(
                fields=['organization', 'is_active', 'occurred_at'],
                name='patient_man_organiz_c4e07b_idx',
            ),
        ),
    ]
