# Generated by Django 6.0.6 on 2026-09-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'patient_management',
            '0006_mpirecord_mpimatchcandidate_patientcommunication_and_more',
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='timelineentry',
            name='patient_man_organiz_4981fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='timelineentry',
            name='patient_man_organiz_28d878_idx',
        ),
        migrations.RemoveIndex(
            model_name='timelineentry',
            name='patient_man_organiz_c4e07b_idx',
        ),
        migrations.DeleteModel(
            name='TimelineEntry',
        ),
    ]
