# Generated by Django 6.0.6 on 2026-09-23 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('patient_core', '0001_initial'),
        ('patient_management', '0007_remove_timelineentry_patient_man_organiz_4981fc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patientconsent',
            name='pm_consent_org_patient_status_idx',
        ),
        migrations.AddConstraint(
            model_name='patientconsent',
            constraint=models.Index(fields=['organization', 'patient', 'status'], name='pm_consent_org_pat_status_idx'),
        ),
    ]
