# Generated by Django 6.0.6 on 2026-07-04 02:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'provider_number',
                    models.CharField(
                        help_text='Unique provider identifier.', max_length=30
                    ),
                ),
                (
                    'license_number',
                    models.CharField(
                        help_text='Professional license number.', max_length=100
                    ),
                ),
                (
                    'provider_type',
                    models.CharField(
                        choices=[
                            ('physician', 'Physician'),
                            ('surgeon', 'Surgeon'),
                            ('nurse', 'Nurse'),
                            ('dentist', 'Dentist'),
                            ('therapist', 'Therapist'),
                            ('pharmacist', 'Pharmacist'),
                            ('radiologist', 'Radiologist'),
                            ('pathologist', 'Pathologist'),
                            ('lab_technician', 'Lab Technician'),
                            ('other', 'Other'),
                        ],
                        help_text='Healthcare provider type.',
                        max_length=30,
                    ),
                ),
                (
                    'years_of_experience',
                    models.PositiveSmallIntegerField(
                        default=0, help_text='Years of professional experience.'
                    ),
                ),
                (
                    'is_accepting_patients',
                    models.BooleanField(
                        default=True,
                        help_text='Whether the provider is accepting new patients.',
                    ),
                ),
                (
                    'bio',
                    models.TextField(blank=True, help_text='Professional biography.'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('inactive', 'Inactive'),
                            ('on_leave', 'On Leave'),
                            ('suspended', 'Suspended'),
                            ('retired', 'Retired'),
                        ],
                        db_index=True,
                        default='active',
                        help_text='Provider lifecycle status.',
                        max_length=20,
                    ),
                ),
                (
                    'employee',
                    models.OneToOneField(
                        help_text='Employee profile associated with this provider.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='provider',
                        to='employees.employee',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns the provider.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='providers',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'providers',
                'ordering': ('provider_number',),
                'indexes': [
                    models.Index(
                        fields=['provider_number'], name='providers_provide_cf91af_idx'
                    ),
                    models.Index(
                        fields=['provider_type'], name='providers_provide_2b0409_idx'
                    ),
                    models.Index(fields=['status'], name='providers_status_d8f0d1_idx'),
                    models.Index(
                        fields=['is_accepting_patients'],
                        name='providers_is_acce_f4c21e_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('organization', 'provider_number'),
                        name='unique_provider_number_per_organization',
                    ),
                    models.UniqueConstraint(
                        fields=('organization', 'license_number'),
                        name='unique_provider_license_per_organization',
                    ),
                ],
            },
        ),
    ]
