# Generated by Django 6.0.6 on 2026-07-07 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'order_number',
                    models.CharField(
                        db_index=True,
                        help_text='Unique laboratory order number.',
                        max_length=30,
                    ),
                ),
                (
                    'priority',
                    models.CharField(
                        choices=[
                            ('routine', 'Routine'),
                            ('urgent', 'Urgent'),
                            ('stat', 'STAT'),
                        ],
                        db_index=True,
                        default='routine',
                        help_text='Priority assigned to the laboratory order.',
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('ordered', 'Ordered'),
                            ('specimen_collected', 'Specimen Collected'),
                            ('in_progress', 'In Progress'),
                            ('completed', 'Completed'),
                            ('cancelled', 'Cancelled'),
                        ],
                        db_index=True,
                        default='ordered',
                        help_text='Current status of the laboratory order.',
                        max_length=30,
                    ),
                ),
                (
                    'ordered_at',
                    models.DateTimeField(
                        db_index=True,
                        help_text='Date and time when the laboratory order was placed.',
                    ),
                ),
                (
                    'clinical_notes',
                    models.TextField(
                        blank=True,
                        help_text='Clinical information supporting the laboratory request.',
                    ),
                ),
                (
                    'instructions',
                    models.TextField(
                        blank=True,
                        help_text='Additional specimen collection or processing instructions.',
                    ),
                ),
                (
                    'encounter',
                    models.ForeignKey(
                        help_text='Encounter during which the laboratory order was placed.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='laboratory_orders',
                        to='encounters.encounter',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns this laboratory order.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='laboratory_orders',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        help_text='Patient associated with this laboratory order.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='laboratory_orders',
                        to='patients.patient',
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        help_text='Provider who ordered the laboratory investigation.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='laboratory_orders',
                        to='providers.provider',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Laboratory Order',
                'verbose_name_plural': 'Laboratory Orders',
                'db_table': 'laboratory_orders',
                'ordering': ('-ordered_at',),
            },
        ),
        migrations.CreateModel(
            name='LaboratoryTest',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        db_index=True,
                        help_text='Standard laboratory test code.',
                        max_length=30,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        db_index=True, help_text='Laboratory test name.', max_length=255
                    ),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('hematology', 'Hematology'),
                            ('chemistry', 'Chemistry'),
                            ('microbiology', 'Microbiology'),
                            ('serology', 'Serology'),
                            ('pathology', 'Pathology'),
                            ('immunology', 'Immunology'),
                            ('molecular', 'Molecular'),
                        ],
                        db_index=True,
                        help_text='Clinical category of the laboratory test.',
                        max_length=30,
                    ),
                ),
                (
                    'specimen_type',
                    models.CharField(
                        choices=[
                            ('blood', 'Blood'),
                            ('urine', 'Urine'),
                            ('stool', 'Stool'),
                            ('sputum', 'Sputum'),
                            ('saliva', 'Saliva'),
                            ('tissue', 'Tissue'),
                            ('swab', 'Swab'),
                            ('other', 'Other'),
                        ],
                        help_text='Required specimen type.',
                        max_length=30,
                    ),
                ),
                (
                    'priority',
                    models.CharField(
                        choices=[
                            ('routine', 'Routine'),
                            ('urgent', 'Urgent'),
                            ('stat', 'STAT'),
                        ],
                        db_index=True,
                        default='routine',
                        help_text='Execution priority of the laboratory test.',
                        max_length=20,
                    ),
                ),
                (
                    'display_order',
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=1,
                        help_text='Display order within the laboratory order.',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('in_progress', 'In Progress'),
                            ('completed', 'Completed'),
                            ('cancelled', 'Cancelled'),
                        ],
                        db_index=True,
                        default='pending',
                        help_text='Current status of the laboratory test.',
                        max_length=20,
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True,
                        help_text='Additional notes for the laboratory test.',
                    ),
                ),
                (
                    'laboratory_order',
                    models.ForeignKey(
                        help_text='Laboratory order containing this test.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tests',
                        to='laboratories.laboratoryorder',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Laboratory Test',
                'verbose_name_plural': 'Laboratory Tests',
                'db_table': 'laboratory_tests',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LaboratoryResult',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'result_value_numeric',
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text='Numeric laboratory result value.',
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    'result_value_text',
                    models.CharField(
                        blank=True,
                        help_text='Text laboratory result value.',
                        max_length=255,
                    ),
                ),
                (
                    'unit',
                    models.CharField(
                        blank=True, help_text='Measurement unit.', max_length=50
                    ),
                ),
                (
                    'reference_range',
                    models.CharField(
                        blank=True,
                        help_text='Reference range for the laboratory test.',
                        max_length=100,
                    ),
                ),
                (
                    'abnormal_flag',
                    models.CharField(
                        choices=[
                            ('normal', 'Normal'),
                            ('high', 'High'),
                            ('low', 'Low'),
                            ('critical', 'Critical'),
                            ('abnormal', 'Abnormal'),
                        ],
                        db_index=True,
                        default='normal',
                        help_text='Abnormality flag for the laboratory result.',
                        max_length=30,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('preliminary', 'Preliminary'),
                            ('final', 'Final'),
                            ('amended', 'Amended'),
                        ],
                        db_index=True,
                        default='pending',
                        help_text='Current status of the laboratory result.',
                        max_length=30,
                    ),
                ),
                (
                    'resulted_at',
                    models.DateTimeField(
                        db_index=True,
                        help_text='Date and time the laboratory result was generated.',
                    ),
                ),
                (
                    'verified_at',
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text='Date and time the laboratory result was verified.',
                        null=True,
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True, help_text='Additional laboratory notes.'
                    ),
                ),
                (
                    'verified_by',
                    models.ForeignKey(
                        blank=True,
                        help_text='Provider who verified the laboratory result.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='verified_laboratory_results',
                        to='providers.provider',
                    ),
                ),
                (
                    'laboratory_test',
                    models.OneToOneField(
                        help_text='Laboratory test associated with this result.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='result',
                        to='laboratories.laboratorytest',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Laboratory Result',
                'verbose_name_plural': 'Laboratory Results',
                'db_table': 'laboratory_results',
                'ordering': ('-resulted_at',),
            },
        ),
        migrations.AddIndex(
            model_name='laboratoryorder',
            index=models.Index(
                fields=['organization'], name='laboratory__organiz_d7437f_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratoryorder',
            index=models.Index(
                fields=['patient'], name='laboratory__patient_ffd897_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratoryorder',
            index=models.Index(
                fields=['provider'], name='laboratory__provide_2fe7b9_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratoryorder',
            index=models.Index(
                fields=['encounter'], name='laboratory__encount_14b55a_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratoryorder',
            index=models.Index(
                fields=['order_number'], name='laboratory__order_n_7ce1f8_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratoryorder',
            index=models.Index(fields=['status'], name='laboratory__status_d72124_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoryorder',
            index=models.Index(
                fields=['ordered_at'], name='laboratory__ordered_615ff2_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratoryorder',
            index=models.Index(
                fields=['organization', 'status'], name='laboratory__organiz_799250_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratoryorder',
            index=models.Index(
                fields=['patient', 'ordered_at'], name='laboratory__patient_224605_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratoryorder',
            index=models.Index(
                fields=['encounter', 'ordered_at'],
                name='laboratory__encount_d3ba70_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='laboratoryorder',
            constraint=models.UniqueConstraint(
                fields=('organization', 'order_number'),
                name='unique_laboratory_order_per_organization',
            ),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(
                fields=['laboratory_order'], name='laboratory__laborat_654c79_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(fields=['code'], name='laboratory__code_f629a0_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(fields=['name'], name='laboratory__name_2b2cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(
                fields=['category'], name='laboratory__categor_5d21f9_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(
                fields=['priority'], name='laboratory__priorit_2539e5_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(fields=['status'], name='laboratory__status_7cce8a_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(
                fields=['category', 'status'], name='laboratory__categor_02f010_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(
                fields=['laboratory_order', 'status'],
                name='laboratory__laborat_67a55e_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(
                fields=['laboratory_order', 'display_order'],
                name='laboratory__laborat_0b3cdf_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='laboratorytest',
            constraint=models.UniqueConstraint(
                fields=('laboratory_order', 'code'),
                name='unique_test_per_laboratory_order',
            ),
        ),
        migrations.AddIndex(
            model_name='laboratoryresult',
            index=models.Index(
                fields=['laboratory_test'], name='laboratory__laborat_25a740_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratoryresult',
            index=models.Index(fields=['status'], name='laboratory__status_ca3b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoryresult',
            index=models.Index(
                fields=['resulted_at'], name='laboratory__resulte_73c805_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratoryresult',
            index=models.Index(
                fields=['verified_by'], name='laboratory__verifie_77def0_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratoryresult',
            index=models.Index(
                fields=['verified_at'], name='laboratory__verifie_7c4f4b_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratoryresult',
            index=models.Index(
                fields=['status', 'resulted_at'], name='laboratory__status_b34547_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='laboratoryresult',
            index=models.Index(
                fields=['abnormal_flag', 'resulted_at'],
                name='laboratory__abnorma_a16d81_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='laboratoryresult',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('result_value_numeric__isnull', False),
                    models.Q(('result_value_text', ''), _negated=True),
                    _connector='OR',
                ),
                name='laboratory_result_has_value',
            ),
        ),
    ]
