# Generated by Django 6.0.6 on 2026-07-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoryresult',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='laboratoryresult',
            name='status',
            field=models.CharField(
                choices=[
                    ('recorded', 'Recorded'),
                    ('verified', 'Verified'),
                    ('final', 'Final'),
                    ('amended', 'Amended'),
                    ('invalidated', 'Invalidated'),
                ],
                db_index=True,
                default='recorded',
                help_text='Current status of the laboratory result.',
                max_length=30,
            ),
        ),
    ]
