# Generated by Django 6.0.6 on 2026-07-14 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("patients", "0001_initial"),
        ("providers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "appointment_number",
                    models.CharField(
                        help_text="Unique appointment number.", max_length=30
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation"),
                            ("follow_up", "Follow-up"),
                            ("emergency", "Emergency"),
                            ("surgery", "Surgery"),
                            ("procedure", "Procedure"),
                            ("teleconsultation", "Teleconsultation"),
                        ],
                        help_text="Appointment type.",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="scheduled",
                        help_text="Appointment status.",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        help_text="Appointment priority.",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_start",
                    models.DateTimeField(help_text="Scheduled appointment start."),
                ),
                (
                    "scheduled_end",
                    models.DateTimeField(help_text="Scheduled appointment end."),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30, help_text="Appointment duration in minutes."
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, help_text="Reason for appointment.", max_length=255
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional appointment notes."
                    ),
                ),
                (
                    "check_in_at",
                    models.DateTimeField(
                        blank=True, help_text="Patient check-in time.", null=True
                    ),
                ),
                (
                    "check_out_at",
                    models.DateTimeField(
                        blank=True, help_text="Patient check-out time.", null=True
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, help_text="Reason for cancellation."),
                ),
                (
                    "is_virtual",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a virtual appointment.",
                    ),
                ),
                (
                    "meeting_url",
                    models.URLField(blank=True, help_text="Virtual meeting URL."),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this appointment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient for the appointment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="Healthcare provider assigned to the appointment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "db_table": "appointments",
                "ordering": ("-scheduled_start",),
                "indexes": [
                    models.Index(
                        fields=["appointment_number"],
                        name="appointment_appoint_e7d91b_idx",
                    ),
                    models.Index(
                        fields=["organization"], name="appointment_organiz_a77c6b_idx"
                    ),
                    models.Index(
                        fields=["scheduled_start"],
                        name="appointment_schedul_eb43c5_idx",
                    ),
                    models.Index(
                        fields=["status"], name="appointment_status_9fecd6_idx"
                    ),
                    models.Index(
                        fields=["patient"], name="appointment_patient_75a4eb_idx"
                    ),
                    models.Index(
                        fields=["provider"], name="appointment_provide_7523ed_idx"
                    ),
                    models.Index(
                        fields=["provider", "scheduled_start"],
                        name="appointment_provide_7c92e2_idx",
                    ),
                    models.Index(
                        fields=["patient", "scheduled_start"],
                        name="appointment_patient_fdc364_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "appointment_number"),
                        name="unique_appointment_number_per_organization",
                    )
                ],
            },
        ),
    ]
