# Generated by Django 6.0.6 on 2026-07-31 11:49

import apps.core.models.managers
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'appointment_number',
                    models.CharField(
                        help_text='Unique appointment number.', max_length=30
                    ),
                ),
                (
                    'appointment_type',
                    models.CharField(
                        choices=[
                            ('consultation', 'Consultation'),
                            ('follow_up', 'Follow-up'),
                            ('emergency', 'Emergency'),
                            ('surgery', 'Surgery'),
                            ('procedure', 'Procedure'),
                            ('teleconsultation', 'Teleconsultation'),
                        ],
                        help_text='Appointment type.',
                        max_length=30,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('scheduled', 'Scheduled'),
                            ('confirmed', 'Confirmed'),
                            ('checked_in', 'Checked In'),
                            ('in_progress', 'In Progress'),
                            ('completed', 'Completed'),
                            ('cancelled', 'Cancelled'),
                            ('no_show', 'No Show'),
                        ],
                        db_index=True,
                        default='scheduled',
                        help_text='Appointment status.',
                        max_length=20,
                    ),
                ),
                (
                    'priority',
                    models.CharField(
                        choices=[
                            ('low', 'Low'),
                            ('normal', 'Normal'),
                            ('high', 'High'),
                            ('urgent', 'Urgent'),
                        ],
                        default='normal',
                        help_text='Appointment priority.',
                        max_length=20,
                    ),
                ),
                (
                    'scheduled_start',
                    models.DateTimeField(help_text='Scheduled appointment start.'),
                ),
                (
                    'scheduled_end',
                    models.DateTimeField(help_text='Scheduled appointment end.'),
                ),
                (
                    'duration_minutes',
                    models.PositiveIntegerField(
                        default=30, help_text='Appointment duration in minutes.'
                    ),
                ),
                (
                    'reason',
                    models.CharField(
                        blank=True, help_text='Reason for appointment.', max_length=255
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True, help_text='Additional appointment notes.'
                    ),
                ),
                (
                    'check_in_at',
                    models.DateTimeField(
                        blank=True, help_text='Patient check-in time.', null=True
                    ),
                ),
                (
                    'check_out_at',
                    models.DateTimeField(
                        blank=True, help_text='Patient check-out time.', null=True
                    ),
                ),
                (
                    'cancellation_reason',
                    models.TextField(blank=True, help_text='Reason for cancellation.'),
                ),
                (
                    'is_virtual',
                    models.BooleanField(
                        default=False,
                        help_text='Whether this is a virtual appointment.',
                    ),
                ),
                (
                    'meeting_url',
                    models.URLField(blank=True, help_text='Virtual meeting URL.'),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns this appointment.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='appointments',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        help_text='Patient for the appointment.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='appointments',
                        to='patients.patient',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ('-scheduled_start',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
    ]
