# Generated by Django 6.0.6 on 2026-07-28 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(
                help_text='Patient for the appointment.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='appointments',
                to='patients.patient',
            ),
        ),
    ]
