# Generated by Django 6.0.6 on 2026-07-27 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(
                help_text='Healthcare provider assigned to the appointment.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='appointments',
                to='providers.provider',
            ),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(
                fields=['appointment_number'], name='appointment_appoint_e7d91b_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(
                fields=['organization'], name='appointment_organiz_a77c6b_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(
                fields=['scheduled_start'], name='appointment_schedul_eb43c5_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_9fecd6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(
                fields=['patient'], name='appointment_patient_75a4eb_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(
                fields=['provider'], name='appointment_provide_7523ed_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(
                fields=['provider', 'scheduled_start'],
                name='appointment_provide_7c92e2_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(
                fields=['patient', 'scheduled_start'],
                name='appointment_patient_fdc364_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(
                fields=('organization', 'appointment_number'),
                name='unique_appointment_number_per_organization',
            ),
        ),
    ]
