# Generated by Django 6.0.6 on 2026-09-11 02:05

import apps.core.models.managers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('organizations', '0001_initial'),
        ('patient_core', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('scheduled_start', 'appointment_number')},
        ),
        migrations.AlterModelManagers(
            name='appointment',
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment_number_per_organization',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_appoint_e7d91b_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_organiz_a77c6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_schedul_eb43c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_status_9fecd6_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_patient_75a4eb_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_provide_7523ed_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_provider_start_idx',
            old_name='appointment_provide_7c92e2_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_patient_start_idx',
            old_name='appointment_patient_fdc364_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(
                choices=[
                    ('in_person', 'In Person'),
                    ('virtual', 'Virtual'),
                    ('follow_up', 'Follow Up'),
                    ('consultation', 'Consultation'),
                    ('procedure', 'Procedure'),
                    ('emergency', 'Emergency'),
                ],
                default='in_person',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='check_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='check_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='meeting_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='clinical_appointments',
                to='organizations.organization',
            ),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='clinical_appointments',
                to='patient_core.patient',
            ),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='priority',
            field=models.CharField(
                choices=[
                    ('routine', 'Routine'),
                    ('urgent', 'Urgent'),
                    ('emergency', 'Emergency'),
                ],
                db_index=True,
                default='routine',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='clinical_appointments',
                to='providers.provider',
            ),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_end',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_start',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(
                choices=[
                    ('scheduled', 'Scheduled'),
                    ('confirmed', 'Confirmed'),
                    ('checked_in', 'Checked In'),
                    ('in_progress', 'In Progress'),
                    ('completed', 'Completed'),
                    ('cancelled', 'Cancelled'),
                    ('no_show', 'No Show'),
                ],
                db_index=True,
                default='scheduled',
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(
                fields=['organization', 'scheduled_start'], name='appt_org_start_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(
                condition=models.Q(('scheduled_end__gt', models.F('scheduled_start'))),
                name='appointment_end_after_start',
            ),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(
                condition=models.Q(('duration_minutes__gt', 0)),
                name='appointment_duration_positive',
            ),
        ),
        migrations.AlterModelTable(
            name='appointment',
            table=None,
        ),
    ]
