# Generated by Django 6.0.6 on 2026-10-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_options_alter_appointment_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reschedule_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
