# Generated by Django 6.0.6 on 2026-10-01 09:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_reschedule_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_invoice_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='final_invoice_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
