# Generated by Django 6.0.6 on 2026-10-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tracking_token_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
