"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from datetime import timedelta
from pathlib import Path

from decouple import config

from config.logging import LOGGING as DJANGO_LOGGING

# ------------------------------------------------------------------------------
# Base Directory
# ------------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------------------------
# Security
# ------------------------------------------------------------------------------
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-local-development-key",
)


def _parse_debug(value: str | bool) -> bool:
    """Parse boolean and conventional deployment-mode DEBUG values safely."""
    if isinstance(value, bool):
        return value

    normalized = value.strip().lower()
    if normalized in {"1", "true", "yes", "on", "development", "dev"}:
        return True
    if normalized in {"", "0", "false", "no", "off", "production", "prod", "release"}:
        return False

    raise ValueError(
        "DEBUG must be a boolean or a supported deployment mode "
        "(development, production, or release)."
    )


DEBUG = config(
    "DEBUG",
    default=False,
    cast=_parse_debug,
)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
    cast=lambda value: [host.strip() for host in value.split(",")],
)

# ------------------------------------------------------------------------------
# Applications
# ------------------------------------------------------------------------------

INSTALLED_APPS = [
    # Django Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third Party
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "drf_spectacular",
    # Celery
    "django_celery_results",
    "django_celery_beat",
    # Local Apps
    "apps.platform.tenancy",
    "apps.core.apps.CoreConfig",
    "apps.common.apps.CommonConfig",
    "apps.documents",
    "apps.platform.accounts.apps.AccountsConfig",
    "apps.platform.organizations.apps.OrganizationsConfig",
    "apps.platform.rbac.apps.RBACConfig",
    "apps.organization.departments.apps.DepartmentsConfig",
    "apps.organization.teams.apps.TeamsConfig",
    "apps.organization.employees.apps.EmployeesConfig",
    "apps.platform.audit.apps.AuditConfig",
    "apps.platform.saas_billing.apps.SaaSBillingConfig",
    "apps.configuration.apps.ConfigurationConfig",
    "apps.billing.apps.BillingConfig",
    "apps.billing.general_ledger.apps.GeneralLedgerConfig",
    "apps.billing.accounts_payable.apps.AccountsPayableConfig",
    "apps.billing.accounts_receivable.apps.AccountsReceivableConfig",
    "apps.billing.cash_management.apps.CashManagementConfig",
    "apps.billing.tax_gst.apps.TaxGstConfig",
    "apps.billing.financial_management.apps.FinancialManagementConfig",
    "apps.clinical.patients.apps.PatientsConfig",
    "apps.clinical.providers.apps.ProvidersConfig",
    "apps.clinical.appointments.apps.AppointmentsConfig",
    "apps.clinical.encounters.apps.EncountersConfig",
    "apps.clinical.diagnoses.apps.DiagnosesConfig",
    "apps.clinical.medications.apps.MedicationsConfig",
    "apps.clinical.prescriptions.apps.PrescriptionsConfig",
    "apps.clinical.allergies.apps.AllergiesConfig",
    "apps.clinical.vitals.apps.VitalsConfig",
    "apps.clinical.laboratories.apps.LaboratoriesConfig",
    "apps.notes.apps.NotesConfig",
    "apps.telemedicine.apps.TelemedicineConfig",
    "apps.ai.apps.AIConfig",
    "apps.imaging.apps.ImagingConfig",
    "apps.insurance.apps.InsuranceConfig",
    "apps.transcription.apps.TranscriptionConfig",
    "apps.interoperability.apps.InteroperabilityConfig",
    "apps.revenue_cycle.apps.RevenueCycleConfig",
    "apps.patient_management.apps.PatientManagementConfig",
    "apps.compliance.apps.ComplianceConfig",
    "apps.datavionos.apps.DatavionOSConfig",
    "apps.platform.subscriptions.apps.SubscriptionsConfig",
    "apps.platform.feature_flags.apps.FeatureFlagsConfig",
    "apps.platform.module_registry.apps.ModuleRegistryConfig",
    "apps.platform.dashboard.apps.DashboardConfig",
    "apps.platform.notifications.apps.NotificationsConfig",
]

# ------------------------------------------------------------------------------
# Middleware
# ------------------------------------------------------------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    # Request tracing
    "apps.common.middleware.RequestIDMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    # Authentication must run before tenant resolution
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # DatavionOS SaaS tenant context
    "apps.platform.tenancy.middleware.TenantMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

# ------------------------------------------------------------------------------
# Templates
# ------------------------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ------------------------------------------------------------------------------
# Database
# ------------------------------------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DATABASE_NAME", default="datavion"),
        "USER": config("DATABASE_USER", default="postgres"),
        "PASSWORD": config("DATABASE_PASSWORD", default="postgres"),
        "HOST": config("DATABASE_HOST", default="localhost"),
        "PORT": config("DATABASE_PORT", default="5432"),
        "CONN_MAX_AGE": 60,
        "CONN_HEALTH_CHECKS": True,
    }
}
# ------------------------------------------------------------------------------
# Password Validation
# ------------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 12,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
# ------------------------------------------------------------------------------
# Email
# ------------------------------------------------------------------------------

EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend",
)

EMAIL_HOST = config(
    "EMAIL_HOST",
    default="smtp.gmail.com",
)

EMAIL_PORT = config(
    "EMAIL_PORT",
    default=587,
    cast=int,
)

EMAIL_USE_TLS = config(
    "EMAIL_USE_TLS",
    default=True,
    cast=bool,
)

EMAIL_USE_SSL = config(
    "EMAIL_USE_SSL",
    default=False,
    cast=bool,
)

EMAIL_HOST_USER = config(
    "EMAIL_HOST_USER",
    default="",
)

EMAIL_HOST_PASSWORD = config(
    "EMAIL_HOST_PASSWORD",
    default="",
)

DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default="DatavionAI <noreply@datavion.ai>",
)

SERVER_EMAIL = config(
    "SERVER_EMAIL",
    default=DEFAULT_FROM_EMAIL,
)

EMAIL_TIMEOUT = 30

# ------------------------------------------------------------------------------
# Cache
# ------------------------------------------------------------------------------

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "datavion-cache",
    },
}
# ------------------------------------------------------------------------------
# Internationalization
# ------------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True

# ------------------------------------------------------------------------------
# Custom User
# ------------------------------------------------------------------------------

AUTH_USER_MODEL = "accounts.User"


# ------------------------------------------------------------------------------
# Authentication
# ------------------------------------------------------------------------------

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]
# ------------------------------------------------------------------------------
# Login
# ------------------------------------------------------------------------------

LOGIN_URL = "/api/auth/login/"

LOGIN_REDIRECT_URL = "/"

LOGOUT_REDIRECT_URL = "/"
# ------------------------------------------------------------------------------
# Static Files
# ------------------------------------------------------------------------------

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# ==============================================================================
# Application
# ==============================================================================

APP_NAME = "Datavion AI"
APP_VERSION = "1.0.0"
APP_ENVIRONMENT = config(
    "APP_ENVIRONMENT",
    default="development",
)
DEFAULT_PAGE_SIZE = 20

MAX_PAGE_SIZE = 100

DEFAULT_TIMEZONE = "Asia/Kolkata"
# ------------------------------------------------------------------------------
# Django REST Framework
# ------------------------------------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.platform.tenancy.authentication.TenantJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_PAGINATION_CLASS": "apps.common.api.pagination.DatavionPagination",
    "PAGE_SIZE": DEFAULT_PAGE_SIZE,
    # Enterprise exception handler
    "EXCEPTION_HANDLER": ("apps.common.exceptions.handlers.datavion_exception_handler"),
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
    },
}
# ------------------------------------------------------------------------------
# CORS
# ------------------------------------------------------------------------------

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
# ------------------------------------------------------------------------------
# JWT
# ------------------------------------------------------------------------------

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "LEEWAY": 0,
}

# ------------------------------------------------------------------------------
# Swagger / OpenAPI
# ------------------------------------------------------------------------------

SPECTACULAR_SETTINGS = {
    "TITLE": APP_NAME,
    "DESCRIPTION": "AI Powered Revenue Cycle Management Platform",
    "VERSION": APP_VERSION,
    "SERVE_INCLUDE_SCHEMA": False,
    "SECURITY": [
        {
            "BearerAuth": [],
        }
    ],
    "COMPONENT_SPLIT_REQUEST": True,
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
}


# ------------------------------------------------------------------------------
# Celery
# ------------------------------------------------------------------------------

CELERY_BROKER_URL = config(
    "CELERY_BROKER_URL",
    default="redis://127.0.0.1:6379/0",
)

CELERY_RESULT_BACKEND = config(
    "CELERY_RESULT_BACKEND",
    default="redis://127.0.0.1:6379/1",
)

CELERY_ACCEPT_CONTENT = [
    "json",
]

CELERY_TASK_SERIALIZER = "json"

CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = TIME_ZONE

CELERY_ENABLE_UTC = USE_TZ

CELERY_TASK_TRACK_STARTED = True

CELERY_TASK_TIME_LIMIT = 300

CELERY_TASK_ALWAYS_EAGER = False

CELERY_TASK_IGNORE_RESULT = False


# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------

LOGGING = DJANGO_LOGGING

# ----# ------------------------------------------------------------------------------
# Production Security
# ------------------------------------------------------------------------------

if not DEBUG:
    SECURE_CONTENT_TYPE_NOSNIFF = True

    X_FRAME_OPTIONS = "DENY"

    SECURE_REFERRER_POLICY = "same-origin"
    SESSION_COOKIE_AGE = 60 * 60 * 8

    SESSION_SAVE_EVERY_REQUEST = True

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    SECURE_SSL_REDIRECT = True

    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )
    SECURE_HSTS_SECONDS = 31536000

    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    SECURE_HSTS_PRELOAD = True
# --------------------------------------------------------------------------
# Default Primary Key
# ------------------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
