# Generated by Django 6.0.6 on 2026-07-31 11:49

import apps.core.models.managers
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('CREATE', 'Create'),
                            ('UPDATE', 'Update'),
                            ('DELETE', 'Delete'),
                            ('RESTORE', 'Restore'),
                            ('LOGIN', 'Login'),
                            ('LOGOUT', 'Logout'),
                            ('FAILED_LOGIN', 'Failed Login'),
                            ('PASSWORD_RESET', 'Password Reset'),
                            ('APPROVE', 'Approve'),
                            ('REJECT', 'Reject'),
                            ('ROLE_CHANGE', 'Role Change'),
                            ('PERMISSION_CHANGE', 'Permission Change'),
                            ('VIEW', 'View'),
                            ('ACCESS', 'Access'),
                            ('DOWNLOAD', 'Download'),
                            ('PRINT', 'Print'),
                            ('SHARE', 'Share'),
                            ('CONSENT', 'Consent'),
                            ('SIGN', 'Sign'),
                            ('EXPORT', 'Export'),
                            ('IMPORT', 'Import'),
                            ('AI_ACCESS', 'AI Access'),
                            ('AI_GENERATION', 'AI Generation'),
                            ('AI_EXECUTION', 'AI Execution'),
                            ('AI_APPROVAL', 'AI Approval'),
                            ('AI_FEEDBACK', 'AI Feedback'),
                            ('WORKFLOW_START', 'Workflow Start'),
                            ('WORKFLOW_COMPLETE', 'Workflow Complete'),
                            ('WORKFLOW_APPROVE', 'Workflow Approve'),
                            ('WORKFLOW_REJECT', 'Workflow Reject'),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('object_type', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=100)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                (
                    'request_id',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=100
                    ),
                ),
                (
                    'correlation_id',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=100
                    ),
                ),
                (
                    'session_key',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=100
                    ),
                ),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                (
                    'http_method',
                    models.CharField(blank=True, default='', max_length=10),
                ),
                (
                    'request_path',
                    models.CharField(blank=True, default='', max_length=500),
                ),
                (
                    'status_code',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                (
                    'organization',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='audit_logs',
                        to='organizations.organization',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='audit_logs',
                        to='tenancy.tenant',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='audit_logs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(
                        fields=['tenant', 'created_at'], name='audit_tenant_created_idx'
                    ),
                    models.Index(
                        fields=['organization', 'created_at'],
                        name='audit_org_created_idx',
                    ),
                    models.Index(
                        fields=['user', 'created_at'], name='audit_user_created_idx'
                    ),
                    models.Index(
                        fields=['action', 'created_at'], name='audit_action_created_idx'
                    ),
                    models.Index(
                        fields=['module', 'created_at'], name='audit_module_created_idx'
                    ),
                    models.Index(
                        fields=['object_type', 'object_id'], name='audit_object_idx'
                    ),
                    models.Index(fields=['request_id'], name='audit_request_idx'),
                    models.Index(fields=['correlation_id'], name='audit_corr_idx'),
                ],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('module', ''), _negated=True),
                        name='audit_module_required',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('object_type', ''), _negated=True),
                        name='audit_object_type_required',
                    ),
                ],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
    ]
