# Generated by Django 6.0.6 on 2026-09-09 03:06

import apps.patient_management.family_members.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('patient_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'family_member_number',
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name='Family Member Number',
                    ),
                ),
                (
                    'first_name',
                    models.CharField(
                        max_length=100,
                        validators=[
                            apps.patient_management.family_members.validators.validate_family_member_name
                        ],
                        verbose_name='First Name',
                    ),
                ),
                (
                    'middle_name',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Middle Name'
                    ),
                ),
                (
                    'last_name',
                    models.CharField(
                        max_length=100,
                        validators=[
                            apps.patient_management.family_members.validators.validate_family_member_name
                        ],
                        verbose_name='Last Name',
                    ),
                ),
                (
                    'relationship',
                    models.CharField(
                        choices=[
                            ('FATHER', 'Father'),
                            ('MOTHER', 'Mother'),
                            ('HUSBAND', 'Husband'),
                            ('WIFE', 'Wife'),
                            ('SPOUSE', 'Spouse'),
                            ('SON', 'Son'),
                            ('DAUGHTER', 'Daughter'),
                            ('BROTHER', 'Brother'),
                            ('SISTER', 'Sister'),
                            ('GRANDFATHER', 'Grandfather'),
                            ('GRANDMOTHER', 'Grandmother'),
                            ('UNCLE', 'Uncle'),
                            ('AUNT', 'Aunt'),
                            ('COUSIN', 'Cousin'),
                            ('GUARDIAN', 'Guardian'),
                            ('CAREGIVER', 'Caregiver'),
                            ('FATHER_IN_LAW', 'Father-in-law'),
                            ('MOTHER_IN_LAW', 'Mother-in-law'),
                            ('BROTHER_IN_LAW', 'Brother-in-law'),
                            ('SISTER_IN_LAW', 'Sister-in-law'),
                            ('STEP_FATHER', 'Step Father'),
                            ('STEP_MOTHER', 'Step Mother'),
                            ('STEP_BROTHER', 'Step Brother'),
                            ('STEP_SISTER', 'Step Sister'),
                            ('LEGAL_GUARDIAN', 'Legal Guardian'),
                            ('OTHER', 'Other'),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name='Relationship',
                    ),
                ),
                (
                    'gender',
                    models.CharField(
                        choices=[
                            ('MALE', 'Male'),
                            ('FEMALE', 'Female'),
                            ('OTHER', 'Other'),
                            ('UNKNOWN', 'Unknown'),
                        ],
                        default='UNKNOWN',
                        max_length=20,
                        verbose_name='Gender',
                    ),
                ),
                (
                    'date_of_birth',
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[
                            apps.patient_management.family_members.validators.validate_date_of_birth
                        ],
                        verbose_name='Date of Birth',
                    ),
                ),
                (
                    'mobile_number',
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            apps.patient_management.family_members.validators.validate_mobile_number
                        ],
                        verbose_name='Mobile Number',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        validators=[
                            apps.patient_management.family_members.validators.validate_email_address
                        ],
                        verbose_name='Email',
                    ),
                ),
                (
                    'blood_group',
                    models.CharField(
                        blank=True, max_length=5, verbose_name='Blood Group'
                    ),
                ),
                (
                    'occupation',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='Occupation'
                    ),
                ),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                (
                    'city',
                    models.CharField(blank=True, max_length=100, verbose_name='City'),
                ),
                (
                    'state',
                    models.CharField(blank=True, max_length=100, verbose_name='State'),
                ),
                (
                    'postal_code',
                    models.CharField(
                        blank=True, max_length=20, verbose_name='Postal Code'
                    ),
                ),
                (
                    'country',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Country'
                    ),
                ),
                ('is_living', models.BooleanField(default=True, verbose_name='Living')),
                (
                    'is_emergency_contact',
                    models.BooleanField(
                        db_index=True, default=False, verbose_name='Emergency Contact'
                    ),
                ),
                (
                    'is_next_of_kin',
                    models.BooleanField(
                        db_index=True, default=False, verbose_name='Next of Kin'
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True,
                        validators=[
                            apps.patient_management.family_members.validators.validate_notes
                        ],
                        verbose_name='Notes',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')],
                        db_index=True,
                        default='ACTIVE',
                        max_length=20,
                        verbose_name='Status',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='family_members',
                        to='organizations.organization',
                        verbose_name='Organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='family_members',
                        to='patient_core.patient',
                        verbose_name='Patient',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Family Member',
                'verbose_name_plural': 'Family Members',
                'ordering': ('first_name', 'last_name'),
                'indexes': [
                    models.Index(
                        fields=['organization', 'patient'], name='fm_org_patient_idx'
                    ),
                    models.Index(
                        fields=['organization', 'is_deleted'], name='fm_org_deleted_idx'
                    ),
                    models.Index(
                        fields=['patient', 'relationship'],
                        name='fm_patient_relationship_idx',
                    ),
                    models.Index(
                        fields=['patient', 'status'], name='fm_patient_status_idx'
                    ),
                    models.Index(
                        fields=['patient', 'is_next_of_kin'],
                        name='fm_patient_next_kin_idx',
                    ),
                    models.Index(
                        fields=['patient', 'is_emergency_contact'],
                        name='fm_patient_emergency_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('is_deleted', False)),
                        fields=('patient', 'relationship', 'first_name', 'last_name'),
                        name='uniq_active_patient_family_member',
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ('is_deleted', False), ('is_next_of_kin', True)
                        ),
                        fields=('patient',),
                        name='uniq_active_patient_next_of_kin',
                    ),
                ],
            },
        ),
    ]
