"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useMutation, useQueries, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, BarChart3, CalendarDays, ClipboardCheck, FileText, House, Settings, Users } from "lucide-react";
import { apiClient } from "@/core/api";
import { useBootstrap } from "@/core/bootstrap";
import type { ModuleRuntimeDefinition } from "../../domain/types";

type Row = Record<string, unknown>; type Payload = Row[] | { results?: Row[]; data?: Row[] };
const list = (value: Payload | undefined) => Array.isArray(value) ? value : value?.results ?? value?.data ?? [];
const show = (value: unknown, fallback = "-") => value === null || value === undefined || value === "" ? fallback : String(value);
const nav = [["Overview", "overview", House], ["Staff", "staff", Users], ["Patients", "patients", Users], ["Appointments", "appointments", CalendarDays], ["Tasks", "tasks", ClipboardCheck], ["Performance", "performance", BarChart3], ["Analytics", "analytics", BarChart3], ["Reports", "reports", FileText], ["Settings", "settings", Settings]] as const;

export function DepartmentManagerWorkspace({ module }: { module: ModuleRuntimeDefinition }) {
  const { bootstrap } = useBootstrap(); const organization = bootstrap?.organization?.id; const section = useSearchParams().get("section") ?? "overview";
  const sources = [["departments", "/departments/"], ["staff", "/employees/"], ["patients", "/patients/"], ["appointments", "/appointments/"], ["tasks", "/nursing/tasks/"]] as const;
  const queries = useQueries({ queries: sources.map(([key, path]) => ({ queryKey: ["department-manager", key, organization], queryFn: async () => (await apiClient.get<Payload>(path, { params: { organization_id: organization, limit: 100 } })).data, enabled: Boolean(organization) })) });
  const data = Object.fromEntries(sources.map(([key], index) => [key, list(queries[index].data)])) as Record<string, Row[]>; const department = data.departments[0]; const departmentId = show(department?.id, "");
  const scoped = { staff: data.staff.filter((row) => !departmentId || show(row.department ?? row.department_id, departmentId) === departmentId), patients: data.patients, appointments: data.appointments.filter((row) => !departmentId || show(row.department ?? row.department_id, departmentId) === departmentId), tasks: data.tasks.filter((row) => !departmentId || show(row.department ?? row.department_id, departmentId) === departmentId) };
  const active = scoped.staff.filter((row) => row.is_active !== false && row.status !== "inactive"); const today = new Date().toISOString().slice(0, 10); const todayAppointments = scoped.appointments.filter((row) => show(row.scheduled_start ?? row.appointment_date).startsWith(today)); const pending = scoped.tasks.filter((row) => ["pending", "in_progress"].includes(show(row.status))); const completed = scoped.tasks.filter((row) => row.status === "completed"); const completion = scoped.tasks.length ? Math.round(completed.length / scoped.tasks.length * 100) : 0;
  const greeting = new Date().getHours() < 12 ? "Good morning" : new Date().getHours() < 17 ? "Good afternoon" : "Good evening";
  const baseRoute = `/workspace/${module.identifier}`;
  return <section className="container-fluid py-4"><div className="row g-4"><aside className="col-12 col-xl-2"><nav className="card border-0 shadow-sm p-2">{nav.map(([label, target, Icon]) => <Link key={target} href={target === "overview" ? baseRoute : `${baseRoute}?section=${target}`} className={`nav-link d-flex gap-2 align-items-center rounded px-3 py-2 ${section === target ? "active" : "text-body"}`}><Icon size={18}/>{label}</Link>)}</nav></aside><main className="col-12 col-xl-10">{section === "overview" ? <><header className="mb-4"><h1 className="h2">{greeting}, Department Manager</h1><p className="text-body-secondary">{show(department?.name, module.displayName)} • {bootstrap?.organization?.name}</p></header><div className="row g-3 mb-4"><Kpi title="Staff" value={scoped.staff.length} detail={`${active.length} active`}/><Kpi title="Patients" value={scoped.patients.length} detail="Department census"/><Kpi title="Appointments" value={todayAppointments.length} detail="Today"/><Kpi title="Tasks" value={pending.length} detail="Pending" danger={pending.length > 0}/></div><div className="row g-4"><div className="col-lg-7"><Panel title="Department Performance"><div className="py-4"><div className="d-flex justify-content-between mb-2"><span>Task completion</span><strong>{completion}%</strong></div><div className="progress" role="progressbar" aria-label="Task completion"><div className="progress-bar" style={{ width: `${completion}%` }}/></div><div className="row text-center mt-4"><div className="col"><strong>{active.length}</strong><small className="d-block text-body-secondary">Active staff</small></div><div className="col"><strong>{todayAppointments.length}</strong><small className="d-block text-body-secondary">Today</small></div><div className="col"><strong>{completed.length}</strong><small className="d-block text-body-secondary">Tasks done</small></div></div></div></Panel></div><div className="col-lg-5"><Panel title="Department Alerts"><Alert text={`${pending.length} pending tasks`} danger={pending.length > 0}/><Alert text={`${Math.max(scoped.staff.length - active.length, 0)} staffing gaps`}/><div className="border-bottom py-3 text-success">✓ {completion}% task completion</div></Panel></div></div></> : <DepartmentSection section={section} organization={organization ?? ""} data={{ departments: data.departments, ...scoped }} />}</main></div></section>;
}

function DepartmentSection({ section, organization, data }: { section: string; organization: string; data: Record<string, Row[]> }) {
  const client = useQueryClient(); const configs: Record<string, { key: string; title: string; columns: string[] }> = { staff: { key: "staff", title: "Department Staff", columns: ["employee_code", "full_name", "designation", "status", "is_active"] }, patients: { key: "patients", title: "Department Patients", columns: ["patient_number", "display_name", "gender", "status"] }, appointments: { key: "appointments", title: "Appointments", columns: ["appointment_number", "patient_name", "scheduled_start", "status"] }, tasks: { key: "tasks", title: "Department Tasks", columns: ["title", "patient_name", "priority", "due_at", "status"] }, performance: { key: "tasks", title: "Performance", columns: ["title", "priority", "status", "completed_at"] }, analytics: { key: "appointments", title: "Department Analytics", columns: ["appointment_number", "scheduled_start", "status"] }, reports: { key: "tasks", title: "Department Reports", columns: ["title", "priority", "status", "completed_at"] }, settings: { key: "departments", title: "Department Settings", columns: ["code", "name", "department_type", "status"] } }; const config = configs[section] ?? configs.staff;
  const complete = useMutation({ mutationFn: async (row: Row) => apiClient.post(`/nursing/tasks/${row.id}/complete/`, { organization_id: organization, completion_notes: "Completed by department manager" }), onSuccess: () => client.invalidateQueries({ queryKey: ["department-manager"] }) });
  return <div className="card border-0 shadow-sm"><div className="card-body p-4"><h1 className="h4">{config.title}</h1><div className="table-responsive"><table className="table align-middle"><thead><tr>{config.columns.map((column) => <th key={column}>{column.replaceAll("_", " ")}</th>)}<th>Actions</th></tr></thead><tbody>{data[config.key].map((row) => <tr key={show(row.id)}>{config.columns.map((column) => <td key={column}>{show(row[column])}</td>)}<td>{config.key === "tasks" && ["pending", "in_progress"].includes(show(row.status)) && <button className="btn btn-sm btn-outline-primary" onClick={() => complete.mutate(row)}>Complete</button>}</td></tr>)}{!data[config.key].length && <tr><td colSpan={config.columns.length + 1} className="text-center text-body-secondary py-4">No records available.</td></tr>}</tbody></table></div></div></div>;
}
function Kpi({ title, value, detail, danger = false }: { title: string; value: number; detail: string; danger?: boolean }) { return <div className="col-12 col-sm-6 col-xl-3"><div className="card border-0 shadow-sm h-100"><div className="card-body"><span className="text-body-secondary">{title}</span><div className={`display-6 fw-semibold my-2 ${danger ? "text-danger" : ""}`}>{value}</div><small>{detail}</small></div></div></div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <div className="card border-0 shadow-sm h-100"><div className="card-body p-4"><h2 className="h5">{title}</h2>{children}</div></div>; }
function Alert({ text, danger = false }: { text: string; danger?: boolean }) { return <div className={`border-bottom py-3 ${danger ? "text-danger" : "text-warning-emphasis"}`}><AlertTriangle size={17} className="me-2"/>{text}</div>; }
