"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useMutation, useQueries, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, Boxes, Building2, ClipboardList, House, PackageCheck, Settings, Truck, Users } from "lucide-react";
import { apiClient } from "@/core/api";
import { useBootstrap } from "@/core/bootstrap";
import { useState } from "react";
import type { ModuleRuntimeDefinition } from "../../domain/types";

type Row = Record<string, unknown>; type Payload = Row[] | { results?: Row[] };
const list = (value: Payload | undefined) => Array.isArray(value) ? value : value?.results ?? [];
const show = (value: unknown, fallback = "-") => value === null || value === undefined || value === "" ? fallback : String(value);
const nav = [["Overview", "overview", House], ["Inventory", "inventory", Boxes], ["Warehouses", "warehouses", Building2], ["Purchase", "purchases", ClipboardList], ["Transfers", "transfers", Truck], ["Stock", "stock", PackageCheck], ["Suppliers", "suppliers", Users], ["Reports", "reports", AlertTriangle], ["Settings", "settings", Settings]] as const;

export function InventoryBusinessWorkspace({ module }: { module: ModuleRuntimeDefinition }) {
  const { bootstrap } = useBootstrap(); const organization = bootstrap?.organization?.id; const section = useSearchParams().get("section") ?? "overview";
  const [now] = useState(() => Date.now());
  const sources = [["warehouses", "/pharmacy/pharmacies/"], ["products", "/pharmacy/products/"], ["batches", "/pharmacy/batches/"], ["purchases", "/pharmacy/purchase-orders/"], ["transfers", "/pharmacy/stock-transfers/"], ["movements", "/pharmacy/stock-movements/"], ["suppliers", "/pharmacy/suppliers/"]] as const;
  const queries = useQueries({ queries: sources.map(([key, path]) => ({ queryKey: ["inventory-manager", key, organization], queryFn: async () => (await apiClient.get<Payload>(path, { params: { organization_id: organization, limit: 100 } })).data, enabled: Boolean(organization) })) });
  const data = Object.fromEntries(sources.map(([key], index) => [key, list(queries[index].data)])) as Record<string, Row[]>;
  const inventory = useQuery({ queryKey: ["inventory-manager", "stock", organization, data.warehouses.map((row) => row.id).join(",")], queryFn: async () => (await Promise.all(data.warehouses.map(async (warehouse) => (await apiClient.get<Row[]>("/pharmacy/inventory/", { params: { pharmacy_id: warehouse.id } })).data))).flat(), enabled: data.warehouses.length > 0 });
  const stock = inventory.data ?? []; const low = stock.filter((row) => Number(row.stock) > 0 && Number(row.stock) <= Number(row.reorder_level)); const out = stock.filter((row) => Number(row.stock) <= 0); const expiring = data.batches.filter((row) => { const time = Date.parse(show(row.expiry_date, "")); return time >= now && time <= now + 30 * 86400000; });
  const hour = new Date(now).getHours(); const greeting = hour < 12 ? "Good morning" : hour < 17 ? "Good afternoon" : "Good evening";
  return <section className="container-fluid py-4"><div className="row g-4"><aside className="col-12 col-xl-2"><nav className="card border-0 shadow-sm p-2">{nav.map(([label, target, Icon]) => <Link key={target} href={target === "overview" ? "/workspace/inventory" : `/workspace/inventory?section=${target}`} className={`nav-link d-flex gap-2 align-items-center rounded px-3 py-2 ${section === target ? "active" : "text-body"}`}><Icon size={18}/>{label}</Link>)}</nav></aside><main className="col-12 col-xl-10">{section === "overview" ? <><header className="mb-4"><h1 className="h2">{greeting}, Inventory Manager</h1><p className="text-body-secondary">Central Inventory • {bootstrap?.organization?.name ?? module.displayName}</p></header><div className="row g-3 mb-4"><Kpi title="Total Items" value={stock.reduce((sum, row) => sum + Number(row.stock || 0), 0)} detail={`${data.products.length} SKUs`} /><Kpi title="Low Stock" value={low.length} detail="Attention"/><Kpi title="Out Stock" value={out.length} detail="Critical" danger={out.length > 0}/><Kpi title="Expiring" value={expiring.length} detail="Within 30 days"/></div><div className="row g-4"><div className="col-lg-7"><Panel title="Stock Movement">{data.movements.slice(0, 8).map((row) => <div className="border-bottom py-3" key={show(row.id)}><strong>{show(row.sku)} • {show(row.movement_type)}</strong><span className="float-end">{show(row.quantity)}</span><div className="small text-body-secondary">{show(row.medication_name)} • {show(row.batch_number)}</div></div>)}</Panel></div><div className="col-lg-5"><Panel title="Inventory Alerts"><Alert text={`${out.length} out of stock`} danger/><Alert text={`${low.length} low stock`}/><Alert text={`${expiring.length} expiring`}/></Panel></div></div></> : <InventorySection section={section} organization={organization ?? ""} data={{ ...data, inventory: stock }} />}</main></div></section>;
}

function InventorySection({ section, organization, data }: { section: string; organization: string; data: Record<string, Row[]> }) {
  const client = useQueryClient(); const configs: Record<string, { key: string; title: string; columns: string[] }> = { inventory: { key: "inventory", title: "Inventory", columns: ["sku", "medication", "stock", "reorder_level"] }, warehouses: { key: "warehouses", title: "Warehouses", columns: ["code", "name", "status", "phone"] }, purchases: { key: "purchases", title: "Purchase Orders", columns: ["order_number", "pharmacy_name", "supplier_name", "status"] }, transfers: { key: "transfers", title: "Stock Transfers", columns: ["transfer_number", "source_name", "destination_name", "status", "completed_at"] }, stock: { key: "movements", title: "Stock Movement", columns: ["sku", "medication_name", "batch_number", "movement_type", "quantity", "created_at"] }, suppliers: { key: "suppliers", title: "Suppliers", columns: ["code", "name", "contact_name", "phone"] }, reports: { key: "inventory", title: "Inventory Reports", columns: ["sku", "medication", "stock", "reorder_level"] }, settings: { key: "warehouses", title: "Inventory Settings", columns: ["code", "name", "status"] } }; const config = configs[section] ?? configs.inventory;
  const complete = useMutation({ mutationFn: async (row: Row) => apiClient.post(`/pharmacy/stock-transfers/${row.id}/complete/`, { organization_id: organization }), onSuccess: () => client.invalidateQueries({ queryKey: ["inventory-manager"] }) });
  return <div className="card border-0 shadow-sm"><div className="card-body p-4"><h1 className="h4">{config.title}</h1><div className="table-responsive"><table className="table align-middle"><thead><tr>{config.columns.map((column) => <th key={column}>{column.replaceAll("_", " ")}</th>)}<th>Actions</th></tr></thead><tbody>{data[config.key].map((row) => <tr key={show(row.id ?? row.product_id)}>{config.columns.map((column) => <td key={column}>{show(row[column])}</td>)}<td>{section === "transfers" && ["approved", "in_transit"].includes(show(row.status)) && <button className="btn btn-sm btn-outline-primary" onClick={() => complete.mutate(row)}>Complete</button>}</td></tr>)}{!data[config.key].length && <tr><td colSpan={config.columns.length + 1} className="text-center text-body-secondary py-4">No records available.</td></tr>}</tbody></table></div></div></div>;
}
function Kpi({ title, value, detail, danger = false }: { title: string; value: number; detail: string; danger?: boolean }) { return <div className="col-12 col-sm-6 col-xl-3"><div className="card border-0 shadow-sm h-100"><div className="card-body"><span className="text-body-secondary">{title}</span><div className={`display-6 fw-semibold my-2 ${danger ? "text-danger" : ""}`}>{value}</div><small>{detail}</small></div></div></div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <div className="card border-0 shadow-sm h-100"><div className="card-body p-4"><h2 className="h5">{title}</h2>{children}</div></div>; }
function Alert({ text, danger = false }: { text: string; danger?: boolean }) { return <div className={`border-bottom py-3 ${danger ? "text-danger" : "text-warning-emphasis"}`}><AlertTriangle size={17} className="me-2"/>{text}</div>; }
