[pytest]
DJANGO_SETTINGS_MODULE = config.settings

python_files =
    test_*.py
    *_test.py

python_classes = Test*

python_functions = test_*

testpaths =
    apps
    tests

addopts =
    --import-mode=importlib
    -p no:cacheprovider
    --strict-markers
    --tb=short

filterwarnings =
    ignore::DeprecationWarning
