# Generated by Django 6.0.6 on 2026-07-31 11:49

import apps.core.models.managers
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'code',
                    models.CharField(blank=True, help_text='Code.', max_length=60),
                ),
                (
                    'name',
                    models.CharField(blank=True, help_text='Name.', max_length=150),
                ),
                (
                    'rate',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Rate.',
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    'tax_type',
                    models.CharField(blank=True, help_text='Tax Type.', max_length=40),
                ),
                ('description', models.TextField(blank=True, help_text='Description.')),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns the tax_rate record.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tax_gst_tax_rates',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'db_table': 'tax_gst_tax_rates',
                'ordering': ('name',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='TaxFiling',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'period',
                    models.CharField(blank=True, help_text='Period.', max_length=120),
                ),
                (
                    'period_start',
                    models.DateTimeField(
                        blank=True, db_index=True, help_text='Period Start.', null=True
                    ),
                ),
                (
                    'period_end',
                    models.DateTimeField(
                        blank=True, db_index=True, help_text='Period End.', null=True
                    ),
                ),
                ('reference', models.TextField(blank=True, help_text='Reference.')),
                (
                    'taxable_amount',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Taxable Amount.',
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    'tax_amount',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Tax Amount.',
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(blank=True, help_text='Status.', max_length=40),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tax_gst_tax_filings',
                        to='organizations.organization',
                    ),
                ),
                (
                    'tax_rate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='tax_filings',
                        to='tax_gst.taxrate',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Tax Filing',
                'verbose_name_plural': 'Tax Filings',
                'db_table': 'tax_gst_tax_filings',
                'ordering': ('-period_end',),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
    ]
