# Generated by Django 6.0.6 on 2026-09-09 03:06

import apps.core.models.managers
import apps.patient_management.emergency_contacts.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('patient_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'emergency_contact_number',
                    models.CharField(
                        help_text='System-generated emergency contact identifier.',
                        max_length=30,
                        validators=[
                            apps.patient_management.emergency_contacts.validators.validate_emergency_contact_number
                        ],
                        verbose_name='Emergency Contact Number',
                    ),
                ),
                (
                    'first_name',
                    models.CharField(max_length=100, verbose_name='First Name'),
                ),
                (
                    'middle_name',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Middle Name'
                    ),
                ),
                (
                    'last_name',
                    models.CharField(max_length=100, verbose_name='Last Name'),
                ),
                (
                    'relationship',
                    models.CharField(
                        choices=[
                            ('SPOUSE', 'Spouse'),
                            ('FATHER', 'Father'),
                            ('MOTHER', 'Mother'),
                            ('SON', 'Son'),
                            ('DAUGHTER', 'Daughter'),
                            ('BROTHER', 'Brother'),
                            ('SISTER', 'Sister'),
                            ('GRANDFATHER', 'Grandfather'),
                            ('GRANDMOTHER', 'Grandmother'),
                            ('UNCLE', 'Uncle'),
                            ('AUNT', 'Aunt'),
                            ('COUSIN', 'Cousin'),
                            ('FRIEND', 'Friend'),
                            ('GUARDIAN', 'Guardian'),
                            ('CAREGIVER', 'Caregiver'),
                            ('LEGAL_REPRESENTATIVE', 'Legal Representative'),
                            ('EMPLOYER', 'Employer'),
                            ('NEIGHBOR', 'Neighbor'),
                            ('OTHER', 'Other'),
                        ],
                        max_length=50,
                        verbose_name='Relationship',
                    ),
                ),
                (
                    'date_of_birth',
                    models.DateField(
                        blank=True, null=True, verbose_name='Date of Birth'
                    ),
                ),
                (
                    'mobile_number',
                    models.CharField(
                        max_length=20,
                        validators=[
                            apps.patient_management.emergency_contacts.validators.validate_phone_number
                        ],
                        verbose_name='Mobile Number',
                    ),
                ),
                (
                    'alternate_mobile_number',
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            apps.patient_management.emergency_contacts.validators.validate_phone_number
                        ],
                        verbose_name='Alternate Mobile Number',
                    ),
                ),
                (
                    'home_phone',
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            apps.patient_management.emergency_contacts.validators.validate_phone_number
                        ],
                        verbose_name='Home Phone',
                    ),
                ),
                (
                    'work_phone',
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            apps.patient_management.emergency_contacts.validators.validate_phone_number
                        ],
                        verbose_name='Work Phone',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        validators=[
                            apps.patient_management.emergency_contacts.validators.validate_email_address
                        ],
                        verbose_name='Email',
                    ),
                ),
                (
                    'preferred_contact_method',
                    models.CharField(
                        choices=[
                            ('MOBILE', 'Mobile'),
                            ('HOME_PHONE', 'Home Phone'),
                            ('WORK_PHONE', 'Work Phone'),
                            ('EMAIL', 'Email'),
                            ('SMS', 'SMS'),
                            ('WHATSAPP', 'WhatsApp'),
                            ('ANY', 'Any'),
                        ],
                        default='MOBILE',
                        max_length=20,
                        verbose_name='Preferred Contact Method',
                    ),
                ),
                (
                    'address_line_1',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Address Line 1'
                    ),
                ),
                (
                    'address_line_2',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Address Line 2'
                    ),
                ),
                (
                    'city',
                    models.CharField(blank=True, max_length=100, verbose_name='City'),
                ),
                (
                    'state',
                    models.CharField(blank=True, max_length=100, verbose_name='State'),
                ),
                (
                    'postal_code',
                    models.CharField(
                        blank=True, max_length=20, verbose_name='Postal Code'
                    ),
                ),
                (
                    'country',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Country'
                    ),
                ),
                (
                    'is_primary',
                    models.BooleanField(
                        db_index=True, default=False, verbose_name='Primary'
                    ),
                ),
                (
                    'priority_order',
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            apps.patient_management.emergency_contacts.validators.validate_priority_order
                        ],
                        verbose_name='Priority Order',
                    ),
                ),
                (
                    'availability',
                    models.CharField(
                        choices=[
                            ('ALWAYS', 'Always Available'),
                            ('DAYTIME', 'Daytime'),
                            ('NIGHT', 'Night'),
                            ('BUSINESS_HOURS', 'Business Hours'),
                            ('WEEKENDS', 'Weekends'),
                            ('ON_CALL', 'On Call'),
                        ],
                        default='ALWAYS',
                        max_length=30,
                        verbose_name='Availability',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('ACTIVE', 'Active'),
                            ('INACTIVE', 'Inactive'),
                            ('BLOCKED', 'Blocked'),
                        ],
                        db_index=True,
                        default='ACTIVE',
                        max_length=20,
                        verbose_name='Status',
                    ),
                ),
                (
                    'is_verified',
                    models.BooleanField(
                        db_index=True, default=False, verbose_name='Verified'
                    ),
                ),
                (
                    'verified_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Verified At'
                    ),
                ),
                (
                    'is_legal_guardian',
                    models.BooleanField(default=False, verbose_name='Legal Guardian'),
                ),
                (
                    'has_medical_power_of_attorney',
                    models.BooleanField(
                        default=False, verbose_name='Medical Power of Attorney'
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True,
                        validators=[
                            apps.patient_management.emergency_contacts.validators.validate_notes
                        ],
                        verbose_name='Notes',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text='User that created this record.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_%(class)ss',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created By',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='emergency_contacts',
                        to='organizations.organization',
                        verbose_name='Organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='emergency_contacts',
                        to='patient_core.patient',
                        verbose_name='Patient',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text='User that most recently updated this record.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='updated_%(class)ss',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated By',
                    ),
                ),
                (
                    'verified_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Verified By',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ('priority_order', 'first_name', 'last_name'),
                'indexes': [
                    models.Index(
                        fields=['organization', 'patient'], name='idx_ec_org_patient'
                    ),
                    models.Index(
                        fields=['organization', 'is_deleted'], name='idx_ec_org_deleted'
                    ),
                    models.Index(
                        fields=['patient', 'priority_order'],
                        name='idx_ec_patient_priority',
                    ),
                    models.Index(
                        fields=['patient', 'status'], name='idx_ec_patient_status'
                    ),
                    models.Index(fields=['status'], name='idx_ec_status'),
                    models.Index(fields=['relationship'], name='idx_ec_relationship'),
                    models.Index(fields=['is_primary'], name='idx_ec_primary'),
                    models.Index(fields=['is_verified'], name='idx_ec_verified'),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('is_deleted', False)),
                        fields=('organization', 'emergency_contact_number'),
                        name='uniq_org_emergency_contact_number',
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(('is_deleted', False)),
                        fields=('patient', 'priority_order'),
                        name='uniq_patient_priority_order',
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(('is_deleted', False), ('is_primary', True)),
                        fields=('patient',),
                        name='uniq_primary_patient_emergency_contact',
                    ),
                ],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
    ]
