# Generated by Django 6.0.6 on 2026-09-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'laboratories',
            '0002_laboratoryworkflowstate_laboratoryworkflowtransition_and_more',
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='laboratoryworkflowtransition',
            new_name='ix_lab_wf_trans_entity',
            old_name='ix_lab_workflow_transition_entity',
        ),
        migrations.RenameIndex(
            model_name='laboratoryworkflowtransition',
            new_name='ix_lab_wf_trans_corr',
            old_name='ix_lab_workflow_transition_corr',
        ),
    ]
