# Generated by Django 6.0.6 on 2026-07-27 06:42

import apps.core.models.managers
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('medications', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'prescription_number',
                    models.CharField(
                        db_index=True,
                        help_text='Unique prescription number.',
                        max_length=30,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('completed', 'Completed'),
                            ('cancelled', 'Cancelled'),
                            ('on_hold', 'On Hold'),
                            ('expired', 'Expired'),
                        ],
                        db_index=True,
                        default='active',
                        help_text='Prescription status.',
                        max_length=20,
                    ),
                ),
                (
                    'dosage',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('1.00'),
                        help_text='Dose to administer.',
                        max_digits=6,
                    ),
                ),
                (
                    'dosage_unit',
                    models.CharField(
                        default='tablet', help_text='Dosage unit.', max_length=20
                    ),
                ),
                (
                    'frequency',
                    models.CharField(
                        choices=[
                            ('once_daily', 'OD - Once Daily'),
                            ('twice_daily', 'BD - Twice Daily'),
                            ('three_times_daily', 'TDS - Three Times Daily'),
                            ('four_times_daily', 'QID - Four Times Daily'),
                            ('every_other_day', 'Alternate Days'),
                            ('weekly', 'Weekly'),
                            ('monthly', 'Monthly'),
                            ('as_needed', 'SOS - As Needed'),
                            ('bedtime', 'HS - Bedtime'),
                        ],
                        db_index=True,
                        default='once_daily',
                        help_text='Medication frequency.',
                        max_length=20,
                    ),
                ),
                (
                    'quantity',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('1.00'),
                        help_text='Total quantity prescribed.',
                        max_digits=8,
                    ),
                ),
                (
                    'duration_days',
                    models.PositiveIntegerField(
                        default=1, help_text='Treatment duration in days.'
                    ),
                ),
                (
                    'refills',
                    models.PositiveSmallIntegerField(
                        default=0, help_text='Number of allowed refills.'
                    ),
                ),
                ('start_date', models.DateField(help_text='Prescription start date.')),
                ('end_date', models.DateField(help_text='Prescription end date.')),
                (
                    'instructions',
                    models.TextField(blank=True, help_text='Medication instructions.'),
                ),
                (
                    'is_prn',
                    models.BooleanField(
                        default=False,
                        help_text='Whether medication is taken as needed.',
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True, help_text='Additional clinical notes.'
                    ),
                ),
                (
                    'encounter',
                    models.ForeignKey(
                        help_text='Encounter associated with this prescription.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='prescriptions',
                        to='encounters.encounter',
                    ),
                ),
                (
                    'medication',
                    models.ForeignKey(
                        help_text='Medication prescribed.',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='prescriptions',
                        to='medications.medication',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns this prescription.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='prescriptions',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        help_text='Patient receiving this prescription.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='prescriptions',
                        to='patients.patient',
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        help_text='Provider issuing this prescription.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='prescriptions',
                        to='providers.provider',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'db_table': 'prescriptions',
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(
                        fields=['prescription_number'],
                        name='prescriptio_prescri_b8a9ac_idx',
                    ),
                    models.Index(
                        fields=['status'], name='prescriptio_status_1d7db8_idx'
                    ),
                    models.Index(
                        fields=['patient'], name='prescriptio_patient_408a4b_idx'
                    ),
                    models.Index(
                        fields=['provider'], name='prescriptio_provide_da135b_idx'
                    ),
                    models.Index(
                        fields=['encounter'], name='prescriptio_encount_4fba8d_idx'
                    ),
                    models.Index(
                        fields=['medication'], name='prescriptio_medicat_f8728d_idx'
                    ),
                    models.Index(
                        fields=['organization'], name='prescriptio_organiz_615969_idx'
                    ),
                    models.Index(
                        fields=['start_date'], name='prescriptio_start_d_36bd28_idx'
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('organization', 'prescription_number'),
                        name='unique_prescription_number_per_organization',
                    )
                ],
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
    ]
