# Generated by Django 6.0.6 on 2026-07-28 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='provider',
            field=models.ForeignKey(
                help_text='Provider issuing this prescription.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='prescriptions',
                to='providers.provider',
            ),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(
                fields=['prescription_number'], name='prescriptio_prescri_b8a9ac_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='prescriptio_status_1d7db8_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(
                fields=['patient'], name='prescriptio_patient_408a4b_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(
                fields=['provider'], name='prescriptio_provide_da135b_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(
                fields=['encounter'], name='prescriptio_encount_4fba8d_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(
                fields=['medication'], name='prescriptio_medicat_f8728d_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(
                fields=['organization'], name='prescriptio_organiz_615969_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(
                fields=['start_date'], name='prescriptio_start_d_36bd28_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(
                fields=('organization', 'prescription_number'),
                name='unique_prescription_number_per_organization',
            ),
        ),
    ]
