# Generated by Django 6.0.6 on 2026-07-31 11:49

import apps.core.models.managers
import apps.platform.notifications.managers.notification
import apps.platform.notifications.managers.notification_log
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'recipient',
                    models.CharField(
                        db_index=True,
                        help_text='Destination email address, phone number, or push device token.',
                        max_length=255,
                    ),
                ),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                (
                    'channel',
                    models.CharField(
                        choices=[
                            ('EMAIL', 'Email'),
                            ('SMS', 'SMS'),
                            ('WHATSAPP', 'WhatsApp'),
                            ('PUSH', 'Push Notification'),
                            ('IN_APP', 'In-App Notification'),
                        ],
                        db_index=True,
                        default='EMAIL',
                        max_length=20,
                    ),
                ),
                (
                    'provider',
                    models.CharField(
                        choices=[
                            ('SMTP', 'SMTP'),
                            ('AWS_SES', 'AWS SES'),
                            ('SENDGRID', 'SendGrid'),
                            ('TWILIO', 'Twilio'),
                            ('WHATSAPP', 'WhatsApp'),
                            ('FIREBASE', 'Firebase Cloud Messaging'),
                        ],
                        db_index=True,
                        default='SMTP',
                        max_length=30,
                    ),
                ),
                (
                    'priority',
                    models.IntegerField(
                        choices=[
                            (10, 'Low'),
                            (20, 'Normal'),
                            (30, 'High'),
                            (40, 'Critical'),
                        ],
                        db_index=True,
                        default=20,
                    ),
                ),
                (
                    'template',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='Notification template identifier.',
                        max_length=100,
                    ),
                ),
                ('subject', models.CharField(blank=True, max_length=255)),
                (
                    'context',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Template rendering context.',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('QUEUED', 'Queued'),
                            ('SENDING', 'Sending'),
                            ('SENT', 'Sent'),
                            ('DELIVERED', 'Delivered'),
                            ('FAILED', 'Failed'),
                            ('CANCELLED', 'Cancelled'),
                        ],
                        db_index=True,
                        default='PENDING',
                        max_length=20,
                    ),
                ),
                (
                    'provider_message_id',
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'metadata',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Additional provider metadata.',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        help_text='Associated platform user.',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notifications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ('-created_at',),
            },
            managers=[
                (
                    'objects',
                    apps.platform.notifications.managers.notification.NotificationManager(),
                ),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'attempt',
                    models.PositiveSmallIntegerField(
                        default=1, help_text='Delivery attempt number.'
                    ),
                ),
                (
                    'provider',
                    models.CharField(
                        choices=[
                            ('SMTP', 'SMTP'),
                            ('AWS_SES', 'AWS SES'),
                            ('SENDGRID', 'SendGrid'),
                            ('TWILIO', 'Twilio'),
                            ('WHATSAPP', 'WhatsApp'),
                            ('FIREBASE', 'Firebase Cloud Messaging'),
                        ],
                        db_index=True,
                        help_text='Notification provider used.',
                        max_length=30,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('QUEUED', 'Queued'),
                            ('SENDING', 'Sending'),
                            ('SENT', 'Sent'),
                            ('DELIVERED', 'Delivered'),
                            ('FAILED', 'Failed'),
                            ('CANCELLED', 'Cancelled'),
                        ],
                        db_index=True,
                        help_text='Delivery status returned by the provider.',
                        max_length=20,
                    ),
                ),
                (
                    'provider_message_id',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='Provider-specific message identifier.',
                        max_length=255,
                    ),
                ),
                (
                    'response',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Raw provider response payload.',
                    ),
                ),
                (
                    'metadata',
                    models.JSONField(
                        blank=True, default=dict, help_text='Additional audit metadata.'
                    ),
                ),
                (
                    'error_message',
                    models.TextField(
                        blank=True,
                        help_text='Failure reason if delivery was unsuccessful.',
                    ),
                ),
                (
                    'duration_ms',
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='Delivery duration in milliseconds.',
                        null=True,
                    ),
                ),
                (
                    'notification',
                    models.ForeignKey(
                        help_text='Notification associated with this log entry.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='logs',
                        to='notifications.notification',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'notification_logs',
                'ordering': ('-created_at',),
            },
            managers=[
                (
                    'objects',
                    apps.platform.notifications.managers.notification_log.NotificationLogManager(),
                ),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='notif_user_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient'], name='notif_recipient_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel'], name='notif_channel_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['provider'], name='notif_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='notif_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notif_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_at'], name='notif_scheduled_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['queued_at'], name='notif_queued_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sent_at'], name='notif_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notif_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=['channel', 'status'], name='notif_ch_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=['provider', 'status'], name='notif_prv_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status'], name='notif_usr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=['status', 'scheduled_at'], name='notif_stat_sched_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=['status', 'priority'], name='notif_stat_prio_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=['channel', 'priority'], name='notif_ch_prio_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification'], name='notlog_notif_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['provider'], name='notlog_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='notlog_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['attempt'], name='notlog_attempt_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(
                fields=['provider_message_id'], name='notlog_provmsg_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created_at'], name='notlog_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(
                fields=['notification', 'status'], name='notlog_notif_stat_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(
                fields=['provider', 'status'], name='notlog_prov_stat_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(
                fields=['notification', 'created_at'], name='notlog_notif_cre_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(
                fields=('notification', 'attempt'), name='unique_notification_attempt'
            ),
        ),
    ]
