# Generated by Django 6.0.6 on 2026-09-09 03:06

import apps.core.models.managers
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        help_text='ISO 3166-1 alpha-2 country code.',
                        max_length=2,
                        unique=True,
                        verbose_name='Country Code',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        db_index=True,
                        help_text='Canonical country name.',
                        max_length=100,
                        unique=True,
                        verbose_name='Country Name',
                    ),
                ),
                (
                    'iso3',
                    models.CharField(
                        help_text='ISO 3166-1 alpha-3 country code.',
                        max_length=3,
                        unique=True,
                        verbose_name='ISO 3 Code',
                    ),
                ),
                (
                    'phone_code',
                    models.CharField(
                        blank=True,
                        help_text='International telephone dialing code.',
                        max_length=10,
                        verbose_name='Phone Code',
                    ),
                ),
                (
                    'sort_order',
                    models.PositiveIntegerField(
                        default=0,
                        help_text='Display ordering for country selectors.',
                        verbose_name='Sort Order',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'geography_countries',
                'ordering': ('sort_order', 'name'),
                'indexes': [
                    models.Index(
                        fields=['is_active', 'name'], name='idx_geo_country_active_name'
                    )
                ],
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeRegion',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        help_text='Stable administrative-region code.',
                        max_length=20,
                        verbose_name='Region Code',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Canonical administrative-region name.',
                        max_length=150,
                        verbose_name='Region Name',
                    ),
                ),
                (
                    'region_type',
                    models.CharField(
                        choices=[
                            ('state', 'State'),
                            ('province', 'Province'),
                            ('territory', 'Territory'),
                            ('region', 'Region'),
                            ('district', 'District'),
                        ],
                        default='state',
                        help_text='Administrative classification of the region.',
                        max_length=30,
                        verbose_name='Region Type',
                    ),
                ),
                (
                    'sort_order',
                    models.PositiveIntegerField(
                        default=0,
                        help_text='Display ordering within the country.',
                        verbose_name='Sort Order',
                    ),
                ),
                (
                    'country',
                    models.ForeignKey(
                        help_text='Country to which this administrative region belongs.',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='regions',
                        to='geography.country',
                        verbose_name='Country',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Administrative Region',
                'verbose_name_plural': 'Administrative Regions',
                'db_table': 'geography_regions',
                'ordering': ('country', 'sort_order', 'name'),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'source',
                    models.CharField(
                        default='countries-states-cities',
                        help_text='Identifier of the upstream geography data source.',
                        max_length=50,
                        verbose_name='Source',
                    ),
                ),
                (
                    'source_id',
                    models.CharField(
                        help_text='Stable identifier assigned by the upstream data source.',
                        max_length=100,
                        verbose_name='Source ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        db_index=True,
                        help_text='Canonical city name.',
                        max_length=150,
                        verbose_name='City Name',
                    ),
                ),
                (
                    'latitude',
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text='Geographic latitude in decimal degrees.',
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('-90')),
                            django.core.validators.MaxValueValidator(Decimal('90')),
                        ],
                        verbose_name='Latitude',
                    ),
                ),
                (
                    'longitude',
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text='Geographic longitude in decimal degrees.',
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('-180')),
                            django.core.validators.MaxValueValidator(Decimal('180')),
                        ],
                        verbose_name='Longitude',
                    ),
                ),
                (
                    'timezone',
                    models.CharField(
                        blank=True,
                        help_text='IANA timezone identifier for the city.',
                        max_length=100,
                        verbose_name='Timezone',
                    ),
                ),
                (
                    'sort_order',
                    models.PositiveIntegerField(
                        default=0,
                        help_text='Display ordering within the administrative region.',
                        verbose_name='Sort Order',
                    ),
                ),
                (
                    'region',
                    models.ForeignKey(
                        blank=True,
                        help_text='First-level administrative region containing the city.',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='cities',
                        to='geography.administrativeregion',
                        verbose_name='Administrative Region',
                    ),
                ),
                (
                    'country',
                    models.ForeignKey(
                        help_text='Country to which this city belongs.',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='cities',
                        to='geography.country',
                        verbose_name='Country',
                    ),
                ),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'geography_cities',
                'ordering': ('country', 'region', 'sort_order', 'name'),
                'indexes': [
                    models.Index(
                        fields=['country', 'is_active'],
                        name='idx_geo_city_country_active',
                    ),
                    models.Index(
                        fields=['region', 'is_active'],
                        name='idx_geo_city_region_active',
                    ),
                    models.Index(
                        fields=['country', 'name'], name='idx_geo_city_country_name'
                    ),
                    models.Index(
                        fields=['region', 'name'], name='idx_geo_city_region_name'
                    ),
                    models.Index(
                        fields=['source', 'source_id'], name='idx_geo_city_source_id'
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('source', 'source_id'),
                        name='uq_geo_city_source_source_id',
                    )
                ],
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='administrativeregion',
            index=models.Index(
                fields=['country', 'is_active'], name='idx_geo_region_country_active'
            ),
        ),
        migrations.AddIndex(
            model_name='administrativeregion',
            index=models.Index(
                fields=['country', 'region_type'], name='idx_geo_region_country_type'
            ),
        ),
        migrations.AddConstraint(
            model_name='administrativeregion',
            constraint=models.UniqueConstraint(
                fields=('country', 'code'), name='uq_geo_region_country_code'
            ),
        ),
    ]
