# Generated by Django 6.0.6 on 2026-07-03 16:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'mrn',
                    models.CharField(
                        help_text='Medical Record Number (MRN).', max_length=30
                    ),
                ),
                (
                    'first_name',
                    models.CharField(help_text='Patient first name.', max_length=100),
                ),
                (
                    'middle_name',
                    models.CharField(
                        blank=True, help_text='Patient middle name.', max_length=100
                    ),
                ),
                (
                    'last_name',
                    models.CharField(help_text='Patient last name.', max_length=100),
                ),
                (
                    'preferred_name',
                    models.CharField(
                        blank=True, help_text='Preferred display name.', max_length=100
                    ),
                ),
                ('date_of_birth', models.DateField(help_text='Patient date of birth.')),
                (
                    'gender',
                    models.CharField(
                        choices=[
                            ('male', 'Male'),
                            ('female', 'Female'),
                            ('other', 'Other'),
                            ('unknown', 'Unknown'),
                        ],
                        help_text='Patient gender.',
                        max_length=20,
                    ),
                ),
                (
                    'marital_status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('single', 'Single'),
                            ('married', 'Married'),
                            ('divorced', 'Divorced'),
                            ('widowed', 'Widowed'),
                            ('separated', 'Separated'),
                            ('unknown', 'Unknown'),
                        ],
                        help_text='Patient marital status.',
                        max_length=20,
                    ),
                ),
                (
                    'blood_group',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('A+', 'A+'),
                            ('A-', 'A-'),
                            ('B+', 'B+'),
                            ('B-', 'B-'),
                            ('AB+', 'AB+'),
                            ('AB-', 'AB-'),
                            ('O+', 'O+'),
                            ('O-', 'O-'),
                            ('unknown', 'Unknown'),
                        ],
                        help_text='Patient blood group.',
                        max_length=20,
                    ),
                ),
                (
                    'phone',
                    models.CharField(
                        blank=True,
                        help_text='Primary contact phone number.',
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Enter a valid international phone number. Example: +919876543210.',
                                regex='^\\+?[1-9]\\d{9,14}$',
                            )
                        ],
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        blank=True, help_text='Primary contact email.', max_length=254
                    ),
                ),
                ('address', models.TextField(blank=True, help_text='Patient address.')),
                (
                    'city',
                    models.CharField(blank=True, help_text='City.', max_length=100),
                ),
                (
                    'state',
                    models.CharField(blank=True, help_text='State.', max_length=100),
                ),
                (
                    'country',
                    models.CharField(
                        default='India', help_text='Country.', max_length=100
                    ),
                ),
                (
                    'postal_code',
                    models.CharField(
                        blank=True, help_text='Postal code.', max_length=20
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('inactive', 'Inactive'),
                            ('deceased', 'Deceased'),
                            ('archived', 'Archived'),
                        ],
                        db_index=True,
                        default='active',
                        help_text='Patient lifecycle status.',
                        max_length=20,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns the patient record.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='patients',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
                'ordering': ('first_name', 'last_name'),
                'indexes': [
                    models.Index(
                        fields=['last_name', 'first_name'],
                        name='patients_last_na_ce6411_idx',
                    ),
                    models.Index(fields=['status'], name='patients_status_7c14f6_idx'),
                    models.Index(
                        fields=['is_active'], name='patients_is_acti_4a96f9_idx'
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('organization', 'mrn'),
                        name='unique_patient_mrn_per_organization',
                    )
                ],
            },
        ),
    ]
