# Generated by Django 6.0.6 on 2026-09-09 03:06

import apps.core.models.managers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('patient_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientIdentifier',
            fields=[
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'identifier_type',
                    models.CharField(
                        choices=[
                            ('MRN', 'Medical Record Number'),
                            ('ABHA', 'ABHA Number'),
                            ('AADHAAR', 'Aadhaar Number'),
                            ('PASSPORT', 'Passport'),
                            ('DRIVING_LICENSE', 'Driving License'),
                            ('NATIONAL_ID', 'National ID'),
                            ('INSURANCE_MEMBER_ID', 'Insurance Member ID'),
                            ('EMPLOYEE_ID', 'Employee ID'),
                            ('EXTERNAL_EMR_ID', 'External EMR ID'),
                            ('LEGACY_HOSPITAL_ID', 'Legacy Hospital ID'),
                            ('OTHER', 'Other'),
                        ],
                        max_length=50,
                    ),
                ),
                ('identifier_value', models.CharField(max_length=150)),
                ('display_value', models.CharField(blank=True, max_length=150)),
                (
                    'priority',
                    models.CharField(
                        choices=[
                            ('PRIMARY', 'Primary'),
                            ('SECONDARY', 'Secondary'),
                            ('ARCHIVED', 'Archived'),
                        ],
                        default='SECONDARY',
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('ACTIVE', 'Active'),
                            ('INACTIVE', 'Inactive'),
                            ('EXPIRED', 'Expired'),
                            ('REVOKED', 'Revoked'),
                        ],
                        default='ACTIVE',
                        max_length=20,
                    ),
                ),
                (
                    'verification_status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('VERIFIED', 'Verified'),
                            ('REJECTED', 'Rejected'),
                            ('EXPIRED', 'Expired'),
                        ],
                        default='PENDING',
                        max_length=20,
                    ),
                ),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('PATIENT', 'Patient'),
                            ('REGISTRATION', 'Registration'),
                            ('STAFF', 'Staff'),
                            ('GOVERNMENT', 'Government'),
                            ('EXTERNAL_SYSTEM', 'External System'),
                            ('IMPORT', 'Import'),
                            ('API', 'API'),
                        ],
                        default='REGISTRATION',
                        max_length=30,
                    ),
                ),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('issuing_country', models.CharField(blank=True, max_length=100)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('system_uri', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text='User that created this record.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_%(class)ss',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created By',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='patient_identifiers',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='identifiers',
                        to='patient_core.patient',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text='User that most recently updated this record.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='updated_%(class)ss',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated By',
                    ),
                ),
                (
                    'verified_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='verified_patient_identifiers',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Patient Identifier',
                'verbose_name_plural': 'Patient Identifiers',
                'ordering': (
                    'patient',
                    'identifier_type',
                    '-is_primary',
                    'identifier_value',
                ),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='IdentifierVerification',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('VERIFIED', 'Verified'),
                            ('REJECTED', 'Rejected'),
                            ('EXPIRED', 'Expired'),
                        ],
                        default='PENDING',
                        max_length=20,
                    ),
                ),
                (
                    'verification_source',
                    models.CharField(
                        choices=[
                            ('PATIENT', 'Patient'),
                            ('REGISTRATION', 'Registration'),
                            ('STAFF', 'Staff'),
                            ('GOVERNMENT', 'Government'),
                            ('EXTERNAL_SYSTEM', 'External System'),
                            ('IMPORT', 'Import'),
                            ('API', 'API'),
                        ],
                        default='STAFF',
                        max_length=30,
                    ),
                ),
                ('reference_number', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text='User that created this record.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_%(class)ss',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created By',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text='User that most recently updated this record.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='updated_%(class)ss',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated By',
                    ),
                ),
                (
                    'verified_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='identifier_verifications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'identifier',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='verification_history',
                        to='patient_management.patientidentifier',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Identifier Verification',
                'verbose_name_plural': 'Identifier Verifications',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='patientidentifier',
            index=models.Index(
                fields=['organization', 'patient'], name='patient_id_org_patient_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='patientidentifier',
            index=models.Index(
                fields=['organization', 'identifier_type'],
                name='patient_id_org_type_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='patientidentifier',
            index=models.Index(
                fields=['organization', 'identifier_value'],
                name='patient_id_org_value_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='patientidentifier',
            index=models.Index(fields=['status'], name='patient_id_status_idx'),
        ),
        migrations.AddIndex(
            model_name='patientidentifier',
            index=models.Index(
                fields=['verification_status'], name='patient_id_verify_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='patientidentifier',
            index=models.Index(fields=['is_primary'], name='patient_id_primary_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientidentifier',
            constraint=models.UniqueConstraint(
                fields=('organization', 'identifier_type', 'identifier_value'),
                name='uniq_patient_identifier',
            ),
        ),
        migrations.AddConstraint(
            model_name='patientidentifier',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_primary', True)),
                fields=('patient', 'identifier_type'),
                name='uniq_primary_identifier_type',
            ),
        ),
        migrations.AddIndex(
            model_name='identifierverification',
            index=models.Index(
                fields=['identifier'], name='identifier_verification_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='identifierverification',
            index=models.Index(fields=['status'], name='identifier_verify_status_idx'),
        ),
    ]
