# Generated by Django 6.0.6 on 2026-09-21 03:09

import apps.core.models.managers
import apps.patient_management.emergency.validators
import apps.patient_management.preferences.managers
import apps.patient_management.registration.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('patient_core', '0001_initial'),
        ('patient_management', '0004_alter_address_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPreference',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('language', models.CharField(default='en', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('time_format', models.CharField(default='24H', max_length=10)),
                ('accessibility', models.JSONField(blank=True, default=dict)),
                (
                    'notification_preferences',
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='patient_preferences',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='preferences',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'db_table': 'patient_management_patient_preference',
            },
            managers=[
                (
                    'objects',
                    apps.patient_management.preferences.managers.PatientPreferenceManager(),
                ),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientCommunicationPreference',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'channel',
                    models.CharField(
                        choices=[
                            ('EMAIL', 'Email'),
                            ('SMS', 'Sms'),
                            ('PHONE', 'Phone'),
                            ('PUSH', 'Push'),
                            ('PORTAL', 'Portal'),
                        ],
                        max_length=20,
                    ),
                ),
                ('enabled', models.BooleanField(default=True)),
                ('appointment_reminders', models.BooleanField(default=True)),
                ('clinical_updates', models.BooleanField(default=True)),
                ('administrative_updates', models.BooleanField(default=True)),
                ('marketing_messages', models.BooleanField(default=False)),
                (
                    'preference',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='communication_preferences',
                        to='patient_management.patientpreference',
                    ),
                ),
            ],
            options={
                'db_table': 'patient_management_communication_preference',
            },
            managers=[
                (
                    'objects',
                    apps.patient_management.preferences.managers.PatientCommunicationPreferenceManager(),
                ),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientRegistration',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'registration_number',
                    models.CharField(
                        max_length=50,
                        validators=[
                            apps.patient_management.registration.validators.validate_registration_number
                        ],
                        verbose_name='Registration Number',
                    ),
                ),
                (
                    'registration_type',
                    models.CharField(
                        choices=[
                            ('NEW_PATIENT', 'New Patient'),
                            ('EXISTING_PATIENT', 'Existing Patient'),
                            ('FOLLOW_UP', 'Follow-up'),
                            ('WALK_IN', 'Walk-in'),
                            ('ONLINE', 'Online'),
                            ('REFERRAL', 'Referral'),
                            ('EMERGENCY', 'Emergency'),
                            ('CORPORATE', 'Corporate'),
                            ('INSURANCE', 'Insurance'),
                        ],
                        default='NEW_PATIENT',
                        max_length=30,
                        verbose_name='Registration Type',
                    ),
                ),
                (
                    'registration_status',
                    models.CharField(
                        choices=[
                            ('DRAFT', 'Draft'),
                            ('PENDING_VERIFICATION', 'Pending Verification'),
                            ('VERIFIED', 'Verified'),
                            ('REGISTERED', 'Registered'),
                            ('CHECKED_IN', 'Checked In'),
                            ('COMPLETED', 'Completed'),
                            ('CANCELLED', 'Cancelled'),
                            ('REJECTED', 'Rejected'),
                            ('NO_SHOW', 'No Show'),
                        ],
                        db_index=True,
                        default='DRAFT',
                        max_length=40,
                        verbose_name='Registration Status',
                    ),
                ),
                (
                    'registration_source',
                    models.CharField(
                        choices=[
                            ('FRONT_DESK', 'Front Desk'),
                            ('PATIENT_PORTAL', 'Patient Portal'),
                            ('MOBILE_APP', 'Mobile App'),
                            ('KIOSK', 'Kiosk'),
                            ('API', 'API'),
                            ('IMPORT', 'Import'),
                            ('CALL_CENTER', 'Call Center'),
                        ],
                        default='FRONT_DESK',
                        max_length=30,
                        verbose_name='Registration Source',
                    ),
                ),
                (
                    'visit_type',
                    models.CharField(
                        choices=[
                            ('OPD', 'Outpatient'),
                            ('IPD', 'Inpatient'),
                            ('DAY_CARE', 'Day Care'),
                            ('EMERGENCY', 'Emergency'),
                            ('TELEMEDICINE', 'Telemedicine'),
                            ('HOME_CARE', 'Home Care'),
                        ],
                        default='OPD',
                        max_length=30,
                        verbose_name='Visit Type',
                    ),
                ),
                (
                    'priority',
                    models.CharField(
                        choices=[
                            ('LOW', 'Low'),
                            ('NORMAL', 'Normal'),
                            ('HIGH', 'High'),
                            ('URGENT', 'Urgent'),
                            ('CRITICAL', 'Critical'),
                        ],
                        default='NORMAL',
                        max_length=20,
                        verbose_name='Priority',
                    ),
                ),
                (
                    'verification_method',
                    models.CharField(
                        choices=[
                            ('NONE', 'None'),
                            ('MOBILE_OTP', 'Mobile OTP'),
                            ('EMAIL_OTP', 'Email OTP'),
                            ('GOVERNMENT_ID', 'Government ID'),
                            ('INSURANCE', 'Insurance'),
                            ('MANUAL', 'Manual'),
                        ],
                        default='NONE',
                        max_length=30,
                        verbose_name='Verification Method',
                    ),
                ),
                (
                    'verified',
                    models.BooleanField(default=False, verbose_name='Verified'),
                ),
                (
                    'verified_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Verified At'
                    ),
                ),
                (
                    'registration_datetime',
                    models.DateTimeField(verbose_name='Registration Date & Time'),
                ),
                (
                    'checked_in_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Checked In At'
                    ),
                ),
                (
                    'completed_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Completed At'
                    ),
                ),
                (
                    'cancellation_reason',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('PATIENT_REQUEST', 'Patient Request'),
                            ('DUPLICATE_REGISTRATION', 'Duplicate Registration'),
                            ('INVALID_INFORMATION', 'Invalid Information'),
                            ('INSURANCE_DECLINED', 'Insurance Declined'),
                            ('PAYMENT_PENDING', 'Payment Pending'),
                            ('ADMINISTRATIVE', 'Administrative'),
                            ('OTHER', 'Other'),
                        ],
                        max_length=50,
                        verbose_name='Cancellation Reason',
                    ),
                ),
                (
                    'cancellation_notes',
                    models.TextField(
                        blank=True,
                        validators=[
                            apps.patient_management.registration.validators.validate_notes
                        ],
                        verbose_name='Cancellation Notes',
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True,
                        validators=[
                            apps.patient_management.registration.validators.validate_notes
                        ],
                        verbose_name='Notes',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='patient_registrations',
                        to='organizations.organization',
                        verbose_name='Organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='registrations',
                        to='patient_core.patient',
                        verbose_name='Patient',
                    ),
                ),
                (
                    'verified_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='verified_patient_registrations',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Verified By',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Patient Registration',
                'verbose_name_plural': 'Patient Registrations',
                'db_table': 'patient_registration',
                'ordering': ('-registration_datetime',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'contact_type',
                    models.CharField(
                        choices=[
                            ('MOBILE', 'Mobile'),
                            ('HOME', 'Home'),
                            ('WORK', 'Work'),
                            ('EMAIL', 'Email'),
                            ('EMERGENCY', 'Emergency'),
                            ('FAX', 'Fax'),
                            ('OTHER', 'Other'),
                        ],
                        max_length=20,
                        verbose_name='Contact Type',
                    ),
                ),
                (
                    'purpose',
                    models.CharField(
                        choices=[
                            ('PRIMARY', 'Primary'),
                            ('BILLING', 'Billing'),
                            ('APPOINTMENT', 'Appointment'),
                            ('EMERGENCY', 'Emergency'),
                            ('NOTIFICATION', 'Notification'),
                            ('OTHER', 'Other'),
                        ],
                        default='PRIMARY',
                        max_length=20,
                        verbose_name='Purpose',
                    ),
                ),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('ACTIVE', 'Active'),
                            ('INACTIVE', 'Inactive'),
                            ('VERIFIED', 'Verified'),
                            ('UNVERIFIED', 'Unverified'),
                        ],
                        default='UNVERIFIED',
                        max_length=20,
                        verbose_name='Status',
                    ),
                ),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('PATIENT', 'Patient'),
                            ('STAFF', 'Staff'),
                            ('IMPORT', 'Import'),
                            ('API', 'API'),
                            ('SYSTEM', 'System'),
                        ],
                        default='PATIENT',
                        max_length=20,
                        verbose_name='Source',
                    ),
                ),
                (
                    'is_primary',
                    models.BooleanField(default=False, verbose_name='Primary'),
                ),
                (
                    'is_preferred',
                    models.BooleanField(default=False, verbose_name='Preferred'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text='User that created this record.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_%(class)ss',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created By',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='patient_contacts',
                        to='organizations.organization',
                        verbose_name='Organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='contacts',
                        to='patient_core.patient',
                        verbose_name='Patient',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text='User that most recently updated this record.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='updated_%(class)ss',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated By',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Patient Contact',
                'verbose_name_plural': 'Patient Contacts',
                'ordering': (
                    'patient',
                    '-is_primary',
                    '-is_preferred',
                    'contact_type',
                    'created_at',
                ),
                'indexes': [
                    models.Index(
                        fields=['organization', 'patient'],
                        name='idx_contact_org_patient',
                    ),
                    models.Index(
                        fields=['patient', 'contact_type'],
                        name='idx_contact_patient_type',
                    ),
                    models.Index(
                        fields=['organization', 'status'], name='idx_contact_org_status'
                    ),
                    models.Index(
                        fields=['organization', 'contact_type'],
                        name='idx_contact_org_type',
                    ),
                    models.Index(
                        fields=['organization', 'is_deleted'],
                        name='idx_contact_org_deleted',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('is_deleted', False)),
                        fields=('organization', 'contact_type', 'value'),
                        name='uniq_patient_contact',
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(('is_deleted', False), ('is_primary', True)),
                        fields=('patient', 'contact_type'),
                        name='uniq_primary_patient_contact',
                    ),
                ],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255,
                        validators=[
                            apps.patient_management.emergency.validators.validate_contact_name
                        ],
                    ),
                ),
                (
                    'relationship',
                    models.CharField(
                        choices=[
                            ('family', 'Family'),
                            ('spouse', 'Spouse'),
                            ('parent', 'Parent'),
                            ('child', 'Child'),
                            ('sibling', 'Sibling'),
                            ('friend', 'Friend'),
                            ('caregiver', 'Caregiver'),
                            ('other', 'Other'),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'phone',
                    models.CharField(
                        max_length=64,
                        validators=[
                            apps.patient_management.emergency.validators.validate_contact_phone
                        ],
                    ),
                ),
                ('alternate_phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                (
                    'priority',
                    models.CharField(
                        choices=[('primary', 'Primary'), ('secondary', 'Secondary')],
                        default='secondary',
                        max_length=16,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('inactive', 'Inactive'),
                            ('deleted', 'Deleted'),
                        ],
                        default='active',
                        max_length=16,
                    ),
                ),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='patient_emergency_contacts',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='emergency_contacts',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'db_table': 'patient_emergency_contacts',
                'ordering': ('-priority', 'name'),
                'indexes': [
                    models.Index(
                        fields=['organization', 'patient'],
                        name='patient_eme_organiz_d00181_idx',
                    ),
                    models.Index(
                        fields=['organization', 'status'],
                        name='patient_eme_organiz_579dc8_idx',
                    ),
                    models.Index(
                        fields=['patient', 'is_deleted'],
                        name='patient_eme_patient_447999_idx',
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name='patientpreference',
            index=models.Index(
                fields=['organization', 'patient'], name='patpref_org_patient_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='patientpreference',
            index=models.Index(
                fields=['organization', 'language'], name='patpref_org_lang_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='patientcommunicationpreference',
            index=models.Index(
                fields=['preference', 'channel'], name='patcomm_pref_channel_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='patientcommunicationpreference',
            constraint=models.UniqueConstraint(
                fields=('preference', 'channel'), name='patcomm_pref_channel_uniq'
            ),
        ),
        migrations.AddIndex(
            model_name='patientregistration',
            index=models.Index(
                fields=['organization', 'registration_status'],
                name='idx_registration_status',
            ),
        ),
        migrations.AddIndex(
            model_name='patientregistration',
            index=models.Index(
                fields=['organization', 'patient'], name='idx_registration_patient'
            ),
        ),
        migrations.AddIndex(
            model_name='patientregistration',
            index=models.Index(
                fields=['registration_datetime'], name='idx_registration_datetime'
            ),
        ),
        migrations.AddConstraint(
            model_name='patientregistration',
            constraint=models.UniqueConstraint(
                fields=('organization', 'registration_number'),
                name='uq_registration_number_per_organization',
            ),
        ),
    ]
