# Generated by Django 6.0.6 on 2026-07-28 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='patient',
            field=models.ForeignKey(
                help_text='Patient associated with the prediction.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='predictions',
                to='patients.patient',
            ),
        ),
        migrations.AddField(
            model_name='prediction',
            name='reviewed_by',
            field=models.ForeignKey(
                blank=True,
                help_text='User who reviewed the prediction.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reviewed_predictions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                help_text='Owning organization. Null for global templates.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='prompt_templates',
                to='organizations.organization',
            ),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization that owns the recommendation.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recommendations',
                to='organizations.organization',
            ),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='patient',
            field=models.ForeignKey(
                help_text='Patient associated with the recommendation.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recommendations',
                to='patients.patient',
            ),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(
                fields=['organization', 'status'], name='ai_model_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(
                fields=['organization', 'model_type'], name='ai_model_org_type_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='aimodel',
            constraint=models.UniqueConstraint(
                fields=('organization', 'name', 'version'),
                name='unique_ai_model_per_org',
            ),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(
                fields=['organization', 'document'], name='ai_chunk_org_doc_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(
                fields=['organization', 'prediction_type'],
                name='prediction_org_type_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(
                fields=['organization', 'predicted_at'],
                name='prediction_org_predicted_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(
                fields=['organization', 'is_reviewed'],
                name='prediction_org_reviewed_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(
                fields=['patient', 'predicted_at'], name='pred_patient_predicted_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(
                fields=['ai_model', 'predicted_at'],
                name='prediction_model_predicted_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(
                fields=('organization', 'name', 'version'),
                name='uniq_prompt_org_name_version',
            ),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(
                fields=['organization', 'status'], name='recommendation_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(
                fields=['organization', 'recommendation_type'],
                name='recommendation_org_type_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(
                fields=['patient', 'status'], name='rec_patient_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(
                fields=['patient', 'priority'], name='rec_patient_priority_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(
                fields=['organization', 'priority'], name='rec_org_priority_idx'
            ),
        ),
    ]
