# Generated by Django 6.0.6 on 2026-09-09 03:06

import apps.core.models.managers
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('patient_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'invoice_number',
                    models.CharField(
                        help_text='Unique invoice number.', max_length=50, unique=True
                    ),
                ),
                (
                    'invoice_date',
                    models.DateField(help_text='Date the invoice was issued.'),
                ),
                (
                    'due_date',
                    models.DateField(help_text='Payment due date for the invoice.'),
                ),
                (
                    'total_amount',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Total invoice amount.',
                        max_digits=12,
                    ),
                ),
                (
                    'paid_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        help_text='Total amount paid against the invoice.',
                        max_digits=12,
                    ),
                ),
                (
                    'balance_amount',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Outstanding balance on the invoice.',
                        max_digits=12,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('DRAFT', 'Draft'),
                            ('PARTIALLY_PAID', 'Partially Paid'),
                            ('PAID', 'Paid'),
                            ('OVERDUE', 'Overdue'),
                            ('VOID', 'Void'),
                        ],
                        db_index=True,
                        default='DRAFT',
                        help_text='Current status of the invoice.',
                        max_length=20,
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True, help_text='Additional notes for the invoice.'
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns the invoice.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invoices',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        help_text='Patient associated with the invoice.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invoices',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ('-invoice_date', '-created_at'),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'insurance_provider',
                    models.CharField(
                        help_text='Name of the insurance provider.', max_length=255
                    ),
                ),
                (
                    'policy_number',
                    models.CharField(
                        help_text='Patient insurance policy number.', max_length=100
                    ),
                ),
                (
                    'claim_number',
                    models.CharField(
                        help_text='Unique claim reference number.',
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    'claim_amount',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Amount claimed from insurance.',
                        max_digits=12,
                    ),
                ),
                (
                    'approved_amount',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Amount approved by the insurer.',
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('SUBMITTED', 'Submitted'),
                            ('APPROVED', 'Approved'),
                            ('PARTIALLY_APPROVED', 'Partially Approved'),
                            ('REJECTED', 'Rejected'),
                            ('APPEALED', 'Appealed'),
                            ('SETTLED', 'Settled'),
                        ],
                        db_index=True,
                        default='SUBMITTED',
                        help_text='Current status of the claim.',
                        max_length=20,
                    ),
                ),
                (
                    'submitted_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Timestamp when the claim was submitted.',
                    ),
                ),
                (
                    'settled_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Timestamp when the claim was settled.',
                        null=True,
                    ),
                ),
                (
                    'rejection_reason',
                    models.TextField(
                        blank=True,
                        help_text='Reason for claim rejection, if applicable.',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that submitted the claim.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='insurance_claims',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        help_text='Patient associated with the claim.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='insurance_claims',
                        to='patient_core.patient',
                    ),
                ),
                (
                    'invoice',
                    models.ForeignKey(
                        help_text='Invoice the claim is for.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='insurance_claims',
                        to='billing.invoice',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Insurance Claim',
                'verbose_name_plural': 'Insurance Claims',
                'db_table': 'billing_insurance_claims',
                'ordering': ('-submitted_at', '-created_at'),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        help_text='Description of the service or item.', max_length=255
                    ),
                ),
                (
                    'quantity',
                    models.PositiveIntegerField(
                        default=1, help_text='Quantity of the item.'
                    ),
                ),
                (
                    'unit_price',
                    models.DecimalField(
                        decimal_places=2, help_text='Price per unit.', max_digits=10
                    ),
                ),
                (
                    'total_price',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Total price for this line item.',
                        max_digits=10,
                    ),
                ),
                (
                    'service_code',
                    models.CharField(
                        blank=True,
                        help_text='Optional service or CPT code.',
                        max_length=50,
                    ),
                ),
                (
                    'invoice',
                    models.ForeignKey(
                        help_text='Invoice this item belongs to.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='billing.invoice',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'db_table': 'invoice_items',
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientBillingAccount',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('account_number', models.CharField(db_index=True, max_length=50)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('ACTIVE', 'Active'),
                            ('SUSPENDED', 'Suspended'),
                            ('CLOSED', 'Closed'),
                        ],
                        db_index=True,
                        default='ACTIVE',
                        max_length=20,
                    ),
                ),
                (
                    'currency',
                    models.CharField(
                        choices=[
                            ('INR', 'INR'),
                            ('USD', 'USD'),
                            ('EUR', 'EUR'),
                            ('GBP', 'GBP'),
                        ],
                        default='INR',
                        max_length=3,
                    ),
                ),
                (
                    'opening_balance',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0.00'))
                        ],
                    ),
                ),
                (
                    'credit_limit',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0.00'))
                        ],
                    ),
                ),
                (
                    'current_balance',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=14
                    ),
                ),
                ('notes', models.TextField(blank=True, default='')),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='patient_billing_accounts',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='billing_account',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'db_table': 'billing_patient_accounts',
                'ordering': ('account_number',),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientBillingStatement',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('statement_number', models.CharField(db_index=True, max_length=60)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                (
                    'opening_balance',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=14
                    ),
                ),
                (
                    'charges',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0.00'))
                        ],
                    ),
                ),
                (
                    'payments',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0.00'))
                        ],
                    ),
                ),
                (
                    'adjustments',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=14
                    ),
                ),
                (
                    'closing_balance',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=14
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('DRAFT', 'Draft'),
                            ('ISSUED', 'Issued'),
                            ('PAID', 'Paid'),
                            ('VOID', 'Void'),
                        ],
                        db_index=True,
                        default='DRAFT',
                        max_length=20,
                    ),
                ),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='statements',
                        to='billing.patientbillingaccount',
                    ),
                ),
            ],
            options={
                'db_table': 'billing_patient_statements',
                'ordering': ('-period_end', '-created_at'),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientGuarantor',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='patient_guarantors',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='billing_guarantors',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'db_table': 'billing_patient_guarantors',
                'ordering': ('-is_primary', 'name'),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientFinancialResponsibility',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'party_type',
                    models.CharField(
                        choices=[
                            ('SELF', 'Patient'),
                            ('GUARANTOR', 'Guarantor'),
                            ('INSURANCE', 'Insurance'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'percentage',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('100.00'),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0.00')),
                            django.core.validators.MaxValueValidator(Decimal('100.00')),
                        ],
                    ),
                ),
                ('priority', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='responsibilities',
                        to='billing.patientbillingaccount',
                    ),
                ),
                (
                    'guarantor',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='responsibilities',
                        to='billing.patientguarantor',
                    ),
                ),
            ],
            options={
                'db_table': 'billing_patient_responsibilities',
                'ordering': ('priority', 'effective_from'),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'payment_method',
                    models.CharField(
                        choices=[
                            ('CASH', 'Cash'),
                            ('CARD', 'Card'),
                            ('UPI', 'UPI'),
                            ('BANK_TRANSFER', 'Bank Transfer'),
                            ('CHEQUE', 'Cheque'),
                            ('INSURANCE', 'Insurance'),
                            ('OTHER', 'Other'),
                        ],
                        help_text='Method used for the payment.',
                        max_length=20,
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2, help_text='Payment amount.', max_digits=10
                    ),
                ),
                (
                    'payment_date',
                    models.DateField(help_text='Date the payment was received.'),
                ),
                (
                    'reference_number',
                    models.CharField(
                        blank=True,
                        help_text='Optional reference or transaction number.',
                        max_length=100,
                    ),
                ),
                (
                    'notes',
                    models.TextField(blank=True, help_text='Additional payment notes.'),
                ),
                (
                    'invoice',
                    models.ForeignKey(
                        help_text='Invoice the payment is applied to.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payments',
                        to='billing.invoice',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that received the payment.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payments',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        help_text='Patient who made the payment.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payments',
                        to='patient_core.patient',
                    ),
                ),
                (
                    'received_by',
                    models.ForeignKey(
                        blank=True,
                        help_text='User who recorded the payment.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='received_payments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ('-payment_date', '-created_at'),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['organization', 'status'], name='invoice_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['organization', 'invoice_date'], name='invoice_org_date_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['patient', 'status'], name='invoice_patient_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(
                fields=['organization', 'status'], name='billing_claim_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(
                fields=['patient', 'status'], name='billing_claim_pat_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(
                fields=['invoice', 'status'], name='claim_invoice_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(
                fields=['invoice', 'service_code'], name='invoice_item_code_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='patientbillingaccount',
            index=models.Index(
                fields=['organization', 'status'], name='pba_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='patientbillingaccount',
            index=models.Index(
                fields=['organization', 'patient'], name='pba_org_patient_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='patientbillingaccount',
            constraint=models.UniqueConstraint(
                fields=('organization', 'account_number'),
                name='unique_patient_billing_account_number',
            ),
        ),
        migrations.AddConstraint(
            model_name='patientbillingaccount',
            constraint=models.UniqueConstraint(
                fields=('organization', 'patient'),
                name='unique_patient_billing_account_patient',
            ),
        ),
        migrations.AddConstraint(
            model_name='patientbillingaccount',
            constraint=models.CheckConstraint(
                condition=models.Q(('opening_balance__gte', Decimal('0.00'))),
                name='patient_billing_opening_balance_nonnegative',
            ),
        ),
        migrations.AddIndex(
            model_name='patientbillingstatement',
            index=models.Index(
                fields=['account', 'period_end'], name='pstmt_account_end_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='patientbillingstatement',
            index=models.Index(
                fields=['account', 'status'], name='pstmt_account_status_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='patientbillingstatement',
            constraint=models.UniqueConstraint(
                fields=('account', 'statement_number'),
                name='unique_patient_statement_number',
            ),
        ),
        migrations.AddConstraint(
            model_name='patientbillingstatement',
            constraint=models.UniqueConstraint(
                fields=('account', 'period_start', 'period_end'),
                name='unique_patient_statement_period',
            ),
        ),
        migrations.AddConstraint(
            model_name='patientbillingstatement',
            constraint=models.CheckConstraint(
                condition=models.Q(('period_end__gte', models.F('period_start'))),
                name='patient_statement_valid_period',
            ),
        ),
        migrations.AddIndex(
            model_name='patientguarantor',
            index=models.Index(
                fields=['organization', 'patient'], name='pguarantor_org_patient_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='patientguarantor',
            index=models.Index(
                fields=['patient', 'is_primary'], name='pguarantor_patient_primary_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='patientfinancialresponsibility',
            index=models.Index(
                fields=['account', 'party_type'], name='presp_account_party_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='patientfinancialresponsibility',
            index=models.Index(
                fields=['account', 'effective_from'], name='presp_account_date_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(
                fields=['organization', 'payment_date'], name='payment_org_date_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(
                fields=['invoice', 'payment_date'], name='payment_invoice_date_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(
                fields=['patient', 'payment_date'], name='payment_patient_date_idx'
            ),
        ),
    ]
