# Generated by Django 6.0.6 on 2026-07-28 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='patient',
            field=models.ForeignKey(
                help_text='Patient associated with the claim.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='insurance_claims',
                to='patients.patient',
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization that owns the invoice.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='invoices',
                to='organizations.organization',
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(
                help_text='Patient associated with the invoice.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='invoices',
                to='patients.patient',
            ),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='invoice',
            field=models.ForeignKey(
                help_text='Invoice the claim is for.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='insurance_claims',
                to='billing.invoice',
            ),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(
                help_text='Invoice this item belongs to.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='items',
                to='billing.invoice',
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(
                help_text='Invoice the payment is applied to.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payments',
                to='billing.invoice',
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization that received the payment.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payments',
                to='organizations.organization',
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(
                help_text='Patient who made the payment.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payments',
                to='patients.patient',
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(
                blank=True,
                help_text='User who recorded the payment.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='received_payments',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['organization', 'status'], name='invoice_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['organization', 'invoice_date'], name='invoice_org_date_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['patient', 'status'], name='invoice_patient_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(
                fields=['organization', 'status'], name='billing_claim_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(
                fields=['patient', 'status'], name='billing_claim_pat_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(
                fields=['invoice', 'status'], name='claim_invoice_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(
                fields=['invoice', 'service_code'], name='invoice_item_code_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(
                fields=['organization', 'payment_date'], name='payment_org_date_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(
                fields=['invoice', 'payment_date'], name='payment_invoice_date_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(
                fields=['patient', 'payment_date'], name='payment_patient_date_idx'
            ),
        ),
    ]
