# Generated by Django 6.0.6 on 2026-09-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                (
                    'holiday_type',
                    models.CharField(
                        choices=[('mandatory', 'Mandatory'), ('optional', 'Optional')],
                        default='mandatory',
                        max_length=20,
                    ),
                ),
                ('description', models.TextField(blank=True)),
                (
                    'is_recurring_yearly',
                    models.BooleanField(
                        default=False,
                        help_text='Whether this holiday recurs on the same date every year.',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='holidays',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'ordering': ['date'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('organization', 'date', 'name'),
                        name='unique_holiday_per_organization_per_date',
                    )
                ],
            },
        ),
    ]
