# Generated by Django 6.0.6 on 2026-07-04 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'diagnosis_code',
                    models.CharField(
                        db_index=True, help_text='ICD-10 diagnosis code.', max_length=20
                    ),
                ),
                (
                    'diagnosis_description',
                    models.TextField(help_text='Diagnosis description.'),
                ),
                (
                    'diagnosis_type',
                    models.CharField(
                        choices=[
                            ('primary', 'Primary'),
                            ('secondary', 'Secondary'),
                            ('admitting', 'Admitting'),
                            ('discharge', 'Discharge'),
                            ('final', 'Final'),
                        ],
                        db_index=True,
                        default='primary',
                        help_text='Diagnosis type.',
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('resolved', 'Resolved'),
                            ('inactive', 'Inactive'),
                        ],
                        db_index=True,
                        default='active',
                        help_text='Diagnosis status.',
                        max_length=20,
                    ),
                ),
                (
                    'is_primary',
                    models.BooleanField(
                        default=False,
                        help_text='Whether this is the primary diagnosis.',
                    ),
                ),
                (
                    'present_on_admission',
                    models.BooleanField(
                        default=False,
                        help_text='Whether the diagnosis was present on admission.',
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True, help_text='Additional clinical notes.'
                    ),
                ),
                (
                    'encounter',
                    models.ForeignKey(
                        help_text='Encounter associated with this diagnosis.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='diagnoses',
                        to='encounters.encounter',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns this diagnosis.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='diagnoses',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
                'db_table': 'diagnoses',
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(
                        fields=['diagnosis_code'], name='diagnoses_diagnos_3ecb67_idx'
                    ),
                    models.Index(fields=['status'], name='diagnoses_status_b3ae1b_idx'),
                    models.Index(
                        fields=['diagnosis_type'], name='diagnoses_diagnos_049279_idx'
                    ),
                    models.Index(
                        fields=['encounter'], name='diagnoses_encount_1b4290_idx'
                    ),
                    models.Index(
                        fields=['organization'], name='diagnoses_organiz_c0ea99_idx'
                    ),
                    models.Index(
                        fields=['encounter', 'is_primary'],
                        name='diagnoses_encount_218ad8_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('organization', 'encounter', 'diagnosis_code'),
                        name='unique_diagnosis_per_encounter',
                    )
                ],
            },
        ),
    ]
