# Generated by Django 6.0.6 on 2026-07-14 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("organizations", "0001_initial"),
        ("patients", "0001_initial"),
        ("providers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "encounter_number",
                    models.CharField(
                        help_text="Unique encounter number.", max_length=30
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        help_text="Encounter status.",
                        max_length=20,
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        blank=True, help_text="Primary reason for the encounter."
                    ),
                ),
                (
                    "history_of_present_illness",
                    models.TextField(
                        blank=True, help_text="History of present illness."
                    ),
                ),
                (
                    "assessment",
                    models.TextField(blank=True, help_text="Clinical assessment."),
                ),
                ("plan", models.TextField(blank=True, help_text="Treatment plan.")),
                (
                    "clinical_notes",
                    models.TextField(blank=True, help_text="Clinical notes."),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="Encounter start time.", null=True
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, help_text="Encounter end time.", null=True
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Encounter duration in minutes."
                    ),
                ),
                (
                    "is_billable",
                    models.BooleanField(
                        default=True, help_text="Whether the encounter is billable."
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        help_text="Appointment associated with this encounter.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounter",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this encounter.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="organizations.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient for this encounter.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="patients.patient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="Healthcare provider for this encounter.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encounter",
                "verbose_name_plural": "Encounters",
                "db_table": "encounters",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["encounter_number"],
                        name="encounters_encount_5a3539_idx",
                    ),
                    models.Index(
                        fields=["status"], name="encounters_status_2bbb51_idx"
                    ),
                    models.Index(
                        fields=["patient"], name="encounters_patient_42ac76_idx"
                    ),
                    models.Index(
                        fields=["provider"], name="encounters_provide_b0a0fc_idx"
                    ),
                    models.Index(
                        fields=["appointment"], name="encounters_appoint_4b9793_idx"
                    ),
                    models.Index(
                        fields=["started_at"], name="encounters_started_3d026b_idx"
                    ),
                    models.Index(
                        fields=["provider", "started_at"],
                        name="encounters_provide_ab015f_idx",
                    ),
                    models.Index(
                        fields=["patient", "started_at"],
                        name="encounters_patient_fc3997_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "encounter_number"),
                        name="unique_encounter_number_per_organization",
                    )
                ],
            },
        ),
    ]
