# Generated by Django 6.0.6 on 2026-07-28 10:24

import apps.core.models.managers
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'encounter_number',
                    models.CharField(
                        help_text='Unique encounter number.', max_length=30
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('scheduled', 'Scheduled'),
                            ('in_progress', 'In Progress'),
                            ('completed', 'Completed'),
                            ('cancelled', 'Cancelled'),
                        ],
                        db_index=True,
                        default='scheduled',
                        help_text='Encounter status.',
                        max_length=20,
                    ),
                ),
                (
                    'chief_complaint',
                    models.TextField(
                        blank=True, help_text='Primary reason for the encounter.'
                    ),
                ),
                (
                    'history_of_present_illness',
                    models.TextField(
                        blank=True, help_text='History of present illness.'
                    ),
                ),
                (
                    'assessment',
                    models.TextField(blank=True, help_text='Clinical assessment.'),
                ),
                ('plan', models.TextField(blank=True, help_text='Treatment plan.')),
                (
                    'clinical_notes',
                    models.TextField(blank=True, help_text='Clinical notes.'),
                ),
                (
                    'started_at',
                    models.DateTimeField(
                        blank=True, help_text='Encounter start time.', null=True
                    ),
                ),
                (
                    'ended_at',
                    models.DateTimeField(
                        blank=True, help_text='Encounter end time.', null=True
                    ),
                ),
                (
                    'duration_minutes',
                    models.PositiveIntegerField(
                        default=0, help_text='Encounter duration in minutes.'
                    ),
                ),
                (
                    'is_billable',
                    models.BooleanField(
                        default=True, help_text='Whether the encounter is billable.'
                    ),
                ),
                (
                    'appointment',
                    models.OneToOneField(
                        help_text='Appointment associated with this encounter.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='encounter',
                        to='appointments.appointment',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns this encounter.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='encounters',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Encounter',
                'verbose_name_plural': 'Encounters',
                'db_table': 'encounters',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
    ]
