# Generated by Django 6.0.6 on 2026-09-11 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'appointments',
            '0003_alter_appointment_options_alter_appointment_managers_and_more',
        ),
        ('encounters', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patient_core', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ('-started_at', '-created_at')},
        ),
        migrations.RemoveIndex(
            model_name='encounter',
            name='encounters_encount_5a3539_idx',
        ),
        migrations.RemoveIndex(
            model_name='encounter',
            name='encounters_status_2bbb51_idx',
        ),
        migrations.RemoveIndex(
            model_name='encounter',
            name='encounters_patient_42ac76_idx',
        ),
        migrations.RemoveIndex(
            model_name='encounter',
            name='encounters_provide_b0a0fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='encounter',
            name='encounters_appoint_4b9793_idx',
        ),
        migrations.AlterField(
            model_name='encounter',
            name='appointment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='encounters',
                to='appointments.appointment',
            ),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='clinical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='history_of_present_illness',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='is_billable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='encounters',
                to='organizations.organization',
            ),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='encounters',
                to='patient_core.patient',
            ),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='plan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='provider',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='encounters',
                to='providers.provider',
            ),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='status',
            field=models.CharField(
                choices=[
                    ('scheduled', 'Scheduled'),
                    ('in_progress', 'In Progress'),
                    ('completed', 'Completed'),
                    ('cancelled', 'Cancelled'),
                ],
                db_index=True,
                default='scheduled',
                max_length=30,
            ),
        ),
    ]
