# Generated by Django 6.0.6 on 2026-07-28 10:24

import apps.core.models.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'diagnosis_code',
                    models.CharField(
                        db_index=True, help_text='ICD-10 diagnosis code.', max_length=20
                    ),
                ),
                (
                    'diagnosis_description',
                    models.TextField(help_text='Diagnosis description.'),
                ),
                (
                    'diagnosis_type',
                    models.CharField(
                        choices=[
                            ('primary', 'Primary'),
                            ('secondary', 'Secondary'),
                            ('admitting', 'Admitting'),
                            ('discharge', 'Discharge'),
                            ('final', 'Final'),
                        ],
                        db_index=True,
                        default='primary',
                        help_text='Diagnosis type.',
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('resolved', 'Resolved'),
                            ('inactive', 'Inactive'),
                        ],
                        db_index=True,
                        default='active',
                        help_text='Diagnosis status.',
                        max_length=20,
                    ),
                ),
                (
                    'is_primary',
                    models.BooleanField(
                        default=False,
                        help_text='Whether this is the primary diagnosis.',
                    ),
                ),
                (
                    'present_on_admission',
                    models.BooleanField(
                        default=False,
                        help_text='Whether the diagnosis was present on admission.',
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True, help_text='Additional clinical notes.'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
                'db_table': 'diagnoses',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
    ]
