# Generated by Django 6.0.6 on 2026-09-11 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0001_initial'),
        ('encounters', '0002_alter_encounter_options_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveConstraint(
            model_name='diagnosis',
            name='unique_diagnosis_per_encounter',
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_type',
            field=models.CharField(
                choices=[
                    ('primary', 'Primary'),
                    ('secondary', 'Secondary'),
                    ('differential', 'Differential'),
                    ('historical', 'Historical'),
                ],
                db_index=True,
                default='secondary',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='encounter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='diagnoses',
                to='encounters.encounter',
            ),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='diagnoses',
                to='organizations.organization',
            ),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='present_on_admission',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='status',
            field=models.CharField(
                choices=[
                    ('active', 'Active'),
                    ('resolved', 'Resolved'),
                    ('inactive', 'Inactive'),
                    ('ruled_out', 'Ruled Out'),
                ],
                db_index=True,
                default='active',
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name='diagnosis',
            constraint=models.UniqueConstraint(
                fields=('encounter', 'diagnosis_code', 'diagnosis_type'),
                name='unique_diagnosis_per_encounter',
            ),
        ),
    ]
