# Generated by Django 6.0.6 on 2026-07-28 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnoses', '0001_initial'),
        ('encounters', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='encounter',
            field=models.ForeignKey(
                help_text='Encounter associated with this diagnosis.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='diagnoses',
                to='encounters.encounter',
            ),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization that owns this diagnosis.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='diagnoses',
                to='organizations.organization',
            ),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(
                fields=['diagnosis_code'], name='diagnoses_diagnos_3ecb67_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['status'], name='diagnoses_status_b3ae1b_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(
                fields=['diagnosis_type'], name='diagnoses_diagnos_049279_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(
                fields=['encounter'], name='diagnoses_encount_1b4290_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(
                fields=['organization'], name='diagnoses_organiz_c0ea99_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(
                fields=['encounter', 'is_primary'], name='diagnoses_encount_218ad8_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='diagnosis',
            constraint=models.UniqueConstraint(
                fields=('organization', 'encounter', 'diagnosis_code'),
                name='unique_diagnosis_per_encounter',
            ),
        ),
    ]
