# Generated by Django 6.0.6 on 2026-07-31 11:49

import apps.core.models.managers
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                (
                    'plan_type',
                    models.CharField(
                        choices=[
                            ('STARTER', 'Starter'),
                            ('PROFESSIONAL', 'Professional'),
                            ('BUSINESS', 'Business'),
                            ('ENTERPRISE', 'Enterprise'),
                            ('CUSTOM', 'Custom Enterprise'),
                        ],
                        db_index=True,
                        default='STARTER',
                        max_length=30,
                    ),
                ),
                (
                    'healthcare_segment',
                    models.CharField(
                        choices=[
                            ('HOSPITAL', 'Hospital'),
                            ('CLINIC', 'Clinic'),
                            ('PHARMACY', 'Pharmacy / Medical Store'),
                            ('LABORATORY', 'Diagnostic Laboratory'),
                            ('IMAGING', 'Imaging Center'),
                            ('DENTAL', 'Dental Clinic'),
                            ('PHYSIOTHERAPY', 'Physiotherapy Center'),
                            ('NURSING_HOME', 'Nursing Home'),
                            ('ENTERPRISE', 'Healthcare Enterprise'),
                        ],
                        db_index=True,
                        default='CLINIC',
                        max_length=50,
                    ),
                ),
                ('display_order', models.PositiveIntegerField(default=0)),
                (
                    'price',
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    'setup_fee',
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    'currency',
                    models.CharField(
                        choices=[
                            ('USD', 'US Dollar'),
                            ('INR', 'Indian Rupee'),
                            ('EUR', 'Euro'),
                            ('GBP', 'British Pound'),
                        ],
                        default='INR',
                        max_length=10,
                    ),
                ),
                (
                    'billing_cycle',
                    models.CharField(
                        choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')],
                        default='monthly',
                        max_length=20,
                    ),
                ),
                ('trial_days', models.PositiveIntegerField(default=14)),
                ('annual_discount_percentage', models.PositiveIntegerField(default=0)),
                ('max_users', models.PositiveIntegerField(default=5)),
                ('max_branches', models.PositiveIntegerField(default=1)),
                ('max_doctors', models.PositiveIntegerField(default=5)),
                ('max_patients', models.PositiveBigIntegerField(default=1000)),
                ('max_lab_orders', models.PositiveIntegerField(default=1000)),
                ('max_imaging_orders', models.PositiveIntegerField(default=1000)),
                ('max_pharmacy_products', models.PositiveIntegerField(default=1000)),
                (
                    'max_inventory_transactions',
                    models.PositiveIntegerField(default=10000),
                ),
                ('max_storage_gb', models.PositiveIntegerField(default=5)),
                ('max_api_requests', models.PositiveBigIntegerField(default=10000)),
                ('max_ai_requests', models.PositiveBigIntegerField(default=1000)),
                ('max_ai_tokens', models.PositiveBigIntegerField(default=100000)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('modules', models.JSONField(blank=True, default=dict)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                (
                    'is_default',
                    models.BooleanField(
                        default=False, help_text='Default plan assigned during signup.'
                    ),
                ),
                ('is_custom', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SaaS Billing Plan',
                'verbose_name_plural': 'SaaS Billing Plans',
                'db_table': 'saas_billing_plans',
                'ordering': ('display_order', 'price', 'name'),
                'indexes': [
                    models.Index(fields=['code'], name='saas_billin_code_c31e13_idx'),
                    models.Index(
                        fields=['plan_type'], name='saas_billin_plan_ty_501899_idx'
                    ),
                    models.Index(
                        fields=['healthcare_segment'],
                        name='saas_billin_healthc_3ca5d9_idx',
                    ),
                    models.Index(
                        fields=['is_active', 'is_public'],
                        name='saas_billin_is_acti_620517_idx',
                    ),
                ],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('TRIAL', 'Trial'),
                            ('ACTIVE', 'Active'),
                            ('PAST_DUE', 'Past Due'),
                            ('SUSPENDED', 'Suspended'),
                            ('CANCELLED', 'Cancelled'),
                            ('EXPIRED', 'Expired'),
                        ],
                        db_index=True,
                        default='TRIAL',
                        max_length=30,
                    ),
                ),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('grace_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                (
                    'cancellation_reason',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('CUSTOMER_REQUEST', 'Customer Request'),
                            ('PAYMENT_FAILURE', 'Payment Failure'),
                            ('PLAN_CHANGE', 'Plan Change'),
                            ('OTHER', 'Other'),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'auto_renew',
                    models.BooleanField(
                        default=True, help_text='Automatically renew subscription.'
                    ),
                ),
                (
                    'plan_snapshot',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Frozen plan configuration at purchase time.',
                    ),
                ),
                (
                    'feature_snapshot',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Feature entitlement snapshot.',
                    ),
                ),
                ('seats_used', models.PositiveIntegerField(default=0)),
                ('usage_snapshot', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(blank=True, max_length=50)),
                (
                    'external_subscription_id',
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'organization',
                    models.OneToOneField(
                        help_text='Organization subscription.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='saas_subscription',
                        to='organizations.organization',
                    ),
                ),
                (
                    'plan',
                    models.ForeignKey(
                        help_text='Subscribed SaaS plan.',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='subscriptions',
                        to='saas_billing.plan',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        help_text='Tenant owning subscription.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscriptions',
                        to='tenancy.tenant',
                    ),
                ),
            ],
            options={
                'verbose_name': 'SaaS Subscription',
                'verbose_name_plural': 'SaaS Subscriptions',
                'db_table': 'saas_subscriptions',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'invoice_number',
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    'invoice_type',
                    models.CharField(
                        choices=[
                            ('SUBSCRIPTION', 'Subscription'),
                            ('USAGE', 'Usage Based'),
                            ('ADDON', 'Addon'),
                            ('CREDIT_NOTE', 'Credit Note'),
                        ],
                        default='SUBSCRIPTION',
                        max_length=30,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('DRAFT', 'Draft'),
                            ('ISSUED', 'Issued'),
                            ('SENT', 'Sent'),
                            ('PARTIALLY_PAID', 'Partially Paid'),
                            ('PAID', 'Paid'),
                            ('OVERDUE', 'Overdue'),
                            ('FAILED', 'Failed'),
                            ('CANCELLED', 'Cancelled'),
                            ('REFUNDED', 'Refunded'),
                        ],
                        db_index=True,
                        default='DRAFT',
                        max_length=30,
                    ),
                ),
                ('billing_period_start', models.DateTimeField(blank=True, null=True)),
                ('billing_period_end', models.DateTimeField(blank=True, null=True)),
                (
                    'subtotal',
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    'tax_amount',
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    'discount_amount',
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    'total_amount',
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    'paid_amount',
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ('currency', models.CharField(default='INR', max_length=10)),
                (
                    'tax_details',
                    models.JSONField(
                        blank=True, default=dict, help_text='GST/VAT breakdown.'
                    ),
                ),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('payment_provider', models.CharField(blank=True, max_length=50)),
                (
                    'external_invoice_id',
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    'pdf_file',
                    models.FileField(
                        blank=True, null=True, upload_to='billing/invoices/'
                    ),
                ),
                (
                    'invoice_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Invoice lines and metadata.',
                    ),
                ),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization billed.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='saas_invoices',
                        to='organizations.organization',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        help_text='Tenant owning invoice.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invoices',
                        to='tenancy.tenant',
                    ),
                ),
                (
                    'subscription',
                    models.ForeignKey(
                        help_text='Subscription associated with invoice.',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='invoices',
                        to='saas_billing.subscription',
                    ),
                ),
            ],
            options={
                'verbose_name': 'SaaS Invoice',
                'verbose_name_plural': 'SaaS Invoices',
                'db_table': 'saas_invoices',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'metric_type',
                    models.CharField(
                        choices=[
                            ('USERS', 'Users'),
                            ('STORAGE_GB', 'Storage GB'),
                            ('API_CALLS', 'API Calls'),
                            ('PATIENTS', 'Patients'),
                            ('APPOINTMENTS', 'Appointments'),
                            ('ENCOUNTERS', 'Clinical Encounters'),
                            ('PRESCRIPTIONS', 'Prescriptions'),
                            ('LAB_ORDERS', 'Laboratory Orders'),
                            ('IMAGING_STUDIES', 'Imaging Studies'),
                            ('TELEMEDICINE_MINUTES', 'Telemedicine Minutes'),
                            ('PHARMACY_ORDERS', 'Pharmacy Orders'),
                            ('INVENTORY_TRANSACTIONS', 'Inventory Transactions'),
                            ('BILLING_TRANSACTIONS', 'Billing Transactions'),
                            ('AI_REQUESTS', 'AI Requests'),
                            ('AI_TOKENS', 'AI Tokens'),
                            ('AI_DOCUMENTS', 'AI Documents Processed'),
                            ('WORKFLOW_EXECUTIONS', 'Workflow Executions'),
                            ('AUTOMATIONS', 'Automation Executions'),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    'value',
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text='Measured usage value.',
                        max_digits=18,
                    ),
                ),
                ('unit', models.CharField(default='count', max_length=50)),
                ('is_billable', models.BooleanField(db_index=True, default=False)),
                (
                    'billing_rate',
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text='Cost per usage unit.',
                        max_digits=12,
                    ),
                ),
                (
                    'calculated_cost',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text='Calculated billing amount.',
                        max_digits=14,
                    ),
                ),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                (
                    'source',
                    models.CharField(
                        blank=True,
                        help_text='DatavionOS module generating usage.',
                        max_length=100,
                    ),
                ),
                (
                    'reference_id',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='Related business object identifier.',
                        max_length=255,
                    ),
                ),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='saas_usage',
                        to='organizations.organization',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='usage_records',
                        to='tenancy.tenant',
                    ),
                ),
            ],
            options={
                'verbose_name': 'SaaS Usage',
                'verbose_name_plural': 'SaaS Usage Records',
                'db_table': 'saas_usage',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'legal_name',
                    models.CharField(
                        help_text='Registered legal billing entity name.',
                        max_length=255,
                    ),
                ),
                (
                    'billing_email',
                    models.EmailField(
                        help_text='Primary billing email.', max_length=254
                    ),
                ),
                ('billing_phone', models.CharField(blank=True, max_length=30)),
                ('billing_contact_name', models.CharField(blank=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('gst_number', models.CharField(blank=True, max_length=100)),
                ('vat_number', models.CharField(blank=True, max_length=100)),
                (
                    'currency',
                    models.CharField(
                        choices=[
                            ('USD', 'US Dollar'),
                            ('INR', 'Indian Rupee'),
                            ('EUR', 'Euro'),
                            ('GBP', 'British Pound'),
                        ],
                        default='INR',
                        max_length=10,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('ACTIVE', 'Active'),
                            ('SUSPENDED', 'Suspended'),
                            ('CLOSED', 'Closed'),
                        ],
                        db_index=True,
                        default='ACTIVE',
                        max_length=20,
                    ),
                ),
                (
                    'payment_terms',
                    models.CharField(
                        choices=[
                            ('IMMEDIATE', 'Immediate Payment'),
                            ('NET_15', 'Net 15 Days'),
                            ('NET_30', 'Net 30 Days'),
                            ('NET_60', 'Net 60 Days'),
                        ],
                        default='IMMEDIATE',
                        max_length=20,
                    ),
                ),
                ('billing_address', models.JSONField(blank=True, default=dict)),
                ('tax_configuration', models.JSONField(blank=True, default=dict)),
                ('purchase_order_required', models.BooleanField(default=False)),
                ('purchase_order_number', models.CharField(blank=True, max_length=100)),
                (
                    'credit_limit',
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ('grace_period_days', models.PositiveIntegerField(default=7)),
                ('accounting_reference', models.CharField(blank=True, max_length=255)),
                ('payment_provider', models.CharField(blank=True, max_length=50)),
                (
                    'payment_customer_id',
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    'default_payment_method_id',
                    models.CharField(blank=True, max_length=255),
                ),
                ('auto_charge_enabled', models.BooleanField(default=False)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'organization',
                    models.OneToOneField(
                        help_text='Organization billing account.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='billing_account',
                        to='organizations.organization',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        help_text='Tenant owning billing account.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='billing_accounts',
                        to='tenancy.tenant',
                    ),
                ),
            ],
            options={
                'verbose_name': 'SaaS Billing Account',
                'verbose_name_plural': 'SaaS Billing Accounts',
                'db_table': 'saas_billing_accounts',
                'indexes': [
                    models.Index(
                        fields=['tenant'], name='saas_billin_tenant__8d6675_idx'
                    ),
                    models.Index(
                        fields=['status'], name='saas_billin_status_a57dff_idx'
                    ),
                    models.Index(
                        fields=['payment_customer_id'],
                        name='saas_billin_payment_ec440a_idx',
                    ),
                ],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'provider',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('STRIPE', 'Stripe'),
                            ('RAZORPAY', 'Razorpay'),
                            ('PAYPAL', 'PayPal'),
                            ('BANK', 'Bank Transfer'),
                            ('MANUAL', 'Manual'),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'payment_method',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('CARD', 'Card'),
                            ('UPI', 'UPI'),
                            ('NET_BANKING', 'Net Banking'),
                            ('BANK_TRANSFER', 'Bank Transfer'),
                            ('WALLET', 'Wallet'),
                            ('OTHER', 'Other'),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'transaction_id',
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    'gateway_payment_id',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='Payment gateway payment identifier.',
                        max_length=255,
                    ),
                ),
                (
                    'gateway_order_id',
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    'amount',
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    'refunded_amount',
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ('currency', models.CharField(default='INR', max_length=10)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('PROCESSING', 'Processing'),
                            ('SUCCESS', 'Success'),
                            ('FAILED', 'Failed'),
                            ('CANCELLED', 'Cancelled'),
                            ('REFUNDED', 'Refunded'),
                            ('PARTIALLY_REFUNDED', 'Partially Refunded'),
                        ],
                        db_index=True,
                        default='PENDING',
                        max_length=30,
                    ),
                ),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                (
                    'gateway_response',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Raw payment gateway response.',
                    ),
                ),
                (
                    'reconciliation_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Accounting reconciliation information.',
                    ),
                ),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'invoice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='payments',
                        to='saas_billing.invoice',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='saas_payments',
                        to='organizations.organization',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payments',
                        to='tenancy.tenant',
                    ),
                ),
            ],
            options={
                'verbose_name': 'SaaS Payment',
                'verbose_name_plural': 'SaaS Payments',
                'db_table': 'saas_payments',
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(
                        fields=['tenant', 'status'],
                        name='saas_paymen_tenant__8e7161_idx',
                    ),
                    models.Index(
                        fields=['organization', 'status'],
                        name='saas_paymen_organiz_435783_idx',
                    ),
                    models.Index(
                        fields=['invoice'], name='saas_paymen_invoice_74f41a_idx'
                    ),
                    models.Index(
                        fields=['transaction_id'], name='saas_paymen_transac_b67865_idx'
                    ),
                    models.Index(
                        fields=['gateway_payment_id'],
                        name='saas_paymen_gateway_1615de_idx',
                    ),
                ],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(
                fields=['tenant'], name='saas_subscr_tenant__81315a_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='saas_subscr_status_0daec3_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(
                fields=['current_period_end'], name='saas_subscr_current_85644b_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(
                fields=['expires_at'], name='saas_subscr_expires_3f4d72_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(
                fields=['external_subscription_id'],
                name='saas_subscr_externa_66e0f8_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['tenant', 'status'], name='saas_invoic_tenant__8d77d2_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['organization', 'status'], name='saas_invoic_organiz_4d7413_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['invoice_number'], name='saas_invoic_invoice_f5f3c2_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['external_invoice_id'], name='saas_invoic_externa_b36699_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='usage',
            index=models.Index(
                fields=['tenant', 'metric_type'], name='saas_usage_tenant__a9c89c_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='usage',
            index=models.Index(
                fields=['organization', 'metric_type'],
                name='saas_usage_organiz_553def_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='usage',
            index=models.Index(
                fields=['period_start', 'period_end'],
                name='saas_usage_period__893356_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='usage',
            index=models.Index(
                fields=['is_billable'], name='saas_usage_is_bill_aa3dbd_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='usage',
            index=models.Index(
                fields=['reference_id'], name='saas_usage_referen_6a490c_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='usage',
            constraint=models.UniqueConstraint(
                fields=('organization', 'metric_type', 'period_start', 'period_end'),
                name='unique_usage_period_metric',
            ),
        ),
    ]
