# Generated by Django 6.0.6 on 2026-07-29 03:59

import apps.core.models.managers
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('saas_billing', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={
                'ordering': ('display_order', 'price', 'name'),
                'verbose_name': 'SaaS Billing Plan',
                'verbose_name_plural': 'SaaS Billing Plans',
            },
        ),
        migrations.AlterModelOptions(
            name='usage',
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'SaaS Usage',
                'verbose_name_plural': 'SaaS Usage Records',
            },
        ),
        migrations.AlterModelManagers(
            name='billingaccount',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='payment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='plan',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subscription',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='usage',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='saas_invoic_issued__e8f9c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='plan',
            name='saas_billin_is_acti_7546d0_idx',
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='accounting_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='billing_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='payment_terms',
            field=models.CharField(
                choices=[
                    ('IMMEDIATE', 'Immediate Payment'),
                    ('NET_15', 'Net 15 Days'),
                    ('NET_30', 'Net 30 Days'),
                    ('NET_60', 'Net 60 Days'),
                ],
                default='IMMEDIATE',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='purchase_order_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='purchase_order_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='status',
            field=models.CharField(
                choices=[
                    ('ACTIVE', 'Active'),
                    ('SUSPENDED', 'Suspended'),
                    ('CLOSED', 'Closed'),
                ],
                db_index=True,
                default='ACTIVE',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='tax_configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                help_text='Tenant owning billing account.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='billing_accounts',
                to='tenancy.tenant',
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='external_invoice_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(
                choices=[
                    ('SUBSCRIPTION', 'Subscription'),
                    ('USAGE', 'Usage Based'),
                    ('ADDON', 'Addon'),
                    ('CREDIT_NOTE', 'Credit Note'),
                ],
                default='SUBSCRIPTION',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(
                blank=True, null=True, upload_to='billing/invoices/'
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_details',
            field=models.JSONField(
                blank=True, default=dict, help_text='GST/VAT breakdown.'
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                help_text='Tenant owning invoice.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='invoices',
                to='tenancy.tenant',
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_payment_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Payment gateway payment identifier.',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(
                blank=True, default=dict, help_text='Raw payment gateway response.'
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(
                blank=True,
                choices=[
                    ('CARD', 'Card'),
                    ('UPI', 'UPI'),
                    ('NET_BANKING', 'Net Banking'),
                    ('BANK_TRANSFER', 'Bank Transfer'),
                    ('WALLET', 'Wallet'),
                    ('OTHER', 'Other'),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciliation_data',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Accounting reconciliation information.',
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payments',
                to='tenancy.tenant',
            ),
        ),
        migrations.AddField(
            model_name='plan',
            name='annual_discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='healthcare_segment',
            field=models.CharField(
                choices=[
                    ('HOSPITAL', 'Hospital'),
                    ('CLINIC', 'Clinic'),
                    ('PHARMACY', 'Pharmacy / Medical Store'),
                    ('LABORATORY', 'Diagnostic Laboratory'),
                    ('IMAGING', 'Imaging Center'),
                    ('DENTAL', 'Dental Clinic'),
                    ('PHYSIOTHERAPY', 'Physiotherapy Center'),
                    ('NURSING_HOME', 'Nursing Home'),
                    ('ENTERPRISE', 'Healthcare Enterprise'),
                ],
                db_index=True,
                default='CLINIC',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_default',
            field=models.BooleanField(
                default=False, help_text='Default plan assigned during signup.'
            ),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='limits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_ai_requests',
            field=models.PositiveBigIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_ai_tokens',
            field=models.PositiveBigIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_api_requests',
            field=models.PositiveBigIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_branches',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_doctors',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_imaging_orders',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_inventory_transactions',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_lab_orders',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_pharmacy_products',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='plan',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(
                choices=[
                    ('STARTER', 'Starter'),
                    ('PROFESSIONAL', 'Professional'),
                    ('BUSINESS', 'Business'),
                    ('ENTERPRISE', 'Enterprise'),
                    ('CUSTOM', 'Custom Enterprise'),
                ],
                db_index=True,
                default='STARTER',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='plan',
            name='setup_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancellation_reason',
            field=models.CharField(
                blank=True,
                choices=[
                    ('CUSTOMER_REQUEST', 'Customer Request'),
                    ('PAYMENT_FAILURE', 'Payment Failure'),
                    ('PLAN_CHANGE', 'Plan Change'),
                    ('OTHER', 'Other'),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='feature_snapshot',
            field=models.JSONField(
                blank=True, default=dict, help_text='Feature entitlement snapshot.'
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='grace_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_snapshot',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Frozen plan configuration at purchase time.',
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='seats_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                help_text='Tenant owning subscription.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscriptions',
                to='tenancy.tenant',
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='usage_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usage',
            name='billing_rate',
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text='Cost per usage unit.',
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name='usage',
            name='calculated_cost',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Calculated billing amount.',
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name='usage',
            name='is_billable',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='usage',
            name='reference_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Related business object identifier.',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name='usage',
            name='source',
            field=models.CharField(
                blank=True,
                help_text='DatavionOS module generating usage.',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name='usage',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='usage_records',
                to='tenancy.tenant',
            ),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='auto_charge_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='billing_address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='currency',
            field=models.CharField(
                choices=[
                    ('USD', 'US Dollar'),
                    ('INR', 'Indian Rupee'),
                    ('EUR', 'Euro'),
                    ('GBP', 'British Pound'),
                ],
                default='INR',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='default_payment_method_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='gst_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='legal_name',
            field=models.CharField(
                help_text='Registered legal billing entity name.', max_length=255
            ),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='payment_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_data',
            field=models.JSONField(
                blank=True, default=dict, help_text='Invoice lines and metadata.'
            ),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Draft'),
                    ('ISSUED', 'Issued'),
                    ('SENT', 'Sent'),
                    ('PARTIALLY_PAID', 'Partially Paid'),
                    ('PAID', 'Paid'),
                    ('OVERDUE', 'Overdue'),
                    ('FAILED', 'Failed'),
                    ('CANCELLED', 'Cancelled'),
                    ('REFUNDED', 'Refunded'),
                ],
                db_index=True,
                default='DRAFT',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(
                help_text='Subscription associated with invoice.',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='invoices',
                to='saas_billing.subscription',
            ),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payments',
                to='saas_billing.invoice',
            ),
        ),
        migrations.AlterField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='saas_payments',
                to='organizations.organization',
            ),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(
                blank=True,
                choices=[
                    ('STRIPE', 'Stripe'),
                    ('RAZORPAY', 'Razorpay'),
                    ('PAYPAL', 'PayPal'),
                    ('BANK', 'Bank Transfer'),
                    ('MANUAL', 'Manual'),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('PROCESSING', 'Processing'),
                    ('SUCCESS', 'Success'),
                    ('FAILED', 'Failed'),
                    ('CANCELLED', 'Cancelled'),
                    ('REFUNDED', 'Refunded'),
                    ('PARTIALLY_REFUNDED', 'Partially Refunded'),
                ],
                db_index=True,
                default='PENDING',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(
                choices=[
                    ('USD', 'US Dollar'),
                    ('INR', 'Indian Rupee'),
                    ('EUR', 'Euro'),
                    ('GBP', 'British Pound'),
                ],
                default='INR',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_patients',
            field=models.PositiveBigIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_storage_gb',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_users',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='modules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='external_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='organization',
            field=models.OneToOneField(
                help_text='Organization subscription.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='saas_subscription',
                to='organizations.organization',
            ),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(
                choices=[
                    ('TRIAL', 'Trial'),
                    ('ACTIVE', 'Active'),
                    ('PAST_DUE', 'Past Due'),
                    ('SUSPENDED', 'Suspended'),
                    ('CANCELLED', 'Cancelled'),
                    ('EXPIRED', 'Expired'),
                ],
                db_index=True,
                default='TRIAL',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='usage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='usage',
            name='metric_type',
            field=models.CharField(
                choices=[
                    ('USERS', 'Users'),
                    ('STORAGE_GB', 'Storage GB'),
                    ('API_CALLS', 'API Calls'),
                    ('PATIENTS', 'Patients'),
                    ('APPOINTMENTS', 'Appointments'),
                    ('ENCOUNTERS', 'Clinical Encounters'),
                    ('PRESCRIPTIONS', 'Prescriptions'),
                    ('LAB_ORDERS', 'Laboratory Orders'),
                    ('IMAGING_STUDIES', 'Imaging Studies'),
                    ('TELEMEDICINE_MINUTES', 'Telemedicine Minutes'),
                    ('PHARMACY_ORDERS', 'Pharmacy Orders'),
                    ('INVENTORY_TRANSACTIONS', 'Inventory Transactions'),
                    ('BILLING_TRANSACTIONS', 'Billing Transactions'),
                    ('AI_REQUESTS', 'AI Requests'),
                    ('AI_TOKENS', 'AI Tokens'),
                    ('AI_DOCUMENTS', 'AI Documents Processed'),
                    ('WORKFLOW_EXECUTIONS', 'Workflow Executions'),
                    ('AUTOMATIONS', 'Automation Executions'),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='usage',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='saas_usage',
                to='organizations.organization',
            ),
        ),
        migrations.AlterField(
            model_name='usage',
            name='period_end',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='period_start',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='unit',
            field=models.CharField(default='count', max_length=50),
        ),
        migrations.AlterField(
            model_name='usage',
            name='value',
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text='Measured usage value.',
                max_digits=18,
            ),
        ),
        migrations.AddIndex(
            model_name='billingaccount',
            index=models.Index(
                fields=['tenant'], name='saas_billin_tenant__8d6675_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='billingaccount',
            index=models.Index(fields=['status'], name='saas_billin_status_a57dff_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['tenant', 'status'], name='saas_invoic_tenant__8d77d2_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(
                fields=['external_invoice_id'], name='saas_invoic_externa_b36699_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(
                fields=['tenant', 'status'], name='saas_paymen_tenant__8e7161_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(
                fields=['gateway_payment_id'], name='saas_paymen_gateway_1615de_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(
                fields=['plan_type'], name='saas_billin_plan_ty_501899_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(
                fields=['healthcare_segment'], name='saas_billin_healthc_3ca5d9_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(
                fields=['is_active', 'is_public'], name='saas_billin_is_acti_620517_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(
                fields=['tenant'], name='saas_subscr_tenant__81315a_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(
                fields=['current_period_end'], name='saas_subscr_current_85644b_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='usage',
            index=models.Index(
                fields=['tenant', 'metric_type'], name='saas_usage_tenant__a9c89c_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='usage',
            index=models.Index(
                fields=['is_billable'], name='saas_usage_is_bill_aa3dbd_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='usage',
            index=models.Index(
                fields=['reference_id'], name='saas_usage_referen_6a490c_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='usage',
            constraint=models.UniqueConstraint(
                fields=('organization', 'metric_type', 'period_start', 'period_end'),
                name='unique_usage_period_metric',
            ),
        ),
    ]
