# Generated by Django 6.0.6 on 2026-07-29 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_billing', '0002_alter_plan_options_alter_usage_options_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaccount',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant owning billing account.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='billing_accounts',
                to='tenancy.tenant',
            ),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant owning invoice.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='invoices',
                to='tenancy.tenant',
            ),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payments',
                to='tenancy.tenant',
            ),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant owning subscription.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscriptions',
                to='tenancy.tenant',
            ),
        ),
        migrations.AlterField(
            model_name='usage',
            name='tenant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='usage_records',
                to='tenancy.tenant',
            ),
        ),
    ]
