# Generated by Django 6.0.6 on 2026-10-01 09:02

import apps.core.models.managers
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('patient_core', '0001_initial'),
        ('revenue_cycle_billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcarepayment',
            name='gateway_order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='healthcarepayment',
            name='gateway_payment_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.CreateModel(
            name='PatientBillingAccount',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates whether the entity is available for normal operations.', verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True, verbose_name='Deleted By')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUID v4 identifier.', primary_key=True, serialize=False, unique=True, verbose_name='Identifier')),
                ('account_number', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='INR', max_length=3)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_billing_accounts', to='organizations.organization')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_account', to='patient_core.patient')),
            ],
            options={
                'db_table': 'billing_patient_accounts',
                'ordering': ('account_number',),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientBillingStatement',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates whether the entity is available for normal operations.', verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True, verbose_name='Deleted By')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUID v4 identifier.', primary_key=True, serialize=False, unique=True, verbose_name='Identifier')),
                ('statement_number', models.CharField(db_index=True, max_length=60)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('adjustments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='revenue_cycle_billing.patientbillingaccount')),
            ],
            options={
                'db_table': 'billing_patient_statements',
                'ordering': ('-period_end', '-created_at'),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientGuarantor',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates whether the entity is available for normal operations.', verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True, verbose_name='Deleted By')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUID v4 identifier.', primary_key=True, serialize=False, unique=True, verbose_name='Identifier')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_guarantors', to='organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_guarantors', to='patient_core.patient')),
            ],
            options={
                'db_table': 'billing_patient_guarantors',
                'ordering': ('-is_primary', 'name'),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientFinancialResponsibility',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates whether the entity is available for normal operations.', verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True, verbose_name='Deleted By')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique UUID v4 identifier.', primary_key=True, serialize=False, unique=True, verbose_name='Identifier')),
                ('party_type', models.CharField(choices=[('SELF', 'Patient'), ('GUARANTOR', 'Guarantor'), ('INSURANCE', 'Insurance')], max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('priority', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsibilities', to='revenue_cycle_billing.patientbillingaccount')),
                ('guarantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsibilities', to='revenue_cycle_billing.patientguarantor')),
            ],
            options={
                'db_table': 'billing_patient_responsibilities',
                'ordering': ('priority', 'effective_from'),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='patientbillingaccount',
            index=models.Index(fields=['organization', 'status'], name='pba_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='patientbillingaccount',
            index=models.Index(fields=['organization', 'patient'], name='pba_org_patient_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientbillingaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'account_number'), name='unique_patient_billing_account_number'),
        ),
        migrations.AddConstraint(
            model_name='patientbillingaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'patient'), name='unique_patient_billing_account_patient'),
        ),
        migrations.AddConstraint(
            model_name='patientbillingaccount',
            constraint=models.CheckConstraint(condition=models.Q(('opening_balance__gte', Decimal('0.00'))), name='patient_billing_opening_balance_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='patientbillingstatement',
            index=models.Index(fields=['account', 'period_end'], name='pstmt_account_end_idx'),
        ),
        migrations.AddIndex(
            model_name='patientbillingstatement',
            index=models.Index(fields=['account', 'status'], name='pstmt_account_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientbillingstatement',
            constraint=models.UniqueConstraint(fields=('account', 'statement_number'), name='unique_patient_statement_number'),
        ),
        migrations.AddConstraint(
            model_name='patientbillingstatement',
            constraint=models.UniqueConstraint(fields=('account', 'period_start', 'period_end'), name='unique_patient_statement_period'),
        ),
        migrations.AddConstraint(
            model_name='patientbillingstatement',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='patient_statement_valid_period'),
        ),
        migrations.AddIndex(
            model_name='patientguarantor',
            index=models.Index(fields=['organization', 'patient'], name='pguarantor_org_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='patientguarantor',
            index=models.Index(fields=['patient', 'is_primary'], name='pguarantor_patient_primary_idx'),
        ),
        migrations.AddIndex(
            model_name='patientfinancialresponsibility',
            index=models.Index(fields=['account', 'party_type'], name='presp_account_party_idx'),
        ),
        migrations.AddIndex(
            model_name='patientfinancialresponsibility',
            index=models.Index(fields=['account', 'effective_from'], name='presp_account_date_idx'),
        ),
    ]
