# Generated by Django 6.0.6 on 2026-06-26 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
        ("employees", "0001_initial"),
        ("organizations", "0003_alter_organization_code_alter_organization_phone"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["employee_code"]},
        ),
        migrations.RemoveConstraint(
            model_name="employee",
            name="unique_employee_per_organization",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="employee_id",
            new_name="employee_code",
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                fields=("organization", "employee_code"),
                name="unique_employee_code_per_organization",
            ),
        ),
    ]
