# Generated by Django 6.0.6 on 2026-07-06 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'recorded_at',
                    models.DateTimeField(
                        db_index=True,
                        help_text='Date and time the vitals were recorded.',
                    ),
                ),
                (
                    'height_cm',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Patient height in centimeters.',
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    'weight_kg',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Patient weight in kilograms.',
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    'bmi',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Calculated body mass index.',
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    'temperature',
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text='Body temperature.',
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    'temperature_unit',
                    models.CharField(
                        choices=[('celsius', 'Celsius'), ('fahrenheit', 'Fahrenheit')],
                        db_index=True,
                        default='celsius',
                        help_text='Temperature measurement unit.',
                        max_length=20,
                    ),
                ),
                (
                    'pulse',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text='Heart rate in beats per minute.',
                        null=True,
                    ),
                ),
                (
                    'respiratory_rate',
                    models.PositiveSmallIntegerField(
                        blank=True, help_text='Respiratory rate per minute.', null=True
                    ),
                ),
                (
                    'systolic_bp',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text='Systolic blood pressure (mmHg).',
                        null=True,
                    ),
                ),
                (
                    'diastolic_bp',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text='Diastolic blood pressure (mmHg).',
                        null=True,
                    ),
                ),
                (
                    'oxygen_saturation',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text='Oxygen saturation percentage (SpO₂).',
                        null=True,
                    ),
                ),
                (
                    'pain_score',
                    models.PositiveSmallIntegerField(
                        blank=True, help_text='Pain score (0–10).', null=True
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('preliminary', 'Preliminary'),
                            ('final', 'Final'),
                            ('amended', 'Amended'),
                            ('cancelled', 'Cancelled'),
                        ],
                        db_index=True,
                        default='final',
                        help_text='Current status of the vital record.',
                        max_length=20,
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True, help_text='Additional clinical notes.'
                    ),
                ),
                (
                    'encounter',
                    models.ForeignKey(
                        help_text='Encounter during which vitals were recorded.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vitals',
                        to='encounters.encounter',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns this vital record.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vitals',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        help_text='Patient associated with this vital record.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vitals',
                        to='patients.patient',
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        help_text='Provider who recorded the vitals.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vitals',
                        to='providers.provider',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Vital',
                'verbose_name_plural': 'Vitals',
                'db_table': 'vitals',
                'ordering': ('-recorded_at',),
                'indexes': [
                    models.Index(
                        fields=['organization'], name='vitals_organiz_40f244_idx'
                    ),
                    models.Index(fields=['patient'], name='vitals_patient_da51d6_idx'),
                    models.Index(fields=['provider'], name='vitals_provide_d80da3_idx'),
                    models.Index(
                        fields=['encounter'], name='vitals_encount_d02c8a_idx'
                    ),
                    models.Index(
                        fields=['recorded_at'], name='vitals_recorde_5a3a14_idx'
                    ),
                    models.Index(fields=['status'], name='vitals_status_ef2794_idx'),
                    models.Index(
                        fields=['patient', 'recorded_at'],
                        name='vitals_patient_737668_idx',
                    ),
                    models.Index(
                        fields=['encounter', 'recorded_at'],
                        name='vitals_encount_043956_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('encounter', 'recorded_at'),
                        name='unique_vital_record_per_encounter_time',
                    )
                ],
            },
        ),
    ]
