# Generated by Django 6.0.6 on 2026-09-21 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_emergency_contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emergencycontact',
            name='idx_ec_org_patient',
        ),
        migrations.RemoveIndex(
            model_name='emergencycontact',
            name='idx_ec_org_deleted',
        ),
        migrations.RemoveIndex(
            model_name='emergencycontact',
            name='idx_ec_patient_priority',
        ),
        migrations.RemoveIndex(
            model_name='emergencycontact',
            name='idx_ec_patient_status',
        ),
        migrations.RemoveIndex(
            model_name='emergencycontact',
            name='idx_ec_status',
        ),
        migrations.RemoveIndex(
            model_name='emergencycontact',
            name='idx_ec_relationship',
        ),
        migrations.RemoveIndex(
            model_name='emergencycontact',
            name='idx_ec_primary',
        ),
        migrations.RemoveIndex(
            model_name='emergencycontact',
            name='idx_ec_verified',
        ),
        migrations.RemoveConstraint(
            model_name='emergencycontact',
            name='uniq_org_emergency_contact_number',
        ),
        migrations.RemoveConstraint(
            model_name='emergencycontact',
            name='uniq_patient_priority_order',
        ),
        migrations.RemoveConstraint(
            model_name='emergencycontact',
            name='uniq_primary_patient_emergency_contact',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
    ]
