import { mutationOptions } from '@tanstack/react-query';
import { apiClient } from '@/core/api';
import type { CreateDocumentPayload, CreateDocumentVersionPayload, Document, DocumentVersion, UpdateDocumentPayload } from '../domain';
import { documentEndpoints } from './endpoints';

type DocumentDto = { id:string; title:string; document_type:string; status:string; access_level:string; original_filename:string; mime_type:string; file_size:number; storage_key?:string|null; checksum?:string|null; url?:string|null; download_url?:string|null; metadata?:Record<string,unknown>|null; ai_metadata?:Record<string,unknown>|null; created_at:string; updated_at:string };
type VersionDto = { id:string; document_id?:string; version_number:number; status:string; storage_key?:string|null; original_filename:string; mime_type:string; file_size:number; checksum?:string|null; created_at:string; updated_at:string };
const mapDocument = (d:DocumentDto):Document => ({id:d.id,title:d.title,documentType:d.document_type,status:d.status,accessLevel:d.access_level,originalFilename:d.original_filename,mimeType:d.mime_type,fileSize:d.file_size,storageKey:d.storage_key??null,checksum:d.checksum??null,downloadUrl:d.download_url??d.url??null,metadata:d.metadata??{},aiMetadata:d.ai_metadata??{},createdAt:d.created_at,updatedAt:d.updated_at});
const mapVersion = (d:VersionDto,id:string):DocumentVersion => ({id:d.id,documentId:d.document_id??id,versionNumber:d.version_number,status:d.status,storageKey:d.storage_key??null,originalFilename:d.original_filename,mimeType:d.mime_type,fileSize:d.file_size,checksum:d.checksum??null,createdAt:d.created_at,updatedAt:d.updated_at});
async function createDocument(p:CreateDocumentPayload){const r=await apiClient.post<DocumentDto>(documentEndpoints.collection,{title:p.title,document_type:p.documentType,access_level:p.accessLevel,metadata:p.metadata??{},ai_metadata:p.aiMetadata??{}});return mapDocument(r.data);}
async function uploadDocument(p:CreateDocumentPayload & {file:File}){const form=new FormData();form.append('file',p.file);form.append('title',p.title);form.append('document_type',p.documentType);form.append('access_level',p.accessLevel??'private');const r=await apiClient.post<DocumentDto,FormData>(documentEndpoints.upload,form);return mapDocument(r.data);}
async function updateDocument(a:{id:string;payload:UpdateDocumentPayload}){const p=a.payload;const r=await apiClient.patch<DocumentDto>(documentEndpoints.byId(a.id),{...(p.title!==undefined&&{title:p.title}),...(p.documentType!==undefined&&{document_type:p.documentType}),...(p.accessLevel!==undefined&&{access_level:p.accessLevel}),...(p.metadata!==undefined&&{metadata:p.metadata}),...(p.aiMetadata!==undefined&&{ai_metadata:p.aiMetadata})});return mapDocument(r.data);}
async function deleteDocument(id:string){await apiClient.delete(documentEndpoints.byId(id));}
async function createVersion(a:{documentId:string;payload:CreateDocumentVersionPayload}){const form=new FormData();form.append('file',a.payload.file);const r=await apiClient.post<VersionDto,FormData>(documentEndpoints.versions(a.documentId),form);return mapVersion(r.data,a.documentId);}
export const documentMutations = { create:()=>mutationOptions({mutationFn:createDocument}), upload:()=>mutationOptions({mutationFn:uploadDocument}), update:()=>mutationOptions({mutationFn:updateDocument}), delete:()=>mutationOptions({mutationFn:deleteDocument}), createVersion:()=>mutationOptions({mutationFn:createVersion}) } as const;
