# Generated by Django 6.0.6 on 2026-07-28 10:24

import apps.core.models.managers
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('encounters', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTemplate',
            fields=[
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('name', models.CharField(help_text='Template name.', max_length=255)),
                (
                    'template_type',
                    models.CharField(
                        choices=[
                            ('soap', 'SOAP'),
                            ('progress_note', 'Progress Note'),
                            ('discharge_summary', 'Discharge Summary'),
                            ('consultation', 'Consultation'),
                            ('procedure_note', 'Procedure Note'),
                            ('operative_note', 'Operative Note'),
                            ('delivery_note', 'Delivery Note'),
                            ('emergency_note', 'Emergency Note'),
                            ('other', 'Other'),
                        ],
                        help_text='Type of note template.',
                        max_length=50,
                    ),
                ),
                (
                    'content',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Template structure with placeholders.',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Whether the template is currently active.',
                    ),
                ),
                (
                    'is_system_template',
                    models.BooleanField(
                        default=False,
                        help_text='Whether this is a system-provided template.',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Note Template',
                'verbose_name_plural': 'Note Templates',
                'db_table': 'note_templates',
                'ordering': ('name',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'note_type',
                    models.CharField(
                        choices=[
                            ('soap', 'SOAP Note'),
                            ('progress_note', 'Progress Note'),
                            ('discharge_summary', 'Discharge Summary'),
                            ('consultation', 'Consultation Note'),
                            ('procedure_note', 'Procedure Note'),
                            ('operative_note', 'Operative Note'),
                            ('delivery_note', 'Delivery Note'),
                            ('emergency_note', 'Emergency Note'),
                            ('other', 'Other'),
                        ],
                        default='soap',
                        help_text='Type of clinical note.',
                        max_length=50,
                    ),
                ),
                ('title', models.CharField(help_text='Note title.', max_length=255)),
                (
                    'content',
                    models.JSONField(
                        blank=True, default=dict, help_text='Structured note content.'
                    ),
                ),
                (
                    'raw_text',
                    models.TextField(
                        blank=True,
                        help_text='Raw text transcription or voice-to-text content.',
                    ),
                ),
                (
                    'is_amended',
                    models.BooleanField(
                        default=False, help_text='Whether the note has been amended.'
                    ),
                ),
                (
                    'amendment_reason',
                    models.TextField(
                        blank=True, help_text='Reason for amending the note.'
                    ),
                ),
                (
                    'signed_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Timestamp when the note was signed.',
                        null=True,
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        help_text='Employee who created the note.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='created_clinical_notes',
                        to='employees.employee',
                    ),
                ),
                (
                    'encounter',
                    models.ForeignKey(
                        blank=True,
                        help_text='Encounter associated with this note.',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='clinical_note_records',
                        to='encounters.encounter',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns the note.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='clinical_notes',
                        to='organizations.organization',
                    ),
                ),
                (
                    'original_note',
                    models.ForeignKey(
                        blank=True,
                        help_text='Original note if this is an amendment.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='amendments',
                        to='notes.clinicalnote',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Clinical Note',
                'verbose_name_plural': 'Clinical Notes',
                'db_table': 'clinical_notes',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
    ]
