# Generated by Django 6.0.6 on 2026-09-15 07:58

import apps.core.models.managers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0002_alter_encounter_options_and_more'),
        ('organizations', '0001_initial'),
        ('patient_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'note_id',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    'note_type',
                    models.CharField(
                        choices=[
                            ('soap', 'SOAP'),
                            ('progress', 'Progress'),
                            ('consultation', 'Consultation'),
                            ('discharge', 'Discharge'),
                            ('procedure', 'Procedure'),
                            ('telemedicine', 'Telemedicine'),
                            ('nursing', 'Nursing'),
                            ('other', 'Other'),
                        ],
                        default='soap',
                        max_length=32,
                    ),
                ),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('manual', 'Manual'),
                            ('transcription', 'Transcription'),
                            ('telemedicine', 'Telemedicine'),
                            ('imported', 'Imported'),
                        ],
                        default='manual',
                        max_length=24,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('in_review', 'In Review'),
                            ('signed', 'Signed'),
                            ('amended', 'Amended'),
                            ('cancelled', 'Cancelled'),
                        ],
                        db_index=True,
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('structured_content', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('transcription_job_id', models.UUIDField(blank=True, null=True)),
                ('telemedicine_session_id', models.UUIDField(blank=True, null=True)),
                ('document_reference', models.CharField(blank=True, max_length=512)),
                ('storage_reference', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='authored_clinical_notes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'encounter',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='note_records',
                        to='encounters.encounter',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='clinical_notes',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='clinical_notes',
                        to='patient_core.patient',
                    ),
                ),
                (
                    'signed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='signed_clinical_notes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'clinical_notes',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNoteAmendment',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'amendment_id',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('submitted', 'Submitted'),
                            ('accepted', 'Accepted'),
                            ('rejected', 'Rejected'),
                        ],
                        db_index=True,
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('reason', models.TextField()),
                ('proposed_body', models.TextField()),
                (
                    'proposed_structured_content',
                    models.JSONField(blank=True, default=dict),
                ),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'note',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='amendments',
                        to='notes.clinicalnote',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='clinical_note_amendments',
                        to='organizations.organization',
                    ),
                ),
                (
                    'requested_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='requested_note_amendments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='reviewed_note_amendments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'clinical_note_amendments',
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNoteTemplate',
            fields=[
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('name', models.CharField(max_length=150)),
                (
                    'note_type',
                    models.CharField(
                        choices=[
                            ('soap', 'SOAP'),
                            ('progress', 'Progress'),
                            ('consultation', 'Consultation'),
                            ('discharge', 'Discharge'),
                            ('procedure', 'Procedure'),
                            ('telemedicine', 'Telemedicine'),
                            ('nursing', 'Nursing'),
                            ('other', 'Other'),
                        ],
                        default='soap',
                        max_length=32,
                    ),
                ),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('default_content', models.JSONField(blank=True, default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='clinical_note_templates',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'clinical_note_templates',
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNoteVersion',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('structured_content', models.JSONField(blank=True, default=dict)),
                ('change_reason', models.TextField(blank=True)),
                ('is_signed_snapshot', models.BooleanField(default=False)),
                (
                    'changed_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='clinical_note_versions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'note',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='versions',
                        to='notes.clinicalnote',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='clinical_note_versions',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'clinical_note_versions',
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='NoteIdempotencyKey',
            fields=[
                (
                    'key_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('scope', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='clinical_note_idempotency_keys',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'clinical_note_idempotency_keys',
            },
        ),
        migrations.CreateModel(
            name='NoteOutboxEvent',
            fields=[
                (
                    'event_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('event_type', models.CharField(max_length=120)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.CharField(max_length=160)),
                ('payload', models.JSONField(blank=True, default=dict)),
                (
                    'status',
                    models.CharField(db_index=True, default='pending', max_length=20),
                ),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='clinical_note_outbox_events',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'clinical_note_outbox_events',
            },
        ),
        migrations.CreateModel(
            name='NoteTransition',
            fields=[
                (
                    'transition_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('version', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'actor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='clinical_note_transitions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'note',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='transition_ledger',
                        to='notes.clinicalnote',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='clinical_note_transitions',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'clinical_note_transitions',
            },
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(
                fields=['organization', 'status'], name='clin_note_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(
                fields=['patient', 'created_at'], name='clin_note_patient_created_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(
                fields=['encounter', 'created_at'], name='clin_note_enc_created_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(
                fields=['organization', 'note_type'], name='clin_note_org_type_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='clinicalnoteamendment',
            index=models.Index(
                fields=['organization', 'status'], name='clin_note_am_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='clinicalnotetemplate',
            index=models.Index(
                fields=['organization', 'note_type', 'is_active'],
                name='clin_note_tpl_lookup_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='clinicalnotetemplate',
            constraint=models.UniqueConstraint(
                fields=('organization', 'name'), name='clin_note_tpl_org_name_uniq'
            ),
        ),
        migrations.AddIndex(
            model_name='clinicalnoteversion',
            index=models.Index(
                fields=['organization', 'note'], name='clin_note_ver_org_note_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='clinicalnoteversion',
            constraint=models.UniqueConstraint(
                fields=('note', 'version_number'), name='clin_note_ver_note_num_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='noteidempotencykey',
            constraint=models.UniqueConstraint(
                fields=('organization', 'scope', 'idempotency_key'),
                name='clin_note_idem_org_scope_key_uniq',
            ),
        ),
        migrations.AddIndex(
            model_name='noteoutboxevent',
            index=models.Index(
                fields=['organization', 'status'], name='clin_note_out_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='noteoutboxevent',
            index=models.Index(
                fields=['status', 'available_at'], name='clin_note_out_status_time_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='notetransition',
            index=models.Index(
                fields=['organization', 'note', 'created_at'],
                name='clin_note_tr_org_note_idx',
            ),
        ),
    ]
