# Generated by Django 6.0.6 on 2026-07-28 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('notes', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='patient',
            field=models.ForeignKey(
                help_text='Patient associated with this note.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='clinical_notes',
                to='patients.patient',
            ),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='signed_by',
            field=models.ForeignKey(
                blank=True,
                help_text='Employee who signed the note.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='signed_notes',
                to='employees.employee',
            ),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization that owns the template.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='note_templates',
                to='organizations.organization',
            ),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(
                fields=['patient', 'created_at'], name='clin_note_pat_created_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(
                fields=['encounter', 'created_at'], name='clin_note_enc_created_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(
                fields=['organization', 'note_type'], name='clinical_note_org_type_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(
                fields=['created_by', 'created_at'], name='clin_note_auth_created_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='notetemplate',
            index=models.Index(
                fields=['organization', 'template_type'], name='template_org_type_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='notetemplate',
            index=models.Index(
                fields=['organization', 'is_active'], name='template_org_active_idx'
            ),
        ),
    ]
