# Generated by Django 6.0.6 on 2026-07-28 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('team_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='teams',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TeamDepartmentAssignment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'is_primary',
                    models.BooleanField(
                        default=False,
                        help_text='Indicates the primary department for this team assignment.',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether this assignment is currently active.',
                    ),
                ),
                (
                    'department',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='team_assignments',
                        to='departments.department',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='department_assignments',
                        to='teams.team',
                    ),
                ),
            ],
            options={
                'ordering': ('team', 'department'),
            },
        ),
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                (
                    'is_lead',
                    models.BooleanField(
                        default=False,
                        help_text='Indicates whether this role represents a team leadership role.',
                    ),
                ),
                (
                    'is_system',
                    models.BooleanField(
                        default=False,
                        help_text='System roles are predefined and managed by DatavionOS.',
                    ),
                ),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                (
                    'team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='roles',
                        to='teams.team',
                    ),
                ),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                (
                    'team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='members',
                        to='teams.team',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='team_memberships',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'role',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='members',
                        to='teams.teamrole',
                    ),
                ),
            ],
            options={
                'ordering': ('team', 'user'),
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['organization'], name='idx_team_org'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(
                fields=['organization', 'is_active'], name='idx_team_org_active'
            ),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(
                fields=('organization', 'code'), name='uq_team_org_code'
            ),
        ),
        migrations.AddIndex(
            model_name='teamdepartmentassignment',
            index=models.Index(
                fields=['team', 'is_active'], name='idx_team_department_active'
            ),
        ),
        migrations.AddIndex(
            model_name='teamdepartmentassignment',
            index=models.Index(
                fields=['department', 'is_active'], name='idx_department_team_active'
            ),
        ),
        migrations.AddConstraint(
            model_name='teamdepartmentassignment',
            constraint=models.UniqueConstraint(
                fields=('team', 'department'), name='uq_team_department_assignment'
            ),
        ),
        migrations.AddIndex(
            model_name='teamrole',
            index=models.Index(
                fields=['team', 'is_active'], name='idx_team_role_active'
            ),
        ),
        migrations.AddIndex(
            model_name='teamrole',
            index=models.Index(fields=['team', 'is_lead'], name='idx_team_role_lead'),
        ),
        migrations.AddConstraint(
            model_name='teamrole',
            constraint=models.UniqueConstraint(
                fields=('team', 'code'), name='uq_team_role_code'
            ),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(
                fields=['team', 'status'], name='idx_team_member_status'
            ),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(
                fields=('team', 'user'), name='uq_team_user'
            ),
        ),
    ]
