# Generated by Django 6.0.6 on 2026-07-27 06:42

import apps.core.models.managers
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('notes', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'provider',
                    models.CharField(
                        choices=[
                            ('openai_whisper', 'OpenAI Whisper'),
                            ('local', 'Local'),
                        ],
                        default='openai_whisper',
                        max_length=30,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('processing', 'Processing'),
                            ('completed', 'Completed'),
                            ('failed', 'Failed'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                (
                    'audio_path',
                    models.CharField(
                        help_text='Storage path or URL of the source audio.',
                        max_length=512,
                    ),
                ),
                (
                    'transcript',
                    models.TextField(
                        blank=True,
                        help_text='Verbatim transcript produced by the provider.',
                    ),
                ),
                ('language', models.CharField(blank=True, default='en', max_length=10)),
                (
                    'error',
                    models.TextField(
                        blank=True, help_text='Error detail if the job failed.'
                    ),
                ),
                (
                    'encounter',
                    models.ForeignKey(
                        blank=True,
                        help_text='Encounter the audio relates to.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='transcription_jobs',
                        to='encounters.encounter',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Owning organization.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='transcription_jobs',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Transcription Job',
                'verbose_name_plural': 'Transcription Jobs',
                'db_table': 'transcription_jobs',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedNote',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'draft_text',
                    models.TextField(
                        blank=True,
                        help_text='AI-generated structured draft before human review.',
                    ),
                ),
                (
                    'review_required',
                    models.BooleanField(
                        default=True,
                        help_text='Whether a clinician must review before signing.',
                    ),
                ),
                (
                    'note',
                    models.OneToOneField(
                        blank=True,
                        help_text='Persisted clinical note, once reviewed.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='generated_from_transcription',
                        to='notes.clinicalnote',
                    ),
                ),
                (
                    'job',
                    models.OneToOneField(
                        help_text='Source transcription job.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='generated_note',
                        to='transcription.transcriptionjob',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Generated Note',
                'verbose_name_plural': 'Generated Notes',
                'db_table': 'transcription_generated_notes',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
    ]
