# Generated by Django 6.0.6 on 2026-09-15 04:38

import apps.core.models.managers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0002_alter_encounter_options_and_more'),
        ('notes', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patient_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTranscriptionSession',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'session_id',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('created', 'Created'),
                            ('ready', 'Ready'),
                            ('connecting', 'Connecting'),
                            ('recording', 'Recording'),
                            ('paused', 'Paused'),
                            ('reconnecting', 'Reconnecting'),
                            ('finalizing', 'Finalizing'),
                            ('completed', 'Completed'),
                            ('failed', 'Failed'),
                            ('cancelled', 'Cancelled'),
                        ],
                        db_index=True,
                        default='created',
                        max_length=24,
                    ),
                ),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('browser', 'Browser'),
                            ('device_platform', 'Device Platform'),
                            ('telemedicine', 'Telemedicine'),
                            ('dictation', 'Dictation'),
                        ],
                        default='browser',
                        max_length=30,
                    ),
                ),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('telemedicine_session_id', models.UUIDField(blank=True, null=True)),
                ('appointment_id', models.UUIDField(blank=True, null=True)),
                (
                    'audio_mime_type',
                    models.CharField(default='audio/webm', max_length=100),
                ),
                ('language', models.CharField(default='en', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('sequence_number', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_audio_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='created_live_transcription_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'encounter',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='live_transcription_sessions',
                        to='encounters.encounter',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='live_transcription_sessions',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='live_transcription_sessions',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'db_table': 'transcription_live_sessions',
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='LiveTranscriptSegment',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'segment_id',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ('sequence', models.PositiveBigIntegerField()),
                (
                    'kind',
                    models.CharField(
                        choices=[('partial', 'Partial'), ('final', 'Final')],
                        max_length=16,
                    ),
                ),
                ('speaker_label', models.CharField(blank=True, max_length=120)),
                ('text', models.TextField()),
                ('start_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('end_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    'confidence',
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=6, null=True
                    ),
                ),
                ('provider_segment_id', models.CharField(blank=True, max_length=255)),
                ('is_current', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='segments',
                        to='transcription.livetranscriptionsession',
                    ),
                ),
            ],
            options={
                'db_table': 'transcription_live_segments',
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptionIdempotencyKey',
            fields=[
                (
                    'key_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('scope', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('request_hash', models.CharField(max_length=128)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='transcription_idempotency_keys',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'transcription_idempotency_keys',
            },
        ),
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('idempotency_key', models.CharField(max_length=128)),
                (
                    'source_type',
                    models.CharField(
                        choices=[
                            ('upload', 'Upload'),
                            ('telemedicine', 'Telemedicine'),
                            ('dictation', 'Dictation'),
                            ('external', 'External'),
                        ],
                        default='upload',
                        max_length=20,
                    ),
                ),
                (
                    'provider',
                    models.CharField(
                        choices=[
                            ('openai_whisper', 'OpenAI Whisper'),
                            ('azure_speech', 'Azure Speech'),
                            ('google_speech', 'Google Speech'),
                            ('aws_transcribe', 'AWS Transcribe'),
                            ('custom', 'Custom'),
                        ],
                        default='openai_whisper',
                        max_length=40,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('created', 'Created'),
                            ('queued', 'Queued'),
                            ('processing', 'Processing'),
                            ('completed', 'Completed'),
                            ('failed', 'Failed'),
                            ('cancelled', 'Cancelled'),
                        ],
                        db_index=True,
                        default='created',
                        max_length=20,
                    ),
                ),
                ('audio_uri', models.URLField(max_length=2048)),
                ('audio_mime_type', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(default='en', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('transcript_text', models.TextField(blank=True)),
                ('transcript_json', models.JSONField(blank=True, default=dict)),
                ('speaker_count', models.PositiveIntegerField(blank=True, null=True)),
                (
                    'duration_seconds',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='created_transcription_jobs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'encounter',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='transcription_jobs',
                        to='encounters.encounter',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='transcription_jobs',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='transcription_jobs',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'db_table': 'transcription_jobs',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedNote',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('note_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('review', 'Review'),
                            ('signed', 'Signed'),
                            ('rejected', 'Rejected'),
                        ],
                        db_index=True,
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('note_type', models.CharField(default='soap', max_length=50)),
                ('draft_text', models.TextField()),
                ('structured_content', models.JSONField(blank=True, default=dict)),
                ('generated_by_provider', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                (
                    'clinical_note',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='generated_from_transcription',
                        to='notes.clinicalnote',
                    ),
                ),
                (
                    'encounter',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='generated_transcription_notes',
                        to='encounters.encounter',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='generated_transcription_notes',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='generated_transcription_notes',
                        to='patient_core.patient',
                    ),
                ),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='reviewed_transcription_notes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'job',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='generated_note',
                        to='transcription.transcriptionjob',
                    ),
                ),
            ],
            options={
                'db_table': 'transcription_generated_notes',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptionOutboxEvent',
            fields=[
                (
                    'event_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('event_type', models.CharField(max_length=120)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.CharField(max_length=160)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='transcription_outbox_events',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'transcription_outbox_events',
            },
        ),
        migrations.AddIndex(
            model_name='livetranscriptionsession',
            index=models.Index(
                fields=['organization', 'status'], name='trans_live_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='livetranscriptionsession',
            index=models.Index(
                fields=['patient', 'created_at'], name='trans_live_pat_created_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='livetranscriptionsession',
            index=models.Index(
                fields=['device_id', 'status'], name='trans_live_device_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='livetranscriptionsession',
            index=models.Index(
                fields=['telemedicine_session_id', 'status'],
                name='trans_live_tm_status_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='livetranscriptionsession',
            constraint=models.UniqueConstraint(
                fields=('organization', 'session_id'),
                name='trans_live_org_session_uniq',
            ),
        ),
        migrations.AddIndex(
            model_name='livetranscriptsegment',
            index=models.Index(
                fields=['session', 'kind'], name='trans_live_seg_kind_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='livetranscriptsegment',
            index=models.Index(
                fields=['session', 'sequence'], name='trans_live_seg_seq_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='livetranscriptsegment',
            constraint=models.UniqueConstraint(
                fields=('session', 'sequence'), name='trans_live_seg_seq_uniq'
            ),
        ),
        migrations.AddIndex(
            model_name='transcriptionidempotencykey',
            index=models.Index(
                fields=['organization', 'scope'], name='trans_idem_org_scope_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='transcriptionidempotencykey',
            constraint=models.UniqueConstraint(
                fields=('organization', 'scope', 'idempotency_key'),
                name='trans_idem_org_scope_key',
            ),
        ),
        migrations.AddIndex(
            model_name='transcriptionjob',
            index=models.Index(
                fields=['organization', 'status'], name='trans_job_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='transcriptionjob',
            index=models.Index(
                fields=['patient', 'created_at'], name='trans_job_pat_created_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='transcriptionjob',
            index=models.Index(
                fields=['encounter', 'created_at'], name='trans_job_enc_created_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='transcriptionjob',
            constraint=models.UniqueConstraint(
                fields=('job_id',), name='trans_job_jobid_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='transcriptionjob',
            constraint=models.UniqueConstraint(
                fields=('organization', 'idempotency_key'),
                name='trans_job_org_idem_uniq',
            ),
        ),
        migrations.AddIndex(
            model_name='generatednote',
            index=models.Index(
                fields=['organization', 'status'], name='trans_note_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='generatednote',
            index=models.Index(
                fields=['patient', 'created_at'], name='trans_note_pat_created_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='generatednote',
            constraint=models.UniqueConstraint(
                fields=('note_id',), name='trans_note_noteid_uniq'
            ),
        ),
        migrations.AddIndex(
            model_name='transcriptionoutboxevent',
            index=models.Index(
                fields=['organization', 'status'], name='trans_out_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='transcriptionoutboxevent',
            index=models.Index(
                fields=['status', 'available_at'], name='trans_out_status_time_idx'
            ),
        ),
    ]
