# Generated by Django 6.0.6 on 2026-10-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_livetranscriptionsession_websocket_ticket_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionjob',
            name='audio_uri',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='transcriptionjob',
            name='source_type',
            field=models.CharField(choices=[('upload', 'Upload'), ('live', 'Live Recording'), ('telemedicine', 'Telemedicine'), ('dictation', 'Dictation'), ('external', 'External')], default='upload', max_length=20),
        ),
    ]
