# Generated by Django 6.0.6 on 2026-07-28 06:19

import apps.common.validators.fields.phone
import apps.core.models.managers
import apps.platform.organizations.constants.organization_branding
import apps.platform.organizations.constants.organization_hierarchy
import apps.platform.organizations.managers.organization
import apps.platform.organizations.managers.organization_branding
import apps.platform.organizations.managers.organization_hierarchy
import apps.platform.organizations.validators.organization
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Legal registered organization name.',
                        max_length=255,
                        verbose_name='Legal Name',
                    ),
                ),
                (
                    'display_name',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='Friendly name displayed throughout the platform.',
                        max_length=255,
                        verbose_name='Display Name',
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        help_text='Unique organization code within the tenant.',
                        max_length=20,
                        validators=[
                            apps.platform.organizations.validators.organization.validate_organization_code
                        ],
                        verbose_name='Organization Code',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True,
                        help_text='URL-friendly unique slug within the tenant.',
                        max_length=100,
                        verbose_name='Slug',
                    ),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('healthcare_provider', 'Healthcare Provider'),
                            ('diagnostics', 'Diagnostics'),
                            ('pharmacy', 'Pharmacy'),
                            ('emergency', 'Emergency Services'),
                            ('insurance', 'Insurance'),
                            ('research', 'Research & Education'),
                            ('public_health', 'Public Health'),
                            ('enterprise', 'Enterprise'),
                        ],
                        db_index=True,
                        default='healthcare_provider',
                        max_length=50,
                        verbose_name='Category',
                    ),
                ),
                (
                    'organization_type',
                    models.CharField(
                        choices=[
                            ('hospital', 'Hospital'),
                            ('clinic', 'Clinic'),
                            ('dental_clinic', 'Dental Clinic'),
                            ('eye_clinic', 'Eye Clinic'),
                            ('ent_clinic', 'ENT Clinic'),
                            ('cardiology_clinic', 'Cardiology Clinic'),
                            ('neurology_clinic', 'Neurology Clinic'),
                            ('orthopedic_clinic', 'Orthopedic Clinic'),
                            ('pediatric_clinic', 'Pediatric Clinic'),
                            ('gynecology_clinic', 'Gynecology Clinic'),
                            ('dermatology_clinic', 'Dermatology Clinic'),
                            ('psychiatry_clinic', 'Psychiatry Clinic'),
                            ('oncology_center', 'Oncology Center'),
                            ('physiotherapy_center', 'Physiotherapy Center'),
                            ('rehabilitation_center', 'Rehabilitation Center'),
                            ('dialysis_center', 'Dialysis Center'),
                            ('fertility_center', 'Fertility Center'),
                            ('home_healthcare', 'Home Healthcare'),
                            ('telemedicine', 'Telemedicine Provider'),
                            ('nursing_home', 'Nursing Home'),
                            ('hospice', 'Hospice'),
                            ('assisted_living', 'Assisted Living Facility'),
                            ('wellness_center', 'Wellness Center'),
                            ('laboratory', 'Laboratory'),
                            ('diagnostic_center', 'Diagnostic Center'),
                            ('radiology_center', 'Radiology Center'),
                            ('imaging_center', 'Imaging Center'),
                            ('pathology_lab', 'Pathology Laboratory'),
                            ('blood_bank', 'Blood Bank'),
                            ('retail_pharmacy', 'Retail Pharmacy'),
                            ('hospital_pharmacy', 'Hospital Pharmacy'),
                            ('online_pharmacy', 'Online Pharmacy'),
                            ('wholesale_pharmacy', 'Wholesale Pharmacy'),
                            ('ambulance_service', 'Ambulance Service'),
                            ('trauma_center', 'Trauma Center'),
                            ('emergency_center', 'Emergency Center'),
                            ('insurance_company', 'Insurance Company'),
                            ('tpa', 'Third Party Administrator'),
                            ('medical_college', 'Medical College'),
                            ('medical_university', 'Medical University'),
                            ('research_institute', 'Research Institute'),
                            ('clinical_trial_center', 'Clinical Trial Center'),
                            ('government_hospital', 'Government Hospital'),
                            ('public_health_center', 'Public Health Center'),
                            ('ngo', 'NGO'),
                            ('corporate', 'Corporate'),
                            ('occupational_health', 'Occupational Health'),
                            ('healthcare_network', 'Healthcare Network'),
                        ],
                        db_index=True,
                        default='hospital',
                        max_length=100,
                        verbose_name='Organization Type',
                    ),
                ),
                (
                    'size',
                    models.CharField(
                        choices=[
                            ('solo', 'Solo Practice'),
                            ('small', 'Small'),
                            ('medium', 'Medium'),
                            ('large', 'Large'),
                            ('enterprise', 'Enterprise'),
                        ],
                        default='small',
                        max_length=30,
                        verbose_name='Organization Size',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('pending_verification', 'Pending Verification'),
                            ('active', 'Active'),
                            ('inactive', 'Inactive'),
                            ('suspended', 'Suspended'),
                            ('archived', 'Archived'),
                        ],
                        db_index=True,
                        default='active',
                        max_length=50,
                        verbose_name='Status',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, verbose_name='Email'
                    ),
                ),
                (
                    'support_email',
                    models.EmailField(
                        blank=True, max_length=254, verbose_name='Support Email'
                    ),
                ),
                (
                    'phone',
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            apps.common.validators.fields.phone.validate_phone_number
                        ],
                        verbose_name='Phone',
                    ),
                ),
                (
                    'website',
                    models.URLField(blank=True, max_length=500, verbose_name='Website'),
                ),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                (
                    'city',
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name='City'
                    ),
                ),
                (
                    'state',
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name='State'
                    ),
                ),
                (
                    'country',
                    models.CharField(
                        db_index=True,
                        default='India',
                        max_length=100,
                        verbose_name='Country',
                    ),
                ),
                (
                    'postal_code',
                    models.CharField(
                        blank=True, max_length=20, verbose_name='Postal Code'
                    ),
                ),
                (
                    'timezone',
                    models.CharField(
                        default='Asia/Kolkata', max_length=100, verbose_name='Timezone'
                    ),
                ),
                (
                    'registration_number',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Registration Number'
                    ),
                ),
                (
                    'tax_number',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Tax Number'
                    ),
                ),
                (
                    'license_number',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='License Number'
                    ),
                ),
                (
                    'accreditation',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Accreditation'
                    ),
                ),
                (
                    'verification_status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('verified', 'Verified'),
                            ('rejected', 'Rejected'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=30,
                        verbose_name='Verification Status',
                    ),
                ),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Description'),
                ),
                (
                    'is_demo',
                    models.BooleanField(
                        default=False,
                        help_text='Indicates whether this is a demo organization.',
                        verbose_name='Demo Organization',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        help_text='Tenant that owns this organization.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='organizations',
                        to='tenancy.tenant',
                        verbose_name='Tenant',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ('name',),
            },
            managers=[
                (
                    'objects',
                    apps.platform.organizations.managers.organization.OrganizationManager(),
                ),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationBranding',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'logo',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='organizations/branding/logos/',
                        verbose_name='Logo',
                    ),
                ),
                (
                    'favicon',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='organizations/branding/favicons/',
                        verbose_name='Favicon',
                    ),
                ),
                (
                    'primary_color',
                    models.CharField(
                        default='#1A73E8',
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Enter a valid HEX color value.',
                                regex='^#[0-9A-Fa-f]{6}$',
                            )
                        ],
                        verbose_name='Primary color',
                    ),
                ),
                (
                    'font_family',
                    models.CharField(
                        default='Inter', max_length=100, verbose_name='Font family'
                    ),
                ),
                (
                    'theme_mode',
                    models.CharField(
                        choices=[
                            (
                                apps.platform.organizations.constants.organization_branding.OrganizationBrandingThemeMode[
                                    'LIGHT'
                                ],
                                'Light',
                            ),
                            (
                                apps.platform.organizations.constants.organization_branding.OrganizationBrandingThemeMode[
                                    'DARK'
                                ],
                                'Dark',
                            ),
                            (
                                apps.platform.organizations.constants.organization_branding.OrganizationBrandingThemeMode[
                                    'SYSTEM'
                                ],
                                'Follow System',
                            ),
                        ],
                        default=apps.platform.organizations.constants.organization_branding.OrganizationBrandingThemeMode[
                            'LIGHT'
                        ],
                        max_length=20,
                        verbose_name='Theme mode',
                    ),
                ),
                (
                    'custom_css',
                    models.TextField(blank=True, default='', verbose_name='Custom CSS'),
                ),
                (
                    'metadata',
                    models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
                ),
                (
                    'organization',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='branding',
                        to='organizations.organization',
                        verbose_name='Organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Organization branding',
                'verbose_name_plural': 'Organization brandings',
                'db_table': 'organization_branding',
                'ordering': ('-created_at',),
            },
            managers=[
                (
                    'objects',
                    apps.platform.organizations.managers.organization_branding.OrganizationBrandingManager(),
                ),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationDomain',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'domain',
                    models.CharField(
                        db_index=True,
                        help_text='Fully qualified domain name.',
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    'domain_type',
                    models.CharField(
                        choices=[
                            ('primary', 'Primary'),
                            ('login', 'Login'),
                            ('api', 'API'),
                            ('email', 'Email'),
                        ],
                        db_index=True,
                        default='primary',
                        help_text='Purpose of this domain.',
                        max_length=20,
                    ),
                ),
                (
                    'is_primary',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text='Whether this is the primary organization domain.',
                    ),
                ),
                (
                    'verification_status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('verified', 'Verified'),
                            ('failed', 'Failed'),
                        ],
                        db_index=True,
                        default='pending',
                        help_text='Domain verification state.',
                        max_length=20,
                    ),
                ),
                (
                    'verification_token_hash',
                    models.CharField(
                        blank=True,
                        help_text='Hashed DNS verification token.',
                        max_length=255,
                    ),
                ),
                (
                    'verified_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Timestamp when domain was verified.',
                        null=True,
                    ),
                ),
                (
                    'ssl_enabled',
                    models.BooleanField(
                        default=False, help_text='Whether SSL certificate is enabled.'
                    ),
                ),
                (
                    'ssl_expiry_date',
                    models.DateTimeField(
                        blank=True, help_text='SSL certificate expiry date.', null=True
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization owning this domain.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='domains',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Organization Domain',
                'verbose_name_plural': 'Organization Domains',
                'db_table': 'organization_domain',
                'ordering': ('domain',),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationFeature',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'feature_code',
                    models.CharField(
                        db_index=True,
                        help_text='Unique feature identifier from the DatavionOS Feature Registry.',
                        max_length=100,
                        verbose_name='Feature Code',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('enabled', 'Enabled'),
                            ('disabled', 'Disabled'),
                            ('trial', 'Trial'),
                            ('locked', 'Locked'),
                        ],
                        db_index=True,
                        default='enabled',
                        help_text='Current feature entitlement status.',
                        max_length=20,
                        verbose_name='Status',
                    ),
                ),
                (
                    'settings',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Organization-specific configuration for this feature.',
                        verbose_name='Settings',
                    ),
                ),
                (
                    'enabled_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Timestamp when the feature was enabled.',
                        null=True,
                        verbose_name='Enabled At',
                    ),
                ),
                (
                    'disabled_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Timestamp when the feature was disabled.',
                        null=True,
                        verbose_name='Disabled At',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization receiving this feature entitlement.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feature_entitlements',
                        to='organizations.organization',
                        verbose_name='Organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Organization Feature',
                'verbose_name_plural': 'Organization Features',
                'db_table': 'organization_feature',
                'ordering': ('feature_code',),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationHierarchy',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'relationship_type',
                    models.CharField(
                        choices=[
                            (
                                apps.platform.organizations.constants.organization_hierarchy.OrganizationHierarchyRelationshipType[
                                    'HOLDING'
                                ],
                                'Holding Company',
                            ),
                            (
                                apps.platform.organizations.constants.organization_hierarchy.OrganizationHierarchyRelationshipType[
                                    'SUBSIDIARY'
                                ],
                                'Subsidiary',
                            ),
                            (
                                apps.platform.organizations.constants.organization_hierarchy.OrganizationHierarchyRelationshipType[
                                    'BRANCH'
                                ],
                                'Branch',
                            ),
                            (
                                apps.platform.organizations.constants.organization_hierarchy.OrganizationHierarchyRelationshipType[
                                    'DIVISION'
                                ],
                                'Division',
                            ),
                            (
                                apps.platform.organizations.constants.organization_hierarchy.OrganizationHierarchyRelationshipType[
                                    'AFFILIATE'
                                ],
                                'Affiliate',
                            ),
                            (
                                apps.platform.organizations.constants.organization_hierarchy.OrganizationHierarchyRelationshipType[
                                    'FRANCHISE'
                                ],
                                'Franchise',
                            ),
                            (
                                apps.platform.organizations.constants.organization_hierarchy.OrganizationHierarchyRelationshipType[
                                    'PARTNER'
                                ],
                                'Partner',
                            ),
                            (
                                apps.platform.organizations.constants.organization_hierarchy.OrganizationHierarchyRelationshipType[
                                    'NETWORK'
                                ],
                                'Network',
                            ),
                            (
                                apps.platform.organizations.constants.organization_hierarchy.OrganizationHierarchyRelationshipType[
                                    'OTHER'
                                ],
                                'Other',
                            ),
                        ],
                        default=apps.platform.organizations.constants.organization_hierarchy.OrganizationHierarchyRelationshipType[
                            'SUBSIDIARY'
                        ],
                        help_text='Relationship type.',
                        max_length=32,
                        verbose_name='Relationship Type',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            (
                                apps.platform.organizations.constants.organization_hierarchy.OrganizationHierarchyStatus[
                                    'ACTIVE'
                                ],
                                'Active',
                            ),
                            (
                                apps.platform.organizations.constants.organization_hierarchy.OrganizationHierarchyStatus[
                                    'INACTIVE'
                                ],
                                'Inactive',
                            ),
                            (
                                apps.platform.organizations.constants.organization_hierarchy.OrganizationHierarchyStatus[
                                    'PENDING'
                                ],
                                'Pending',
                            ),
                            (
                                apps.platform.organizations.constants.organization_hierarchy.OrganizationHierarchyStatus[
                                    'ARCHIVED'
                                ],
                                'Archived',
                            ),
                        ],
                        default=apps.platform.organizations.constants.organization_hierarchy.OrganizationHierarchyStatus[
                            'ACTIVE'
                        ],
                        help_text='Hierarchy status.',
                        max_length=20,
                        verbose_name='Status',
                    ),
                ),
                (
                    'display_order',
                    models.PositiveIntegerField(
                        default=0,
                        help_text='Display order.',
                        verbose_name='Display Order',
                    ),
                ),
                (
                    'effective_from',
                    models.DateField(
                        blank=True,
                        help_text='Effective start date.',
                        null=True,
                        verbose_name='Effective From',
                    ),
                ),
                (
                    'effective_to',
                    models.DateField(
                        blank=True,
                        help_text='Effective end date.',
                        null=True,
                        verbose_name='Effective To',
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True, help_text='Additional notes.', verbose_name='Notes'
                    ),
                ),
                (
                    'child_organization',
                    models.ForeignKey(
                        help_text='Child organization.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='parent_hierarchies',
                        to='organizations.organization',
                        verbose_name='Child Organization',
                    ),
                ),
                (
                    'parent_organization',
                    models.ForeignKey(
                        help_text='Parent organization.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='child_hierarchies',
                        to='organizations.organization',
                        verbose_name='Parent Organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Organization Hierarchy',
                'verbose_name_plural': 'Organization Hierarchies',
                'db_table': 'organization_hierarchy',
                'ordering': (
                    'display_order',
                    'parent_organization',
                    'child_organization',
                ),
            },
            managers=[
                (
                    'objects',
                    apps.platform.organizations.managers.organization_hierarchy.OrganizationHierarchyManager(),
                ),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationModule',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'module_code',
                    models.CharField(
                        db_index=True,
                        help_text='Module identifier from DatavionOS registry.',
                        max_length=100,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('enabled', 'Enabled'),
                            ('disabled', 'Disabled'),
                            ('trial', 'Trial'),
                            ('locked', 'Locked'),
                        ],
                        db_index=True,
                        default='enabled',
                        help_text='Current module entitlement state.',
                        max_length=20,
                    ),
                ),
                (
                    'settings',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Organization-specific module configuration.',
                    ),
                ),
                (
                    'enabled_at',
                    models.DateTimeField(
                        blank=True, help_text='Module activation timestamp.', null=True
                    ),
                ),
                (
                    'disabled_at',
                    models.DateTimeField(
                        blank=True, help_text='Module disable timestamp.', null=True
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization receiving this module entitlement.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='module_entitlements',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Organization Module',
                'verbose_name_plural': 'Organization Modules',
                'db_table': 'organization_module',
                'ordering': ('module_code',),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'industry',
                    models.CharField(
                        choices=[
                            ('healthcare', 'Healthcare'),
                            ('fintech', 'FinTech'),
                            ('education', 'Education'),
                            ('other', 'Other'),
                        ],
                        db_index=True,
                        default='healthcare',
                        help_text='Industry category.',
                        max_length=50,
                        verbose_name='Industry',
                    ),
                ),
                (
                    'facility_type',
                    models.CharField(
                        choices=[
                            ('clinic', 'Clinic'),
                            ('hospital', 'Hospital'),
                            ('laboratory', 'Laboratory'),
                            ('pharmacy', 'Pharmacy'),
                            ('diagnostic_center', 'Diagnostic Center'),
                            ('insurance', 'Insurance Provider'),
                            ('corporate', 'Corporate Healthcare'),
                            ('other', 'Other'),
                        ],
                        db_index=True,
                        default='clinic',
                        help_text='Healthcare facility type.',
                        max_length=50,
                        verbose_name='Facility Type',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        help_text='Organization description.',
                        verbose_name='Description',
                    ),
                ),
                (
                    'established_year',
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='Year the organization was established.',
                        null=True,
                        verbose_name='Established Year',
                    ),
                ),
                (
                    'employee_count',
                    models.PositiveIntegerField(
                        default=0,
                        help_text='Number of employees.',
                        verbose_name='Employee Count',
                    ),
                ),
                (
                    'bed_capacity',
                    models.PositiveIntegerField(
                        default=0,
                        help_text='Hospital bed capacity.',
                        verbose_name='Bed Capacity',
                    ),
                ),
                (
                    'license_number',
                    models.CharField(
                        blank=True,
                        help_text='Primary healthcare license number.',
                        max_length=255,
                        verbose_name='License Number',
                    ),
                ),
                (
                    'metadata',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Additional organization metadata.',
                        verbose_name='Metadata',
                    ),
                ),
                (
                    'organization',
                    models.OneToOneField(
                        help_text='Organization profile.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile',
                        to='organizations.organization',
                        verbose_name='Organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Organization Profile',
                'verbose_name_plural': 'Organization Profiles',
                'db_table': 'organization_profile',
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'language',
                    models.CharField(
                        db_index=True,
                        default='en',
                        help_text='Default language for the organization.',
                        max_length=20,
                        verbose_name='Language',
                    ),
                ),
                (
                    'timezone',
                    models.CharField(
                        db_index=True,
                        default='Asia/Kolkata',
                        help_text='Default organization timezone.',
                        max_length=100,
                        verbose_name='Timezone',
                    ),
                ),
                (
                    'currency',
                    models.CharField(
                        db_index=True,
                        default='INR',
                        help_text='Default organization currency.',
                        max_length=10,
                        verbose_name='Currency',
                    ),
                ),
                (
                    'date_format',
                    models.CharField(
                        default='DD-MM-YYYY',
                        help_text='Default date display format.',
                        max_length=50,
                        verbose_name='Date Format',
                    ),
                ),
                (
                    'time_format',
                    models.CharField(
                        default='24H',
                        help_text='Default time display format.',
                        max_length=50,
                        verbose_name='Time Format',
                    ),
                ),
                (
                    'email_notifications',
                    models.BooleanField(
                        default=True,
                        help_text='Enable email notifications.',
                        verbose_name='Email Notifications',
                    ),
                ),
                (
                    'sms_notifications',
                    models.BooleanField(
                        default=True,
                        help_text='Enable SMS notifications.',
                        verbose_name='SMS Notifications',
                    ),
                ),
                (
                    'push_notifications',
                    models.BooleanField(
                        default=True,
                        help_text='Enable push notifications.',
                        verbose_name='Push Notifications',
                    ),
                ),
                (
                    'session_timeout_minutes',
                    models.PositiveIntegerField(
                        default=60,
                        help_text='User session timeout in minutes.',
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                        verbose_name='Session Timeout',
                    ),
                ),
                (
                    'mfa_required',
                    models.BooleanField(
                        default=False,
                        help_text='Require multi-factor authentication for organization users.',
                        verbose_name='MFA Required',
                    ),
                ),
                (
                    'default_dashboard',
                    models.CharField(
                        default='main',
                        help_text='Default dashboard configuration identifier.',
                        max_length=100,
                        verbose_name='Default Dashboard',
                    ),
                ),
                (
                    'organization',
                    models.OneToOneField(
                        help_text='Organization these settings belong to.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='settings',
                        to='organizations.organization',
                        verbose_name='Organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
                'db_table': 'organization_settings',
                'ordering': ('organization',),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['tenant'], name='idx_org_tenant'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(
                fields=['tenant', 'status'], name='idx_org_tenant_status'
            ),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(
                fields=['tenant', 'organization_type'], name='idx_org_tenant_type'
            ),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['category'], name='idx_org_category'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['country'], name='idx_org_country'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(
                fields=['verification_status'], name='idx_org_verification'
            ),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(
                fields=('tenant', 'name'), name='uq_org_tenant_name'
            ),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(
                fields=('tenant', 'code'), name='uq_org_tenant_code'
            ),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(
                fields=('tenant', 'slug'), name='uq_org_tenant_slug'
            ),
        ),
        migrations.AddIndex(
            model_name='organizationdomain',
            index=models.Index(
                fields=['organization', 'is_primary'], name='idx_org_primary_domain'
            ),
        ),
        migrations.AddIndex(
            model_name='organizationdomain',
            index=models.Index(
                fields=['verification_status'], name='idx_domain_verification'
            ),
        ),
        migrations.AddConstraint(
            model_name='organizationdomain',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_primary', True)),
                fields=('organization',),
                name='uq_org_primary_domain',
            ),
        ),
        migrations.AddIndex(
            model_name='organizationfeature',
            index=models.Index(
                fields=['organization', 'status'], name='idx_org_feature_status'
            ),
        ),
        migrations.AddIndex(
            model_name='organizationfeature',
            index=models.Index(fields=['feature_code'], name='idx_feature_code'),
        ),
        migrations.AddConstraint(
            model_name='organizationfeature',
            constraint=models.UniqueConstraint(
                fields=('organization', 'feature_code'), name='uq_organization_feature'
            ),
        ),
        migrations.AddIndex(
            model_name='organizationhierarchy',
            index=models.Index(
                fields=['parent_organization'], name='idx_org_hierarchy_parent'
            ),
        ),
        migrations.AddIndex(
            model_name='organizationhierarchy',
            index=models.Index(
                fields=['child_organization'], name='idx_org_hierarchy_child'
            ),
        ),
        migrations.AddIndex(
            model_name='organizationhierarchy',
            index=models.Index(
                fields=['relationship_type'], name='idx_org_hierarchy_relationship'
            ),
        ),
        migrations.AddIndex(
            model_name='organizationhierarchy',
            index=models.Index(fields=['status'], name='idx_org_hierarchy_status'),
        ),
        migrations.AddConstraint(
            model_name='organizationhierarchy',
            constraint=models.UniqueConstraint(
                fields=('parent_organization', 'child_organization'),
                name='uq_organization_hierarchy',
            ),
        ),
        migrations.AddConstraint(
            model_name='organizationhierarchy',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('parent_organization', models.F('child_organization')),
                    _negated=True,
                ),
                name='chk_organization_hierarchy_not_self',
            ),
        ),
        migrations.AddIndex(
            model_name='organizationmodule',
            index=models.Index(
                fields=['organization', 'status'], name='idx_org_module_status'
            ),
        ),
        migrations.AddIndex(
            model_name='organizationmodule',
            index=models.Index(fields=['module_code'], name='idx_module_code'),
        ),
        migrations.AddConstraint(
            model_name='organizationmodule',
            constraint=models.UniqueConstraint(
                fields=('organization', 'module_code'), name='uq_organization_module'
            ),
        ),
        migrations.AddIndex(
            model_name='organizationprofile',
            index=models.Index(fields=['industry'], name='idx_org_profile_industry'),
        ),
        migrations.AddIndex(
            model_name='organizationprofile',
            index=models.Index(
                fields=['facility_type'], name='idx_org_profile_facility'
            ),
        ),
    ]
