# Generated by Django 6.0.6 on 2026-07-14 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationHierarchy",
            fields=[
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("holding", "Holding Company"),
                            ("subsidiary", "Subsidiary"),
                            ("division", "Division"),
                            ("affiliate", "Affiliate"),
                            ("franchise", "Franchise"),
                            ("partner", "Partner"),
                            ("network", "Network"),
                            ("other", "Other"),
                        ],
                        default="subsidiary",
                        help_text="Relationship type.",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        help_text="Hierarchy status.",
                        max_length=20,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, help_text="Display order."),
                ),
                (
                    "effective_from",
                    models.DateField(
                        blank=True, help_text="Effective start date.", null=True
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, help_text="Effective end date.", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes.")),
                (
                    "child_organization",
                    models.ForeignKey(
                        help_text="Child organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_hierarchies",
                        to="organizations.organization",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_organization",
                    models.ForeignKey(
                        help_text="Parent organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_hierarchies",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Hierarchy",
                "verbose_name_plural": "Organization Hierarchies",
                "db_table": "organization_hierarchy",
                "ordering": (
                    "display_order",
                    "parent_organization",
                    "child_organization",
                ),
                "indexes": [
                    models.Index(
                        fields=["parent_organization"],
                        name="organizatio_parent__5eb085_idx",
                    ),
                    models.Index(
                        fields=["child_organization"],
                        name="organizatio_child_o_0402fb_idx",
                    ),
                    models.Index(
                        fields=["relationship_type"],
                        name="organizatio_relatio_ee255c_idx",
                    ),
                    models.Index(
                        fields=["status"], name="organizatio_status_f62fcf_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent_organization", "child_organization"),
                        name="uq_organization_hierarchy",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("parent_organization", models.F("child_organization")),
                            _negated=True,
                        ),
                        name="chk_organization_hierarchy_not_self",
                    ),
                ],
            },
        ),
    ]
