# Generated by Django 6.0.6 on 2026-07-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organizationhierarchy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationhierarchy",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("holding", "Holding Company"),
                    ("subsidiary", "Subsidiary"),
                    ("branch", "Branch"),
                    ("division", "Division"),
                    ("affiliate", "Affiliate"),
                    ("franchise", "Franchise"),
                    ("partner", "Partner"),
                    ("network", "Network"),
                    ("other", "Other"),
                ],
                default="subsidiary",
                help_text="Relationship type.",
                max_length=32,
            ),
        ),
    ]
