# Generated by Django 6.0.6 on 2026-07-31 11:49

import apps.core.models.managers
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedgerAccount',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('code', models.CharField(help_text='Account code.', max_length=30)),
                ('name', models.CharField(help_text='Account name.', max_length=150)),
                (
                    'description',
                    models.TextField(blank=True, help_text='Account description.'),
                ),
                (
                    'account_type',
                    models.CharField(
                        choices=[
                            ('asset', 'Asset'),
                            ('liability', 'Liability'),
                            ('equity', 'Equity'),
                            ('revenue', 'Revenue'),
                            ('expense', 'Expense'),
                        ],
                        help_text='General ledger account type.',
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('inactive', 'Inactive'),
                            ('closed', 'Closed'),
                            ('archived', 'Archived'),
                        ],
                        db_index=True,
                        default='active',
                        help_text='Account lifecycle status.',
                        max_length=20,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns the ledger account.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='general_ledger_accounts',
                        to='organizations.organization',
                    ),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        help_text='Parent account for hierarchical ledgers.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='children',
                        to='general_ledger.generalledgeraccount',
                    ),
                ),
            ],
            options={
                'verbose_name': 'General Ledger Account',
                'verbose_name_plural': 'General Ledger Accounts',
                'db_table': 'general_ledger_accounts',
                'ordering': ('code', 'name'),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralLedgerJournalEntry',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'reference',
                    models.CharField(
                        help_text='External or internal reference number.',
                        max_length=60,
                    ),
                ),
                (
                    'entry_type',
                    models.CharField(
                        choices=[('debit', 'Debit'), ('credit', 'Credit')],
                        help_text='Debit or credit entry.',
                        max_length=10,
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2, help_text='Entry amount.', max_digits=18
                    ),
                ),
                (
                    'description',
                    models.TextField(blank=True, help_text='Entry description.'),
                ),
                (
                    'posted_at',
                    models.DateTimeField(
                        db_index=True, help_text='When the entry was posted.'
                    ),
                ),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='journal_entries',
                        to='general_ledger.generalledgeraccount',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='general_ledger_journal_entries',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'General Ledger Journal Entry',
                'verbose_name_plural': 'General Ledger Journal Entries',
                'db_table': 'general_ledger_journal_entries',
                'ordering': ('-posted_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='generalledgeraccount',
            index=models.Index(
                fields=['organization', 'status'], name='gl_acct_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='generalledgeraccount',
            index=models.Index(
                fields=['organization', 'account_type'], name='gl_acct_org_type_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='generalledgeraccount',
            constraint=models.UniqueConstraint(
                fields=('organization', 'code'),
                name='unique_gl_account_code_per_organization',
            ),
        ),
        migrations.AddIndex(
            model_name='generalledgerjournalentry',
            index=models.Index(
                fields=['organization', 'account', 'posted_at'],
                name='gl_entry_org_acct_idx',
            ),
        ),
    ]
