# Generated by Django 6.0.6 on 2026-09-09 03:06

import apps.core.models.managers
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('patient_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'preferred_language',
                    models.CharField(
                        default='English',
                        help_text="Patient's preferred language.",
                        max_length=50,
                    ),
                ),
                (
                    'language_proficiency',
                    models.CharField(
                        choices=[
                            ('fluent', 'Fluent'),
                            ('conversational', 'Conversational'),
                            ('basic', 'Basic'),
                            ('none', 'None'),
                        ],
                        default='fluent',
                        help_text="Patient's proficiency in the preferred language.",
                        max_length=20,
                    ),
                ),
                (
                    'nationality',
                    models.CharField(
                        blank=True, help_text='Patient nationality.', max_length=100
                    ),
                ),
                (
                    'religion',
                    models.CharField(
                        blank=True, help_text='Religion (optional).', max_length=100
                    ),
                ),
                (
                    'ethnicity',
                    models.CharField(
                        blank=True, help_text='Ethnicity (optional).', max_length=100
                    ),
                ),
                (
                    'occupation',
                    models.CharField(
                        blank=True, help_text='Patient occupation.', max_length=150
                    ),
                ),
                (
                    'employment_status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('employed', 'Employed'),
                            ('self_employed', 'Self Employed'),
                            ('unemployed', 'Unemployed'),
                            ('student', 'Student'),
                            ('retired', 'Retired'),
                            ('other', 'Other'),
                        ],
                        help_text='Employment status.',
                        max_length=20,
                    ),
                ),
                (
                    'education_level',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('none', 'None'),
                            ('primary', 'Primary'),
                            ('secondary', 'Secondary'),
                            ('diploma', 'Diploma'),
                            ('graduate', 'Graduate'),
                            ('postgraduate', 'Postgraduate'),
                        ],
                        help_text='Highest education level.',
                        max_length=20,
                    ),
                ),
                (
                    'income_bracket',
                    models.CharField(
                        blank=True, help_text='Income bracket.', max_length=50
                    ),
                ),
                (
                    'interpreter_required',
                    models.BooleanField(
                        default=False,
                        help_text='Whether interpreter assistance is required.',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns the patient profile.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='patient_profiles',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.OneToOneField(
                        help_text='Patient associated with this profile.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
                'db_table': 'patient_profiles',
                'ordering': ('patient_id',),
                'indexes': [
                    models.Index(
                        fields=['organization', 'patient'],
                        name='profile_org_patient_idx',
                    )
                ],
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
    ]
