# Generated by Django 6.0.6 on 2026-09-09 03:06

import apps.core.models.managers
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'provider_number',
                    models.CharField(
                        help_text='Unique provider identifier.', max_length=30
                    ),
                ),
                (
                    'provider_type',
                    models.CharField(
                        choices=[
                            ('physician', 'Physician'),
                            ('specialist', 'Specialist'),
                            ('surgeon', 'Surgeon'),
                            ('nurse', 'Nurse'),
                            ('dentist', 'Dentist'),
                            ('pharmacist', 'Pharmacist'),
                            ('therapist', 'Therapist'),
                            ('psychologist', 'Psychologist'),
                            ('dietitian', 'Dietitian'),
                            ('technician', 'Technician'),
                            ('other', 'Other'),
                        ],
                        help_text='Healthcare provider classification.',
                        max_length=30,
                    ),
                ),
                (
                    'years_of_experience',
                    models.PositiveSmallIntegerField(
                        default=0, help_text='Professional experience in years.'
                    ),
                ),
                (
                    'is_accepting_patients',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Whether provider accepts new patients.',
                    ),
                ),
                (
                    'bio',
                    models.TextField(blank=True, help_text='Professional biography.'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('under_review', 'Under Review'),
                            ('verified', 'Verified'),
                            ('active', 'Active'),
                            ('inactive', 'Inactive'),
                            ('suspended', 'Suspended'),
                        ],
                        db_index=True,
                        default='pending',
                        help_text='Provider workflow lifecycle status.',
                        max_length=30,
                    ),
                ),
                (
                    'employee',
                    models.OneToOneField(
                        help_text='Employee profile associated with provider.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='provider',
                        to='employees.employee',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns the provider.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='providers',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'providers',
                'ordering': ('provider_number',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderAssignment',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('inactive', 'Inactive')],
                        db_index=True,
                        default='active',
                        help_text='Assignment lifecycle status.',
                        max_length=20,
                    ),
                ),
                (
                    'effective_from',
                    models.DateField(
                        blank=True, help_text='Assignment effective date.', null=True
                    ),
                ),
                (
                    'effective_until',
                    models.DateField(
                        blank=True, help_text='Assignment end date.', null=True
                    ),
                ),
                (
                    'department',
                    models.ForeignKey(
                        blank=True,
                        help_text='Assigned department.',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='provider_assignments',
                        to='departments.department',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization owning this assignment.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='provider_assignments',
                        to='organizations.organization',
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        help_text='Assigned provider.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='assignments',
                        to='providers.provider',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        blank=True,
                        help_text='Assigned team.',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='provider_assignments',
                        to='teams.team',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Provider Assignment',
                'verbose_name_plural': 'Provider Assignments',
                'db_table': 'provider_assignments',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'day_of_week',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'Monday'),
                            (2, 'Tuesday'),
                            (3, 'Wednesday'),
                            (4, 'Thursday'),
                            (5, 'Friday'),
                            (6, 'Saturday'),
                            (7, 'Sunday'),
                        ],
                        help_text='ISO weekday number.',
                    ),
                ),
                ('start_time', models.TimeField(help_text='Availability start time.')),
                ('end_time', models.TimeField(help_text='Availability end time.')),
                (
                    'location',
                    models.CharField(
                        blank=True,
                        help_text='Clinic location or facility.',
                        max_length=150,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('available', 'Available'),
                            ('unavailable', 'Unavailable'),
                            ('blocked', 'Blocked'),
                        ],
                        db_index=True,
                        default='available',
                        help_text='Availability status.',
                        max_length=30,
                    ),
                ),
                (
                    'is_recurring',
                    models.BooleanField(
                        default=True,
                        help_text='Whether this availability repeats weekly.',
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True, help_text='Additional scheduling notes.'
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        help_text='Provider associated with availability.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='availability',
                        to='providers.provider',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Provider Availability',
                'verbose_name_plural': 'Provider Availability',
                'db_table': 'provider_availability',
                'ordering': ('day_of_week', 'start_time'),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'credential_type',
                    models.CharField(
                        choices=[
                            ('degree', 'Degree'),
                            ('certification', 'Certification'),
                            ('fellowship', 'Fellowship'),
                            ('training', 'Training'),
                            ('license', 'License'),
                        ],
                        help_text='Type of professional credential.',
                        max_length=30,
                    ),
                ),
                (
                    'name',
                    models.CharField(help_text='Credential name.', max_length=150),
                ),
                (
                    'issuing_authority',
                    models.CharField(
                        blank=True,
                        help_text='Organization issuing credential.',
                        max_length=150,
                    ),
                ),
                (
                    'credential_number',
                    models.CharField(
                        blank=True,
                        help_text='Credential reference number.',
                        max_length=100,
                    ),
                ),
                (
                    'issued_date',
                    models.DateField(
                        blank=True, help_text='Credential issue date.', null=True
                    ),
                ),
                (
                    'expiry_date',
                    models.DateField(
                        blank=True, help_text='Credential expiry date.', null=True
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('verified', 'Verified'),
                            ('rejected', 'Rejected'),
                            ('expired', 'Expired'),
                        ],
                        db_index=True,
                        default='pending',
                        help_text='Credential verification status.',
                        max_length=30,
                    ),
                ),
                (
                    'document_id',
                    models.UUIDField(
                        blank=True, help_text='Linked document identifier.', null=True
                    ),
                ),
                (
                    'remarks',
                    models.TextField(blank=True, help_text='Verification notes.'),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        help_text='Provider associated with credential.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credentials',
                        to='providers.provider',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Provider Credential',
                'verbose_name_plural': 'Provider Credentials',
                'db_table': 'provider_credentials',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderLicense',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'license_number',
                    models.CharField(
                        help_text='Professional license number.', max_length=100
                    ),
                ),
                (
                    'license_type',
                    models.CharField(
                        help_text='Type of medical license.', max_length=100
                    ),
                ),
                (
                    'issuing_authority',
                    models.CharField(
                        help_text='Regulatory authority issuing license.',
                        max_length=150,
                    ),
                ),
                (
                    'issuing_region',
                    models.CharField(
                        blank=True,
                        help_text='State, province or country.',
                        max_length=100,
                    ),
                ),
                ('issue_date', models.DateField(help_text='License issue date.')),
                (
                    'expiry_date',
                    models.DateField(
                        blank=True, help_text='License expiry date.', null=True
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('verified', 'Verified'),
                            ('expired', 'Expired'),
                            ('suspended', 'Suspended'),
                            ('revoked', 'Revoked'),
                        ],
                        db_index=True,
                        default='pending',
                        help_text='License lifecycle status.',
                        max_length=30,
                    ),
                ),
                (
                    'verification_notes',
                    models.TextField(
                        blank=True, help_text='License verification remarks.'
                    ),
                ),
                (
                    'document_id',
                    models.UUIDField(
                        blank=True,
                        help_text='Linked license document identifier.',
                        null=True,
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        help_text='Provider associated with license.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='licenses',
                        to='providers.provider',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Provider License',
                'verbose_name_plural': 'Provider Licenses',
                'db_table': 'provider_licenses',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderSpecialization',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'name',
                    models.CharField(help_text='Specialization name.', max_length=100),
                ),
                (
                    'code',
                    models.CharField(
                        help_text='Unique specialization code.', max_length=50
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True, help_text='Specialization description.'
                    ),
                ),
                (
                    'is_primary',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text='Primary specialization for provider.',
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        help_text='Provider associated with specialization.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='specializations',
                        to='providers.provider',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Provider Specialization',
                'verbose_name_plural': 'Provider Specializations',
                'db_table': 'provider_specializations',
                'ordering': ('name',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(
                fields=['organization', 'provider_type'],
                name='providers_organiz_bc35fc_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(
                fields=['organization', 'status'], name='providers_organiz_e476dc_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(
                fields=['organization', 'is_accepting_patients'],
                name='providers_organiz_c78ecf_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(
                fields=('organization', 'provider_number'),
                name='unique_provider_number_per_organization',
            ),
        ),
        migrations.AddIndex(
            model_name='providerassignment',
            index=models.Index(
                fields=['organization', 'status'], name='provider_as_organiz_1ea6c9_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='providerassignment',
            index=models.Index(
                fields=['provider', 'status'], name='provider_as_provide_0302fb_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='providerassignment',
            index=models.Index(
                fields=['department'], name='provider_as_departm_f71e0c_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='providerassignment',
            index=models.Index(fields=['team'], name='provider_as_team_id_409594_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerassignment',
            constraint=models.UniqueConstraint(
                fields=('provider', 'department', 'team'),
                name='unique_provider_assignment',
            ),
        ),
        migrations.AddIndex(
            model_name='provideravailability',
            index=models.Index(
                fields=['provider', 'day_of_week'],
                name='provider_av_provide_8d67c8_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='provideravailability',
            index=models.Index(fields=['status'], name='provider_av_status_4cecd4_idx'),
        ),
        migrations.AddIndex(
            model_name='providercredential',
            index=models.Index(
                fields=['provider', 'status'], name='provider_cr_provide_102991_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='providercredential',
            index=models.Index(
                fields=['credential_type'], name='provider_cr_credent_c1ad28_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='providercredential',
            index=models.Index(
                fields=['expiry_date'], name='provider_cr_expiry__84e9bd_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='providerlicense',
            index=models.Index(
                fields=['provider', 'status'], name='provider_li_provide_25dd08_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='providerlicense',
            index=models.Index(
                fields=['license_number'], name='provider_li_license_2626f4_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='providerlicense',
            index=models.Index(
                fields=['expiry_date'], name='provider_li_expiry__ebdadd_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='providerlicense',
            constraint=models.UniqueConstraint(
                fields=('provider', 'license_number'), name='unique_provider_license'
            ),
        ),
        migrations.AddIndex(
            model_name='providerspecialization',
            index=models.Index(
                fields=['provider'], name='provider_sp_provide_e654cc_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='providerspecialization',
            index=models.Index(fields=['code'], name='provider_sp_code_0ede75_idx'),
        ),
        migrations.AddIndex(
            model_name='providerspecialization',
            index=models.Index(
                fields=['is_primary'], name='provider_sp_is_prim_794705_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='providerspecialization',
            constraint=models.UniqueConstraint(
                fields=('provider', 'code'), name='unique_provider_specialization'
            ),
        ),
    ]
