# Generated by Django 6.0.6 on 2026-07-31 11:49

import apps.core.models.managers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        help_text='Human readable document title.',
                        max_length=255,
                        verbose_name='Title',
                    ),
                ),
                (
                    'document_type',
                    models.CharField(
                        choices=[
                            ('general', 'General Document'),
                            ('contract', 'Contract'),
                            ('identification', 'Identification Document'),
                            ('medical_record', 'Medical Record'),
                            ('report', 'Report'),
                            ('prescription', 'Prescription'),
                            ('consent', 'Consent Document'),
                            ('insurance', 'Insurance Document'),
                            ('invoice', 'Invoice'),
                        ],
                        db_index=True,
                        default='general',
                        max_length=50,
                        verbose_name='Document Type',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('active', 'Active'),
                            ('archived', 'Archived'),
                            ('deleted', 'Deleted'),
                        ],
                        db_index=True,
                        default='active',
                        max_length=30,
                        verbose_name='Status',
                    ),
                ),
                (
                    'access_level',
                    models.CharField(
                        choices=[
                            ('private', 'Private'),
                            ('organization', 'Organization'),
                            ('tenant', 'Tenant'),
                            ('public', 'Public'),
                        ],
                        db_index=True,
                        default='private',
                        max_length=30,
                        verbose_name='Access Level',
                    ),
                ),
                (
                    'storage_key',
                    models.CharField(
                        help_text='External storage reference.',
                        max_length=500,
                        verbose_name='Storage Key',
                    ),
                ),
                (
                    'original_filename',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Original Filename'
                    ),
                ),
                (
                    'mime_type',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='Mime Type'
                    ),
                ),
                (
                    'file_size',
                    models.BigIntegerField(
                        default=0,
                        help_text='File size in bytes.',
                        verbose_name='File Size',
                    ),
                ),
                (
                    'checksum',
                    models.CharField(
                        blank=True,
                        help_text='Integrity checksum.',
                        max_length=255,
                        verbose_name='Checksum',
                    ),
                ),
                (
                    'metadata',
                    models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
                ),
                (
                    'ai_metadata',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='AI extraction and enrichment metadata.',
                        verbose_name='AI Metadata',
                    ),
                ),
                (
                    'archived_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Archived At'
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization owning this document.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='documents',
                        to='organizations.organization',
                        verbose_name='Organization',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        help_text='Tenant owning this document.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='documents',
                        to='tenancy.tenant',
                        verbose_name='Tenant',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'permission',
                    models.CharField(
                        choices=[
                            ('view', 'View'),
                            ('download', 'Download'),
                            ('edit', 'Edit'),
                            ('share', 'Share'),
                            ('delete', 'Delete'),
                        ],
                        db_index=True,
                        default='view',
                        max_length=30,
                        verbose_name='Permission',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Whether access is currently active.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'expires_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Optional access expiration.',
                        null=True,
                        verbose_name='Expires At',
                    ),
                ),
                (
                    'metadata',
                    models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
                ),
                (
                    'document',
                    models.ForeignKey(
                        help_text='Document being accessed.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='access_entries',
                        to='documents.document',
                        verbose_name='Document',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='User receiving access.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='document_access',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Document Access',
                'verbose_name_plural': 'Document Access Entries',
                'db_table': 'document_access',
                'ordering': ('document', 'user'),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'version_number',
                    models.PositiveIntegerField(
                        default=1,
                        help_text='Sequential document version number.',
                        verbose_name='Version Number',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('current', 'Current'),
                            ('superseded', 'Superseded'),
                            ('archived', 'Archived'),
                        ],
                        db_index=True,
                        default='current',
                        max_length=30,
                        verbose_name='Version Status',
                    ),
                ),
                (
                    'storage_key',
                    models.CharField(
                        help_text='Storage reference for this version.',
                        max_length=500,
                        verbose_name='Storage Key',
                    ),
                ),
                (
                    'original_filename',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Original Filename'
                    ),
                ),
                (
                    'mime_type',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='Mime Type'
                    ),
                ),
                (
                    'file_size',
                    models.BigIntegerField(default=0, verbose_name='File Size'),
                ),
                (
                    'checksum',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Checksum'
                    ),
                ),
                (
                    'extraction_metadata',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='AI/OCR extraction output.',
                        verbose_name='Extraction Metadata',
                    ),
                ),
                (
                    'metadata',
                    models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
                ),
                (
                    'document',
                    models.ForeignKey(
                        help_text='Parent document.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='versions',
                        to='documents.document',
                        verbose_name='Document',
                    ),
                ),
                (
                    'uploaded_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='uploaded_document_versions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Uploaded By',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'db_table': 'document_versions',
                'ordering': ('document', '-version_number'),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant'], name='idx_document_tenant'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization'], name='idx_document_org'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='idx_document_status'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='idx_document_type'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['access_level'], name='idx_document_access'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(
                fields=('tenant', 'storage_key'), name='uq_document_tenant_storage_key'
            ),
        ),
        migrations.AddIndex(
            model_name='documentaccess',
            index=models.Index(
                fields=['document'], name='idx_document_access_document'
            ),
        ),
        migrations.AddIndex(
            model_name='documentaccess',
            index=models.Index(fields=['user'], name='idx_document_access_user'),
        ),
        migrations.AddIndex(
            model_name='documentaccess',
            index=models.Index(
                fields=['permission'], name='idx_document_access_permission'
            ),
        ),
        migrations.AddIndex(
            model_name='documentaccess',
            index=models.Index(fields=['is_active'], name='idx_document_access_active'),
        ),
        migrations.AddConstraint(
            model_name='documentaccess',
            constraint=models.UniqueConstraint(
                fields=('document', 'user', 'permission'),
                name='uq_document_user_permission',
            ),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(
                fields=['document'], name='idx_document_version_document'
            ),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['status'], name='idx_document_version_status'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(
                fields=['checksum'], name='idx_document_version_checksum'
            ),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(
                fields=('document', 'version_number'), name='uq_document_version_number'
            ),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(
                condition=models.Q(('version_number__gte', 1)),
                name='ck_document_version_positive',
            ),
        ),
    ]
