# Generated by Django 6.0.6 on 2026-07-31 11:49

import apps.core.models.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('key', models.CharField(max_length=100, unique=True)),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('GENERAL', 'General'),
                            ('BRANDING', 'Branding'),
                            ('SECURITY', 'Security'),
                            ('EMAIL', 'Email'),
                            ('SMS', 'SMS'),
                            ('STORAGE', 'Storage'),
                            ('AI', 'Artificial Intelligence'),
                            ('SYSTEM', 'System'),
                        ],
                        default='GENERAL',
                        max_length=30,
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('value', models.TextField()),
                (
                    'value_type',
                    models.CharField(
                        choices=[
                            ('STRING', 'String'),
                            ('INTEGER', 'Integer'),
                            ('BOOLEAN', 'Boolean'),
                            ('FLOAT', 'Float'),
                            ('JSON', 'JSON'),
                        ],
                        default='STRING',
                        max_length=20,
                    ),
                ),
                ('is_editable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'db_table': 'configurations',
                'ordering': ('category', 'name'),
                'indexes': [
                    models.Index(
                        fields=['category'], name='configurati_categor_e5efde_idx'
                    ),
                    models.Index(fields=['key'], name='configurati_key_51176b_idx'),
                ],
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'key',
                    models.CharField(
                        choices=[
                            ('AI_ASSISTANT', 'AI Assistant'),
                            ('APPOINTMENTS', 'Appointments'),
                            ('AUDIT', 'Audit'),
                            ('BILLING', 'Billing'),
                            ('EMPLOYEES', 'Employees'),
                            ('INVENTORY', 'Inventory'),
                            ('LABORATORY', 'Laboratory'),
                            ('NOTIFICATIONS', 'Notifications'),
                            ('PATIENTS', 'Patients'),
                            ('PHARMACY', 'Pharmacy'),
                            ('STORAGE', 'Storage'),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'db_table': 'feature_flags',
                'ordering': ('name',),
                'indexes': [
                    models.Index(fields=['key'], name='feature_fla_key_b4f409_idx'),
                    models.Index(
                        fields=['is_enabled'], name='feature_fla_is_enab_8bb5d4_idx'
                    ),
                ],
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
    ]
