# Generated by Django 6.0.6 on 2026-07-25 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        ("tenancy", "0003_usertenantpreference"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="organization",
            new_name="idx_org_active",
            old_name="organizatio_is_acti_bdc355_idx",
        ),
        migrations.AddField(
            model_name="organization",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant owning this organization.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="accreditation",
            field=models.CharField(
                blank=True, help_text="Accreditation identifier.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="organization",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="organization",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("trial", "Trial"),
                    ("active", "Active"),
                    ("grace_period", "Grace Period"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="trial",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["tenant"], name="idx_org_tenant"),
        ),
    ]
