# Generated by Django 6.0.6 on 2026-07-28 10:24

import apps.core.models.managers
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'medication_code',
                    models.CharField(
                        help_text='Unique medication code.', max_length=30
                    ),
                ),
                (
                    'generic_name',
                    models.CharField(
                        db_index=True,
                        help_text='Generic medication name.',
                        max_length=255,
                    ),
                ),
                (
                    'brand_name',
                    models.CharField(
                        blank=True, help_text='Brand name.', max_length=255
                    ),
                ),
                (
                    'strength',
                    models.CharField(help_text='Medication strength.', max_length=50),
                ),
                (
                    'strength_unit',
                    models.CharField(help_text='Strength unit.', max_length=20),
                ),
                (
                    'dosage_form',
                    models.CharField(
                        choices=[
                            ('tablet', 'Tablet'),
                            ('capsule', 'Capsule'),
                            ('syrup', 'Syrup'),
                            ('suspension', 'Suspension'),
                            ('injection', 'Injection'),
                            ('cream', 'Cream'),
                            ('ointment', 'Ointment'),
                            ('gel', 'Gel'),
                            ('drops', 'Drops'),
                            ('inhaler', 'Inhaler'),
                        ],
                        db_index=True,
                        default='tablet',
                        help_text='Medication dosage form.',
                        max_length=30,
                    ),
                ),
                (
                    'route',
                    models.CharField(
                        choices=[
                            ('oral', 'Oral'),
                            ('intravenous', 'Intravenous'),
                            ('intramuscular', 'Intramuscular'),
                            ('subcutaneous', 'Subcutaneous'),
                            ('topical', 'Topical'),
                            ('ophthalmic', 'Ophthalmic'),
                            ('otic', 'Otic'),
                            ('nasal', 'Nasal'),
                            ('rectal', 'Rectal'),
                            ('inhalation', 'Inhalation'),
                        ],
                        db_index=True,
                        default='oral',
                        help_text='Administration route.',
                        max_length=30,
                    ),
                ),
                (
                    'manufacturer',
                    models.CharField(
                        blank=True, help_text='Medication manufacturer.', max_length=255
                    ),
                ),
                (
                    'description',
                    models.TextField(blank=True, help_text='Medication description.'),
                ),
                (
                    'is_controlled',
                    models.BooleanField(
                        default=False,
                        help_text='Whether this medication is a controlled substance.',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns this medication.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='medications',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'db_table': 'medications',
                'ordering': ('generic_name',),
                'indexes': [
                    models.Index(
                        fields=['medication_code'],
                        name='medications_medicat_5d1d4d_idx',
                    ),
                    models.Index(
                        fields=['generic_name'], name='medications_generic_f22126_idx'
                    ),
                    models.Index(
                        fields=['brand_name'], name='medications_brand_n_90e883_idx'
                    ),
                    models.Index(
                        fields=['dosage_form'], name='medications_dosage__978049_idx'
                    ),
                    models.Index(fields=['route'], name='medications_route_089c91_idx'),
                    models.Index(
                        fields=['organization'], name='medications_organiz_7566c4_idx'
                    ),
                    models.Index(
                        fields=['generic_name', 'strength'],
                        name='medications_generic_99881a_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('organization', 'medication_code'),
                        name='unique_medication_code_per_organization',
                    )
                ],
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
    ]
