# Generated by Django 6.0.6 on 2026-06-30 09:09

import apps.common.validators.organization
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Unique organization name.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique organization code.",
                        max_length=20,
                        unique=True,
                        validators=[
                            apps.common.validators.organization.validate_organization_code
                        ],
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital"),
                            ("clinic", "Clinic"),
                            ("laboratory", "Laboratory"),
                            ("corporate", "Corporate"),
                        ],
                        db_index=True,
                        default="hospital",
                        help_text="Organization category.",
                        max_length=100,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Primary contact email.", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact phone number.",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number. Example: +919876543210",
                                regex="^\\+?[1-9]\\d{9,14}$",
                            )
                        ],
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Organization address."),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City where the organization is located.",
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="State where the organization is located.",
                        max_length=100,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="India",
                        help_text="Country where the organization is located.",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Designates whether this organization is active.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ("name",),
            },
        ),
    ]
