# Generated by Django 6.0.6 on 2026-06-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("Hospital", "Hospital"),
                    ("Clinic", "Clinic"),
                    ("Laboratory", "Laboratory"),
                    ("Corporate", "Corporate"),
                ],
                default="Hospital",
                max_length=100,
            ),
        ),
    ]
