# Generated by Django 6.0.6 on 2026-09-12 00:58

import apps.core.models.managers
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('pharmacy', '0002_stocktransferorder_stocktransferline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecall',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('recall_number', models.CharField(max_length=80)),
                ('reason', models.TextField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('open', 'Open'),
                            ('in_progress', 'In Progress'),
                            ('closed', 'Closed'),
                        ],
                        default='open',
                        max_length=20,
                    ),
                ),
                ('initiated_by_id', models.UUIDField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='pharmacy_recalls',
                        to='organizations.organization',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='recalls',
                        to='pharmacy.pharmacyproduct',
                    ),
                ),
            ],
            options={
                'db_table': 'pharmacy_product_recalls',
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='RecallBatch',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'quantity_affected',
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                ('quarantined', models.BooleanField(default=False)),
                (
                    'batch',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='recalls',
                        to='pharmacy.medicationbatch',
                    ),
                ),
                (
                    'recall',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='batches',
                        to='pharmacy.productrecall',
                    ),
                ),
            ],
            options={
                'db_table': 'pharmacy_recall_batches',
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='ControlledSubstanceControl',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'schedule',
                    models.CharField(
                        choices=[
                            ('none', 'Not Controlled'),
                            ('schedule_i', 'Schedule I'),
                            ('schedule_ii', 'Schedule II'),
                            ('schedule_iii', 'Schedule III'),
                            ('schedule_iv', 'Schedule IV'),
                            ('schedule_v', 'Schedule V'),
                        ],
                        max_length=20,
                    ),
                ),
                ('requires_double_check', models.BooleanField(default=True)),
                (
                    'max_daily_quantity',
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ('license_reference', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='pharmacy_controlled_substances',
                        to='organizations.organization',
                    ),
                ),
                (
                    'product',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='controlled_control',
                        to='pharmacy.pharmacyproduct',
                    ),
                ),
            ],
            options={
                'db_table': 'pharmacy_controlled_substance_controls',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('organization', 'product'),
                        name='unique_controlled_control_per_org_product',
                    )
                ],
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryQuarantine',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.TextField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('quarantined', 'Quarantined'),
                            ('released', 'Released'),
                            ('destroyed', 'Destroyed'),
                        ],
                        default='quarantined',
                        max_length=20,
                    ),
                ),
                ('quarantined_by_id', models.UUIDField(blank=True, null=True)),
                ('released_by_id', models.UUIDField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                (
                    'batch',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='quarantine_records',
                        to='pharmacy.medicationbatch',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='pharmacy_quarantines',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'pharmacy_inventory_quarantines',
                'indexes': [
                    models.Index(
                        fields=['organization', 'status'],
                        name='pharmacy_in_organiz_09ca4d_idx',
                    ),
                    models.Index(
                        fields=['batch', 'status'],
                        name='pharmacy_in_batch_i_a96b79_idx',
                    ),
                ],
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyBillingRecord',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('currency', models.CharField(default='INR', max_length=3)),
                (
                    'subtotal',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), max_digits=14
                    ),
                ),
                (
                    'tax_amount',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), max_digits=14
                    ),
                ),
                (
                    'total_amount',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), max_digits=14
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('invoiced', 'Invoiced'),
                            ('paid', 'Paid'),
                            ('void', 'Void'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('external_invoice_id', models.CharField(blank=True, max_length=120)),
                (
                    'dispensing_order',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='billing_record',
                        to='pharmacy.dispensingorder',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='pharmacy_billing_records',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'pharmacy_billing_records',
                'indexes': [
                    models.Index(
                        fields=['organization', 'status'],
                        name='pharmacy_bi_organiz_b25e0b_idx',
                    )
                ],
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyIdempotencyKey',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('key', models.CharField(max_length=160)),
                ('operation', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='pharmacy_idempotency_keys',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'pharmacy_idempotency_keys',
                'indexes': [
                    models.Index(
                        fields=['organization', 'operation'],
                        name='pharmacy_id_organiz_e1937e_idx',
                    )
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('organization', 'key', 'operation'),
                        name='unique_pharmacy_idempotency_key',
                    )
                ],
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementApproval',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('approved', 'Approved'),
                            ('rejected', 'Rejected'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('requested_by_id', models.UUIDField(blank=True, null=True)),
                ('decided_by_id', models.UUIDField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='pharmacy_procurement_approvals',
                        to='organizations.organization',
                    ),
                ),
                (
                    'purchase_order',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='procurement_approval',
                        to='pharmacy.purchaseorder',
                    ),
                ),
            ],
            options={
                'db_table': 'pharmacy_procurement_approvals',
                'indexes': [
                    models.Index(
                        fields=['organization', 'status'],
                        name='pharmacy_pr_organiz_25187b_idx',
                    )
                ],
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='productrecall',
            constraint=models.UniqueConstraint(
                fields=('organization', 'recall_number'),
                name='unique_pharmacy_recall_number',
            ),
        ),
        migrations.AddConstraint(
            model_name='recallbatch',
            constraint=models.UniqueConstraint(
                fields=('recall', 'batch'), name='unique_recall_batch'
            ),
        ),
    ]
