# Generated by Django 6.0.6 on 2026-09-12 02:41

import apps.core.models.managers
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        (
            'pharmacy',
            '0003_productrecall_recallbatch_controlledsubstancecontrol_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyOutboxEvent',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                ('event_id', models.UUIDField(db_index=True, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('processing', 'Processing'),
                            ('published', 'Published'),
                            ('failed', 'Failed'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('attempts', models.PositiveIntegerField(default=0)),
                (
                    'available_at',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='pharmacy_outbox_events',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'pharmacy_outbox_events',
                'indexes': [
                    models.Index(
                        fields=['status', 'available_at'],
                        name='pharmacy_ou_status_bbf68b_idx',
                    ),
                    models.Index(
                        fields=['organization', 'status'],
                        name='pharmacy_ou_organiz_0ade0b_idx',
                    ),
                    models.Index(
                        fields=['aggregate_type', 'aggregate_id'],
                        name='pharmacy_ou_aggrega_6eb338_idx',
                    ),
                ],
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
    ]
