# Generated by Django 6.0.6 on 2026-09-16 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_operations', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patient_core', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'uuid',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('reserved_from', models.DateTimeField()),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'hospital_operations_bed_reservations',
            },
        ),
        migrations.AlterField(
            model_name='admission',
            name='admission_number',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(
                choices=[
                    ('admitted', 'admitted'),
                    ('discharged', 'discharged'),
                    ('cancelled', 'cancelled'),
                ],
                default='admitted',
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.UniqueConstraint(
                fields=('organization', 'admission_number'),
                name='hop_adm_org_number_uniq',
            ),
        ),
        migrations.AddField(
            model_name='bedreservation',
            name='bed',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='reservations',
                to='hospital_operations.bed',
            ),
        ),
        migrations.AddField(
            model_name='bedreservation',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='hospital_bed_reservations',
                to='organizations.organization',
            ),
        ),
        migrations.AddField(
            model_name='bedreservation',
            name='patient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='hospital_bed_reservations',
                to='patient_core.patient',
            ),
        ),
        migrations.AddField(
            model_name='bedreservation',
            name='tenant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='hospital_bed_reservations',
                to='tenancy.tenant',
            ),
        ),
        migrations.AddConstraint(
            model_name='bedreservation',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'active')),
                fields=('bed',),
                name='hop_one_active_bed_reservation',
            ),
        ),
        migrations.AddConstraint(
            model_name='bedreservation',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('reserved_until__isnull', True),
                    ('reserved_until__gt', models.F('reserved_from')),
                    _connector='OR',
                ),
                name='hop_reservation_time_valid',
            ),
        ),
    ]
