import { test, expect } from "@playwright/test";

test("seeded HR manager uses real bootstrap and persists attendance, leave, payroll and recruitment", async ({ page, request }) => {
  const api = process.env.HR_LIVE_API_URL;
  const session = JSON.parse(process.env.HR_LIVE_SESSION ?? "{}");
  test.skip(!api, "Run through the backend live browser test.");
  page.on("pageerror", (error) => console.log("Browser error", error.message));
  page.on("requestfailed", (request) => console.log("Request failed", new URL(request.url()).pathname, request.failure()?.errorText));
  await page.addInitScript((session) => {
    for (const key of ["access_token", "refresh_token", "current_user"]) {
      const entry = JSON.stringify({ value: session[key], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
      localStorage.setItem(`datavion:v1:${key}`, entry);
      sessionStorage.setItem(`datavion:v1:${key}`, entry);
    }
  }, session);
  // Relay to the disposable Django server; every response is produced by real APIs.
  await page.route("**/api/**", async (route) => {
    const original = new URL(route.request().url());
    const response = await route.fetch({ url: `${api}${original.pathname}${original.search}` });
    console.log("API", original.pathname, response.status());
    if (!response.ok()) console.log("API failure", original.pathname, response.status(), await response.text());
    await route.fulfill({ response });
  });
  const headers = { Authorization: `Bearer ${session.access_token}`, "X-Organization-ID": session.organization };
  const read = async (path: string) => {
    const response = await request.get(`${api}/api/${path}`, { headers });
    expect(response.ok()).toBeTruthy();
    return (await response.json()).data;
  };
  await page.goto("/workspace/hr");
  await expect(page.getByRole("heading", { name: /HR Manager/ })).toBeVisible();
  await page.screenshot({ path: "test-results/hr-live-initial.png", fullPage: true });
  await expect(page.getByTestId("hr-metric-headcount")).toHaveText("1");
  await page.getByRole("navigation", { name: "HR navigation" }).getByRole("link", { name: "Attendance", exact: true }).click();
  await page.getByRole("button", { name: "Create record" }).click();
  await expect(page.getByLabel("Employee *", { exact: true })).toBeEnabled();
  await page.getByLabel("Employee *", { exact: true }).selectOption(session.employee);
  const today = new Date().toLocaleDateString("en-CA");
  await page.getByLabel("Work date *").fill(today);
  await page.getByLabel("Check in", { exact: true }).fill("09:00");
  await page.getByLabel("Check out", { exact: true }).fill("17:00");
  await page.getByRole("button", { name: "Save record" }).click();
  await expect(page.getByText("Record saved.")).toBeVisible();
  expect(JSON.stringify(await read("hr/attendance/"))).toContain('"hours_worked":"8.00"');
  await page.reload();
  await expect(page.getByRole("cell", { name: "HR Manager", exact: true })).toBeVisible();
  const typeResponse = await request.post(`${api}/api/hr/leave/types/`, { headers, data: { organization: session.organization, name: "Annual", code: "ANN", is_paid: true } });
  expect(typeResponse.ok()).toBeTruthy();
  const leaveType = (await typeResponse.json()).data.id;
  const balanceResponse = await request.post(`${api}/api/hr/leave/balances/`, { headers, data: { employee: session.employee, leave_type: leaveType, year: Number(today.slice(0, 4)), allocated_days: 20 } });
  expect(balanceResponse.ok()).toBeTruthy();
  await page.getByRole("navigation", { name: "HR navigation" }).getByRole("link", { name: "Leave", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Leave requests", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Create record" }).click();
  await page.getByLabel("Employee *", { exact: true }).selectOption(session.employee);
  await page.getByLabel("Leave type *").selectOption(String(leaveType));
  await page.getByLabel("Start date *").fill(today);
  await page.getByLabel("End date *").fill(today);
  await page.getByLabel("Number of days *").fill("1");
  await page.getByRole("button", { name: "Save record" }).click();
  await expect(page.getByText("Record saved.")).toBeVisible();
  await page.getByRole("button", { name: "Approve", exact: true }).click();
  await page.getByLabel("Decision notes").fill("Approved in live test");
  await page.getByRole("button", { name: "Confirm", exact: true }).click();
  await expect(page.getByRole("cell", { name: "Approved", exact: true })).toBeVisible();
  expect(JSON.stringify(await read("hr/leave/balances/"))).toContain('"used_days":"1.00"');
  await page.getByRole("navigation", { name: "HR navigation" }).getByRole("link", { name: "Payroll", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Payslips", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Create record" }).click();
  await page.getByLabel("Employee *", { exact: true }).selectOption(session.employee);
  await page.getByLabel("Pay period start *").fill(today);
  await page.getByLabel("Pay period end *").fill(today);
  await page.getByLabel("Basic salary *").fill("1000");
  await page.getByLabel("Total allowances", { exact: true }).fill("100");
  await page.getByRole("button", { name: "Add component", exact: true }).click();
  await page.getByLabel("Component", { exact: true }).selectOption("deduction");
  await page.getByLabel("Name", { exact: true }).fill("Tax");
  await page.getByLabel("Amount", { exact: true }).fill("50");
  await page.getByRole("button", { name: "Save record" }).click();
  await expect(page.getByText("Record saved.")).toBeVisible();
  await page.getByRole("button", { name: "Process", exact: true }).click();
  await page.getByRole("button", { name: "Confirm", exact: true }).click();
  await expect(page.getByRole("cell", { name: "Processed", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Mark paid", exact: true }).click();
  await page.getByRole("button", { name: "Confirm", exact: true }).click();
  await expect(page.getByRole("cell", { name: "Paid", exact: true })).toBeVisible();
  expect(JSON.stringify(await read("hr/payroll/payslips/"))).toContain('"net_pay":"1050.00"');
  await page.getByRole("navigation", { name: "HR navigation" }).getByRole("link", { name: "Recruitment", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Job openings", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Create record" }).click();
  await page.getByLabel("Title *", { exact: true }).fill("Senior Nurse");
  await page.getByLabel("Status", { exact: true }).selectOption("open");
  await page.getByLabel("Priority", { exact: true }).selectOption("urgent");
  await page.getByRole("button", { name: "Save record" }).click();
  await expect(page.getByText("Record saved.")).toBeVisible();
  const jobs = await read("hr/recruitment/jobs/");
  expect(JSON.stringify(jobs)).toContain("Senior Nurse");
  await page.getByRole("button", { name: "Candidates", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Candidates", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Create record" }).click();
  await page.getByLabel("Job *", { exact: true }).selectOption(String(jobs[0].id));
  await page.getByLabel("Full name *").fill("New Nurse");
  await page.getByLabel("Email *", { exact: true }).fill("nurse@example.test");
  await page.getByRole("button", { name: "Save record" }).click();
  await expect(page.getByText("Record saved.")).toBeVisible();
  const candidates = await read("hr/recruitment/candidates/");
  expect(JSON.stringify(candidates)).toContain("New Nurse");
  await page.getByRole("button", { name: "Edit", exact: true }).click();
  await page.getByLabel("Status", { exact: true }).selectOption("shortlisted");
  await page.getByRole("button", { name: "Save record" }).click();
  await expect(page.getByRole("cell", { name: "Shortlisted", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Interviews", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Interviews", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Create record" }).click();
  await page.getByLabel("Candidate *", { exact: true }).selectOption(String(candidates[0].id));
  await page.getByLabel("Interviewer *", { exact: true }).selectOption(session.employee);
  await page.getByLabel("Scheduled at *").fill(`${today}T14:00`);
  await page.getByRole("button", { name: "Save record" }).click();
  await expect(page.getByText("Record saved.")).toBeVisible();
  await page.getByRole("button", { name: "Edit", exact: true }).click();
  await page.getByLabel("Status", { exact: true }).selectOption("completed");
  await page.getByLabel("Feedback", { exact: true }).fill("Recommended for hire");
  await page.getByRole("button", { name: "Save record" }).click();
  await expect(page.getByRole("cell", { name: "Completed", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Candidates", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Candidates", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Edit", exact: true }).click();
  await page.getByLabel("Status", { exact: true }).selectOption("offered");
  await page.getByRole("button", { name: "Save record" }).click();
  await expect(page.getByRole("cell", { name: "Offered", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Edit", exact: true }).click();
  await page.getByLabel("Status", { exact: true }).selectOption("hired");
  await page.getByLabel("Employee code", { exact: true }).fill("NEW001");
  await page.getByLabel("Joining date", { exact: true }).fill(today);
  await page.getByRole("button", { name: "Save record" }).click();
  await expect(page.getByRole("cell", { name: "Hired", exact: true })).toBeVisible();
  expect(JSON.stringify(await read("employees/"))).toContain("NEW001");
  expect(JSON.stringify(await read("hr/onboarding/processes/"))).toContain("in_progress");
  await page.getByRole("navigation", { name: "HR navigation" }).getByRole("link", { name: "Overview", exact: true }).click();
  await expect(page.getByTestId("hr-metric-open-jobs")).toHaveText("1");
  await expect(page.getByTestId("hr-metric-headcount")).toHaveText("2");
  await expect(page.getByTestId("hr-metric-attendance")).toHaveText("50%");
  await page.screenshot({ path: "test-results/hr-live-manager.png", fullPage: true });
});
