# Generated by Django 6.0.6 on 2026-07-27 06:42

import apps.core.models.managers
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'code',
                    models.CharField(blank=True, help_text='Code.', max_length=60),
                ),
                (
                    'name',
                    models.CharField(blank=True, help_text='Name.', max_length=150),
                ),
                (
                    'email',
                    models.CharField(blank=True, help_text='Email.', max_length=120),
                ),
                (
                    'phone',
                    models.CharField(blank=True, help_text='Phone.', max_length=60),
                ),
                ('address', models.TextField(blank=True, help_text='Address.')),
                (
                    'tax_id',
                    models.CharField(blank=True, help_text='Tax Id.', max_length=60),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns the vendor record.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='accounts_payable_vendors',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'accounts_payable_vendors',
                'ordering': ('name',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'invoice_number',
                    models.CharField(
                        blank=True, help_text='Invoice Number.', max_length=60
                    ),
                ),
                ('reference', models.TextField(blank=True, help_text='Reference.')),
                (
                    'amount',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Amount.',
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    'tax_amount',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Tax Amount.',
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    'due_date',
                    models.DateTimeField(
                        blank=True, db_index=True, help_text='Due Date.', null=True
                    ),
                ),
                (
                    'status',
                    models.CharField(blank=True, help_text='Status.', max_length=40),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='accounts_payable_vendor_invoices',
                        to='organizations.organization',
                    ),
                ),
                (
                    'vendor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='vendor_invoices',
                        to='accounts_payable.vendor',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Vendor Invoice',
                'verbose_name_plural': 'Vendor Invoices',
                'db_table': 'accounts_payable_vendor_invoices',
                'ordering': ('-due_date',),
            },
            managers=[
                ('objects', apps.core.models.managers.SoftDeleteManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
    ]
