# Generated by Django 6.0.6 on 2026-09-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                ('work_date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('present', 'Present'),
                            ('absent', 'Absent'),
                            ('half_day', 'Half Day'),
                            ('late', 'Late'),
                            ('on_leave', 'On Leave'),
                            ('holiday', 'Holiday'),
                            ('week_off', 'Week Off'),
                        ],
                        default='present',
                        max_length=20,
                    ),
                ),
                (
                    'hours_worked',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ('notes', models.TextField(blank=True)),
                (
                    'employee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attendance_records',
                        to='employees.employee',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attendance_records',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'ordering': ['-work_date'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('employee', 'work_date'),
                        name='unique_attendance_per_employee_per_day',
                    )
                ],
            },
        ),
    ]
