# Generated by Django 6.0.6 on 2026-07-28 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='headed_departments',
                to='employees.employee',
            ),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='departments',
                to='organizations.organization',
            ),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='children',
                to='departments.department',
            ),
        ),
        migrations.AddField(
            model_name='departmenthierarchy',
            name='child',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='hierarchy_parents',
                to='departments.department',
            ),
        ),
        migrations.AddField(
            model_name='departmenthierarchy',
            name='parent',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='hierarchy_children',
                to='departments.department',
            ),
        ),
        migrations.AddField(
            model_name='departmentmember',
            name='department',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='members',
                to='departments.department',
            ),
        ),
        migrations.AddField(
            model_name='departmentmember',
            name='employee',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='department_memberships',
                to='employees.employee',
            ),
        ),
        migrations.AddField(
            model_name='departmentrole',
            name='department',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='roles',
                to='departments.department',
            ),
        ),
        migrations.AddField(
            model_name='departmentmember',
            name='role',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='members',
                to='departments.departmentrole',
            ),
        ),
        migrations.AddField(
            model_name='departmentsetting',
            name='department',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='department_settings',
                to='departments.department',
            ),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(
                fields=['organization', 'status'], name='departments_organiz_c1565b_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(
                fields=['organization', 'department_type'],
                name='departments_organiz_8cb5bb_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(
                fields=['organization', 'parent'], name='departments_organiz_44af11_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(
                fields=['organization', 'is_active'],
                name='departments_organiz_aa8e84_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(
                fields=('organization', 'code'),
                name='department_unique_code_per_organization',
            ),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(
                fields=('organization', 'name'),
                name='department_unique_name_per_organization',
            ),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(
                fields=('organization', 'slug'),
                name='department_unique_slug_per_organization',
            ),
        ),
        migrations.AddIndex(
            model_name='departmenthierarchy',
            index=models.Index(
                fields=['parent'], name='departments_parent__d5e116_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='departmenthierarchy',
            index=models.Index(fields=['child'], name='departments_child_i_5d4a7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='departmenthierarchy',
            constraint=models.UniqueConstraint(
                fields=('parent', 'child'), name='unique_department_hierarchy_relation'
            ),
        ),
        migrations.AddConstraint(
            model_name='departmentrole',
            constraint=models.UniqueConstraint(
                fields=('department', 'code'), name='unique_department_role_code'
            ),
        ),
        migrations.AddIndex(
            model_name='departmentmember',
            index=models.Index(
                fields=['department', 'is_active'],
                name='departments_departm_b67b15_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='departmentmember',
            index=models.Index(
                fields=['employee', 'is_active'], name='departments_employe_4135bb_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='departmentmember',
            constraint=models.UniqueConstraint(
                fields=('department', 'employee'), name='unique_department_member'
            ),
        ),
    ]
