# Generated by Django 6.0.6 on 2026-07-28 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='patient',
            field=models.ForeignKey(
                help_text='Patient granting consent.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='consents',
                to='patients.patient',
            ),
        ),
        migrations.AddField(
            model_name='phiaccesslog',
            name='actor',
            field=models.ForeignKey(
                blank=True,
                help_text='User or system actor that accessed PHI.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='phi_access_logs',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='phiaccesslog',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='phi_access_logs',
                to='organizations.organization',
            ),
        ),
        migrations.AddField(
            model_name='phiaccesslog',
            name='patient',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='phi_access_logs',
                to='patients.patient',
            ),
        ),
        migrations.AddIndex(
            model_name='phiaccesslog',
            index=models.Index(
                fields=['patient', 'action'], name='phi_log_patient_action_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='phiaccesslog',
            index=models.Index(
                fields=['actor', 'created_at'], name='phi_log_actor_time_idx'
            ),
        ),
    ]
