# Generated by Django 6.0.6 on 2026-07-31 11:49

import apps.core.models.managers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemedicineSession',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'session_id',
                    models.CharField(
                        help_text='Unique session identifier.',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    'scheduled_start',
                    models.DateTimeField(help_text='Scheduled session start time.'),
                ),
                (
                    'scheduled_end',
                    models.DateTimeField(help_text='Scheduled session end time.'),
                ),
                (
                    'actual_start',
                    models.DateTimeField(
                        blank=True, help_text='Actual session start time.', null=True
                    ),
                ),
                (
                    'actual_end',
                    models.DateTimeField(
                        blank=True, help_text='Actual session end time.', null=True
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('scheduled', 'Scheduled'),
                            ('in_progress', 'In Progress'),
                            ('completed', 'Completed'),
                            ('cancelled', 'Cancelled'),
                            ('no_show', 'No Show'),
                            ('failed', 'Failed'),
                        ],
                        db_index=True,
                        default='scheduled',
                        help_text='Session lifecycle status.',
                        max_length=20,
                    ),
                ),
                (
                    'session_type',
                    models.CharField(
                        choices=[
                            ('video', 'Video'),
                            ('audio', 'Audio'),
                            ('chat', 'Chat'),
                        ],
                        default='video',
                        help_text='Type of telemedicine session.',
                        max_length=20,
                    ),
                ),
                (
                    'connection_url',
                    models.URLField(help_text='URL for joining the session.'),
                ),
                (
                    'connection_id',
                    models.CharField(
                        blank=True,
                        help_text='Connection identifier from the telephony provider.',
                        max_length=100,
                    ),
                ),
                (
                    'recording_url',
                    models.URLField(
                        blank=True, help_text='URL of the session recording.'
                    ),
                ),
                (
                    'recording_consent',
                    models.BooleanField(
                        default=False,
                        help_text='Whether the patient consented to recording.',
                    ),
                ),
                ('notes', models.TextField(blank=True, help_text='Session notes.')),
                (
                    'appointment',
                    models.OneToOneField(
                        blank=True,
                        help_text='Associated appointment, if any.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='telemedicine_session',
                        to='appointments.appointment',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization that owns the session.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='telemedicine_sessions',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        help_text='Patient participating in the session.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='telemedicine_sessions',
                        to='patients.patient',
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        help_text='Provider conducting the session.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='telemedicine_sessions',
                        to='providers.provider',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Telemedicine Session',
                'verbose_name_plural': 'Telemedicine Sessions',
                'db_table': 'telemedicine_sessions',
                'ordering': ('-scheduled_start',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'recording_url',
                    models.URLField(help_text='URL where the recording is stored.'),
                ),
                (
                    'duration_seconds',
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='Recording duration in seconds.',
                        null=True,
                    ),
                ),
                (
                    'file_size_bytes',
                    models.PositiveIntegerField(
                        blank=True, help_text='Recording file size in bytes.', null=True
                    ),
                ),
                (
                    'transcript_url',
                    models.URLField(
                        blank=True, help_text='URL of the transcript file.'
                    ),
                ),
                (
                    'transcript_text',
                    models.TextField(blank=True, help_text='Transcript text content.'),
                ),
                (
                    'is_processed',
                    models.BooleanField(
                        default=False,
                        help_text='Whether the recording has been processed.',
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        help_text='Session that was recorded.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='recordings',
                        to='telemedicine.telemedicinesession',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Telemedicine Recording',
                'verbose_name_plural': 'Telemedicine Recordings',
                'db_table': 'telemedicine_recordings',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'participant_type',
                    models.CharField(
                        choices=[
                            ('patient', 'Patient'),
                            ('provider', 'Provider'),
                            ('nurse', 'Nurse'),
                            ('interpreter', 'Interpreter'),
                            ('observer', 'Observer'),
                        ],
                        help_text='Role of the participant.',
                        max_length=20,
                    ),
                ),
                (
                    'joined_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Time the participant joined the session.',
                        null=True,
                    ),
                ),
                (
                    'left_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Time the participant left the session.',
                        null=True,
                    ),
                ),
                (
                    'is_present',
                    models.BooleanField(
                        default=False,
                        help_text='Whether the participant is currently present.',
                    ),
                ),
                (
                    'connection_quality',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('excellent', 'Excellent'),
                            ('good', 'Good'),
                            ('poor', 'Poor'),
                            ('disconnected', 'Disconnected'),
                        ],
                        help_text='Connection quality rating.',
                        max_length=20,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='User participating in the session.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='telemedicine_participations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        help_text='Session this participant belongs to.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='participants',
                        to='telemedicine.telemedicinesession',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Telemedicine Participant',
                'verbose_name_plural': 'Telemedicine Participants',
                'db_table': 'telemedicine_participants',
                'ordering': ('session', 'user'),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='telemedicinesession',
            index=models.Index(
                fields=['patient', 'scheduled_start'],
                name='tele_session_patient_start_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='telemedicinesession',
            index=models.Index(
                fields=['provider', 'scheduled_start'], name='tele_sess_prov_start_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='telemedicinesession',
            index=models.Index(
                fields=['organization', 'status'], name='tele_session_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='telemedicinesession',
            index=models.Index(
                fields=['appointment'], name='tele_session_appointment_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(
                fields=['session', 'created_at'], name='tele_record_sess_crt_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(
                fields=['session', 'user'], name='tele_part_sess_user_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(
                fields=('session', 'user'), name='unique_participant_per_session'
            ),
        ),
    ]
