# Generated by Django 6.0.6 on 2026-09-09 03:06

import apps.core.models.managers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patient_core', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemedicineSession',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'session_id',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('scheduled', 'Scheduled'),
                            ('confirmed', 'Confirmed'),
                            ('ready', 'Ready'),
                            ('in_progress', 'In Progress'),
                            ('completed', 'Completed'),
                            ('cancelled', 'Cancelled'),
                            ('no_show', 'No Show'),
                            ('failed', 'Failed'),
                        ],
                        db_index=True,
                        default='scheduled',
                        max_length=20,
                    ),
                ),
                (
                    'session_type',
                    models.CharField(
                        choices=[
                            ('video', 'Video'),
                            ('audio', 'Audio'),
                            ('chat', 'Chat'),
                        ],
                        default='video',
                        max_length=20,
                    ),
                ),
                ('connection_url', models.URLField(blank=True)),
                ('connection_id', models.CharField(blank=True, max_length=128)),
                ('provider_name', models.CharField(blank=True, max_length=100)),
                ('recording_consent', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                (
                    'appointment',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='telemedicine_session',
                        to='appointments.appointment',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='telemedicine_sessions',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='telemedicine_sessions',
                        to='patient_core.patient',
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='telemedicine_sessions',
                        to='providers.provider',
                    ),
                ),
            ],
            options={
                'db_table': 'telemedicine_sessions',
                'ordering': ('-scheduled_start',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'recording_id',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('requested', 'Requested'),
                            ('recording', 'Recording'),
                            ('finalizing', 'Finalizing'),
                            ('ready', 'Ready'),
                            ('failed', 'Failed'),
                        ],
                        db_index=True,
                        default='requested',
                        max_length=20,
                    ),
                ),
                ('recording_url', models.URLField(blank=True)),
                ('transcript_url', models.URLField(blank=True)),
                ('transcript_text', models.TextField(blank=True)),
                (
                    'duration_seconds',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'file_size_bytes',
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='recordings',
                        to='telemedicine.telemedicinesession',
                    ),
                ),
            ],
            options={
                'db_table': 'telemedicine_recordings',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Indicates whether the entity is available for normal operations.',
                        verbose_name='Active',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name='Deleted',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name='Deleted At'
                    ),
                ),
                (
                    'deleted_by_id',
                    models.UUIDField(
                        blank=True, editable=False, null=True, verbose_name='Deleted By'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when the record was created.',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text='Timestamp when the record was last updated.',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Globally unique UUID v4 identifier.',
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'participant_type',
                    models.CharField(
                        choices=[
                            ('patient', 'Patient'),
                            ('provider', 'Provider'),
                            ('nurse', 'Nurse'),
                            ('interpreter', 'Interpreter'),
                            ('observer', 'Observer'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('invited', 'Invited'),
                            ('admitted', 'Admitted'),
                            ('joined', 'Joined'),
                            ('left', 'Left'),
                            ('removed', 'Removed'),
                        ],
                        db_index=True,
                        default='invited',
                        max_length=20,
                    ),
                ),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                (
                    'connection_quality',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('excellent', 'Excellent'),
                            ('good', 'Good'),
                            ('fair', 'Fair'),
                            ('poor', 'Poor'),
                            ('disconnected', 'Disconnected'),
                        ],
                        max_length=20,
                    ),
                ),
                ('microphone_enabled', models.BooleanField(default=True)),
                ('camera_enabled', models.BooleanField(default=True)),
                ('audio_connected', models.BooleanField(default=False)),
                ('video_connected', models.BooleanField(default=False)),
                (
                    'microphone_permission',
                    models.CharField(
                        choices=[
                            ('prompt', 'Prompt'),
                            ('granted', 'Granted'),
                            ('denied', 'Denied'),
                            ('not_applicable', 'Not Applicable'),
                        ],
                        default='prompt',
                        max_length=20,
                    ),
                ),
                (
                    'camera_permission',
                    models.CharField(
                        choices=[
                            ('prompt', 'Prompt'),
                            ('granted', 'Granted'),
                            ('denied', 'Denied'),
                            ('not_applicable', 'Not Applicable'),
                        ],
                        default='prompt',
                        max_length=20,
                    ),
                ),
                ('media_updated_at', models.DateTimeField(blank=True, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='telemedicine_participations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='participants',
                        to='telemedicine.telemedicinesession',
                    ),
                ),
            ],
            options={
                'db_table': 'telemedicine_participants',
                'ordering': ('session', 'user'),
            },
            managers=[
                ('objects', apps.core.models.managers.BaseManager()),
                ('all_objects', apps.core.models.managers.AllObjectsManager()),
                ('deleted_objects', apps.core.models.managers.DeletedObjectsManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='telemedicinesession',
            index=models.Index(
                fields=['organization', 'status'], name='tele_sess_org_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='telemedicinesession',
            index=models.Index(
                fields=['patient', 'scheduled_start'], name='tele_sess_pat_start_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='telemedicinesession',
            index=models.Index(
                fields=['provider', 'scheduled_start'], name='tele_sess_prov_start_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='telemedicinesession',
            index=models.Index(fields=['appointment'], name='tele_sess_appt_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(
                fields=['session', 'status'], name='tele_rec_sess_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(
                fields=['session', 'status'], name='tele_part_sess_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(
                fields=['session', 'joined_at'], name='tele_part_sess_join_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(
                fields=('session', 'user'), name='unique_tele_participant_session_user'
            ),
        ),
    ]
