# Generated by Django 6.0.6 on 2026-09-09 03:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('patient_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                (
                    'device_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('device_type', models.CharField(max_length=80)),
                ('manufacturer', models.CharField(blank=True, max_length=160)),
                ('model_name', models.CharField(blank=True, max_length=160)),
                ('model_number', models.CharField(blank=True, max_length=160)),
                ('serial_number', models.CharField(blank=True, max_length=160)),
                ('firmware_version', models.CharField(blank=True, max_length=120)),
                ('hardware_revision', models.CharField(blank=True, max_length=120)),
                (
                    'lifecycle',
                    models.CharField(
                        choices=[
                            ('DISCOVERED', 'Discovered'),
                            ('PAIRING', 'Pairing'),
                            ('PAIRED', 'Paired'),
                            ('ASSOCIATED', 'Associated'),
                            ('ACTIVE', 'Active'),
                            ('SUSPENDED', 'Suspended'),
                            ('RETIRED', 'Retired'),
                        ],
                        default='DISCOVERED',
                        max_length=24,
                    ),
                ),
                (
                    'trust_state',
                    models.CharField(
                        choices=[
                            ('UNKNOWN', 'Unknown'),
                            ('TRUSTED', 'Trusted'),
                            ('UNTRUSTED', 'Untrusted'),
                            ('REVOKED', 'Revoked'),
                        ],
                        default='UNKNOWN',
                        max_length=24,
                    ),
                ),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                (
                    'battery_percent',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='device_platform_devices',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'device_platform_devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceCapability',
            fields=[
                (
                    'capability_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'capability_type',
                    models.CharField(
                        choices=[
                            ('HEART_RATE', 'Heart rate'),
                            ('SPO2', 'SpO2'),
                            ('BLOOD_PRESSURE', 'Blood pressure'),
                            ('GLUCOSE', 'Glucose'),
                            ('TEMPERATURE', 'Temperature'),
                            ('ECG', 'ECG'),
                            ('RESPIRATORY_RATE', 'Respiratory rate'),
                            ('WEIGHT', 'Weight'),
                            ('STEPS', 'Steps'),
                            ('DISTANCE', 'Distance'),
                            ('CALORIES', 'Calories'),
                            ('SLEEP', 'Sleep'),
                            ('ACTIVITY', 'Activity'),
                            ('BATTERY', 'Battery'),
                            ('GENERIC', 'Generic'),
                        ],
                        max_length=40,
                    ),
                ),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('sampling_mode', models.CharField(default='ON_DEMAND', max_length=40)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'device',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='capabilities',
                        to='device_platform.device',
                    ),
                ),
            ],
            options={
                'db_table': 'device_platform_capabilities',
            },
        ),
        migrations.CreateModel(
            name='DeviceConnection',
            fields=[
                (
                    'connection_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('BLE', 'Bluetooth Low Energy'),
                            ('WIFI', 'Wi-Fi'),
                            ('MOBILE', 'Mobile'),
                            ('HEALTH_PLATFORM', 'Health platform'),
                            ('GATEWAY', 'Gateway'),
                            ('API', 'API'),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('DISCONNECTED', 'Disconnected'),
                            ('CONNECTING', 'Connecting'),
                            ('CONNECTED', 'Connected'),
                            ('RECONNECTING', 'Reconnecting'),
                            ('FAILED', 'Failed'),
                        ],
                        default='DISCONNECTED',
                        max_length=24,
                    ),
                ),
                (
                    'external_connection_id',
                    models.CharField(blank=True, max_length=255),
                ),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'device',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='connections',
                        to='device_platform.device',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='device_connections',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'device_platform_connections',
            },
        ),
        migrations.CreateModel(
            name='DeviceConsent',
            fields=[
                (
                    'consent_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('purpose', models.CharField(max_length=120)),
                ('granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'device',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='consents',
                        to='device_platform.device',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='device_consents',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='device_consents',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'db_table': 'device_platform_consents',
            },
        ),
        migrations.CreateModel(
            name='DeviceFirmware',
            fields=[
                (
                    'firmware_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('version', models.CharField(max_length=120)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('release_notes', models.TextField(blank=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'device',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='firmware_history',
                        to='device_platform.device',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='device_firmware',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'device_platform_firmware',
            },
        ),
        migrations.CreateModel(
            name='DeviceIdentifier',
            fields=[
                (
                    'identifier_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('identifier_type', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'device',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='identifiers',
                        to='device_platform.device',
                    ),
                ),
            ],
            options={
                'db_table': 'device_platform_identifiers',
            },
        ),
        migrations.CreateModel(
            name='DevicePairing',
            fields=[
                (
                    'pairing_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('NOT_PAIRED', 'Not paired'),
                            ('PENDING', 'Pending'),
                            ('PAIRED', 'Paired'),
                            ('REVOKED', 'Revoked'),
                        ],
                        default='PENDING',
                        max_length=24,
                    ),
                ),
                ('pairing_method', models.CharField(default='BLE', max_length=40)),
                ('external_pairing_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'device',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pairings',
                        to='device_platform.device',
                    ),
                ),
                (
                    'initiated_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='device_pairings_initiated',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='device_pairings',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'device_platform_pairings',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                (
                    'device_type_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_medical', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='device_types',
                        to='organizations.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'device_platform_device_types',
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                (
                    'device_model_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('manufacturer', models.CharField(max_length=160)),
                ('model_name', models.CharField(max_length=160)),
                ('model_number', models.CharField(blank=True, max_length=160)),
                ('protocol', models.CharField(default='BLE', max_length=40)),
                ('specification', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='device_models',
                        to='organizations.organization',
                    ),
                ),
                (
                    'device_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='models',
                        to='device_platform.devicetype',
                    ),
                ),
            ],
            options={
                'db_table': 'device_platform_device_models',
            },
        ),
        migrations.CreateModel(
            name='PatientDevice',
            fields=[
                (
                    'patient_device_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'assigned_at',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'device',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='patient_associations',
                        to='device_platform.device',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='patient_devices',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='device_platform_devices',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'db_table': 'device_platform_patient_devices',
            },
        ),
        migrations.CreateModel(
            name='TelemetryRecord',
            fields=[
                (
                    'telemetry_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('measurement_type', models.CharField(max_length=60)),
                (
                    'value',
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('measured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('BLE', 'Bluetooth Low Energy'),
                            ('WIFI', 'Wi-Fi'),
                            ('MOBILE', 'Mobile'),
                            ('HEALTH_PLATFORM', 'Health platform'),
                            ('GATEWAY', 'Gateway'),
                            ('API', 'API'),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    'quality',
                    models.CharField(
                        choices=[
                            ('UNKNOWN', 'Unknown'),
                            ('VALID', 'Valid'),
                            ('SUSPECT', 'Suspect'),
                            ('INVALID', 'Invalid'),
                        ],
                        default='UNKNOWN',
                        max_length=16,
                    ),
                ),
                (
                    'source_event_id',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                (
                    'capability',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='telemetry',
                        to='device_platform.devicecapability',
                    ),
                ),
                (
                    'device',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='telemetry',
                        to='device_platform.device',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='device_telemetry',
                        to='organizations.organization',
                    ),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='device_telemetry',
                        to='patient_core.patient',
                    ),
                ),
            ],
            options={
                'db_table': 'device_platform_telemetry',
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(
                fields=['organization', 'lifecycle'], name='dp_dev_org_life_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(
                fields=['organization', 'manufacturer'], name='dp_dev_org_mfr_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='dp_dev_serial_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(
                condition=models.Q(('serial_number', ''), _negated=True),
                fields=('organization', 'serial_number'),
                name='dp_dev_org_serial_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('battery_percent__isnull', True),
                    ('battery_percent__range', (0, 100)),
                    _connector='OR',
                ),
                name='dp_dev_battery_range_chk',
            ),
        ),
        migrations.AddConstraint(
            model_name='devicecapability',
            constraint=models.UniqueConstraint(
                fields=('device', 'capability_type'), name='dp_cap_device_type_uniq'
            ),
        ),
        migrations.AddIndex(
            model_name='deviceconnection',
            index=models.Index(
                fields=['organization', 'device', 'state'],
                name='dp_conn_org_dev_state_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='deviceconnection',
            constraint=models.UniqueConstraint(
                fields=('organization', 'device', 'source'),
                name='dp_conn_org_dev_source_uniq',
            ),
        ),
        migrations.AddIndex(
            model_name='deviceconsent',
            index=models.Index(
                fields=['organization', 'patient', 'device'],
                name='dp_consent_org_pat_dev_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='devicefirmware',
            index=models.Index(
                fields=['organization', 'device', '-created_at'],
                name='dp_fw_org_dev_created_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='deviceidentifier',
            index=models.Index(
                fields=['identifier_type', 'value'], name='dp_identifier_lookup_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='deviceidentifier',
            constraint=models.UniqueConstraint(
                fields=('identifier_type', 'value'),
                name='dp_identifier_type_value_uniq',
            ),
        ),
        migrations.AddIndex(
            model_name='devicepairing',
            index=models.Index(
                fields=['organization', 'device', 'state'],
                name='dp_pair_org_dev_state_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='devicepairing',
            constraint=models.UniqueConstraint(
                condition=models.Q(('state', 'PAIRED')),
                fields=('organization', 'device'),
                name='dp_pair_active_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='devicetype',
            constraint=models.UniqueConstraint(
                fields=('organization', 'code'), name='dp_type_org_code_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='devicemodel',
            constraint=models.UniqueConstraint(
                fields=('organization', 'manufacturer', 'model_name'),
                name='dp_model_org_mfr_name_uniq',
            ),
        ),
        migrations.AddIndex(
            model_name='patientdevice',
            index=models.Index(
                fields=['organization', 'patient', 'active'],
                name='dp_pd_org_pat_act_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='patientdevice',
            index=models.Index(
                fields=['organization', 'device', 'active'],
                name='dp_pd_org_dev_act_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='patientdevice',
            constraint=models.UniqueConstraint(
                condition=models.Q(('active', True)),
                fields=('organization', 'patient', 'device'),
                name='dp_patient_device_active_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='patientdevice',
            constraint=models.UniqueConstraint(
                condition=models.Q(('active', True)),
                fields=('organization', 'device'),
                name='dp_patient_device_device_active_uniq',
            ),
        ),
        migrations.AddIndex(
            model_name='telemetryrecord',
            index=models.Index(
                fields=['organization', 'patient', 'measurement_type', '-measured_at'],
                name='dp_tel_org_pat_type_time_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='telemetryrecord',
            index=models.Index(
                fields=['organization', 'device', '-measured_at'],
                name='dp_tel_org_dev_time_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='telemetryrecord',
            index=models.Index(
                fields=['source_event_id'], name='dp_tel_source_event_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='telemetryrecord',
            constraint=models.UniqueConstraint(
                fields=('organization', 'device', 'source_event_id'),
                name='dp_tel_source_event_uniq',
            ),
        ),
    ]
