# Generated by Django 6.0.6 on 2026-07-16 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_alter_organizationhierarchy_relationship_type"),
        ("rbac", "0002_userrole"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("invitation", "Invitation"),
                            ("default_role", "Default Role"),
                            ("sync", "Synchronization"),
                            ("migration", "Migration"),
                            ("system", "System"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary role for the user within the organization.",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_roles",
                        to="organizations.organization",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_roles",
                        to="rbac.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Role",
                "verbose_name_plural": "Organization Roles",
                "ordering": ("organization", "user", "role"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "user", "role"),
                        name="unique_organization_user_role",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoleHierarchy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hierarchy_type",
                    models.CharField(
                        choices=[("direct", "Direct"), ("inherited", "Inherited")],
                        default="direct",
                        max_length=20,
                    ),
                ),
                (
                    "assignment_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("system", "System"),
                            ("migration", "Migration"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "child_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_hierarchies",
                        to="rbac.role",
                    ),
                ),
                (
                    "parent_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_hierarchies",
                        to="rbac.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Hierarchy",
                "verbose_name_plural": "Role Hierarchies",
                "ordering": ("parent_role", "child_role"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent_role", "child_role"),
                        name="unique_role_hierarchy",
                    )
                ],
            },
        ),
    ]
