# Generated by Django 6.0.6 on 2026-09-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_alter_permission_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(
                choices=[
                    ('accounts', 'Accounts'),
                    ('organizations', 'Organizations'),
                    ('rbac', 'Role Based Access Control'),
                    ('patients', 'Patients'),
                    ('providers', 'Providers'),
                    ('employees', 'Employees'),
                    ('departments', 'Departments'),
                    ('teams', 'Teams'),
                    ('documents', 'Documents'),
                    ('appointments', 'Appointments'),
                    ('encounters', 'Encounters'),
                    ('laboratories', 'Laboratories'),
                    ('medications', 'Medications'),
                    ('prescriptions', 'Prescriptions'),
                    ('allergies', 'Allergies'),
                    ('diagnoses', 'Diagnoses'),
                    ('vitals', 'Vitals'),
                    ('pharmacy', 'Pharmacy'),
                    ('billing', 'Billing'),
                    ('inventory', 'Inventory'),
                    ('notifications', 'Notifications'),
                    ('audit', 'Audit'),
                    ('reports', 'Reports'),
                    ('Dashboard', 'Dashboard'),
                    ('settings', 'Settings'),
                    ('ai', 'Artificial Intelligence'),
                    ('telemedicine', 'Telemedicine'),
                ],
                db_index=True,
                help_text='Application module.',
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='module',
            field=models.CharField(
                choices=[
                    ('accounts', 'Accounts'),
                    ('organizations', 'Organizations'),
                    ('rbac', 'Role Based Access Control'),
                    ('patients', 'Patients'),
                    ('providers', 'Providers'),
                    ('employees', 'Employees'),
                    ('departments', 'Departments'),
                    ('teams', 'Teams'),
                    ('documents', 'Documents'),
                    ('appointments', 'Appointments'),
                    ('encounters', 'Encounters'),
                    ('laboratories', 'Laboratories'),
                    ('medications', 'Medications'),
                    ('prescriptions', 'Prescriptions'),
                    ('allergies', 'Allergies'),
                    ('diagnoses', 'Diagnoses'),
                    ('vitals', 'Vitals'),
                    ('pharmacy', 'Pharmacy'),
                    ('billing', 'Billing'),
                    ('inventory', 'Inventory'),
                    ('notifications', 'Notifications'),
                    ('audit', 'Audit'),
                    ('reports', 'Reports'),
                    ('Dashboard', 'Dashboard'),
                    ('settings', 'Settings'),
                    ('ai', 'Artificial Intelligence'),
                    ('telemedicine', 'Telemedicine'),
                ],
                db_index=True,
                help_text='Associated platform module.',
                max_length=64,
            ),
        ),
    ]
