# Generated by Django 6.0.6 on 2026-07-16 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0003_organizationrole_rolehierarchy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rolehierarchy",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rolehierarchy",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rolehierarchy",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="rolehierarchy",
            name="assignment_source",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("manual", "Manual"),
                    ("import", "Import"),
                    ("api", "API"),
                ],
                default="system",
                max_length=32,
            ),
        ),
    ]
