# Generated by Django 6.0.6 on 2026-10-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_alter_permission_module_alter_permissiongroup_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('accounts', 'Accounts'), ('organizations', 'Organizations'), ('rbac', 'Role Based Access Control'), ('patients', 'Patients'), ('providers', 'Providers'), ('employees', 'Employees'), ('departments', 'Departments'), ('teams', 'Teams'), ('hr', 'Human Resources'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('shifts', 'Shifts'), ('holidays', 'Holidays'), ('onboarding', 'Onboarding'), ('payroll', 'Payroll'), ('performance', 'Performance'), ('recruitment', 'Recruitment'), ('hospital_operations', 'Hospital Operations'), ('devices', 'Connected Devices'), ('documents', 'Documents'), ('appointments', 'Appointments'), ('encounters', 'Encounters'), ('laboratories', 'Laboratories'), ('medications', 'Medications'), ('prescriptions', 'Prescriptions'), ('allergies', 'Allergies'), ('diagnoses', 'Diagnoses'), ('vitals', 'Vitals'), ('pharmacy', 'Pharmacy'), ('imaging', 'Imaging'), ('notes', 'Clinical Notes'), ('transcription', 'Transcription'), ('billing', 'Billing'), ('insurance', 'Insurance'), ('inventory', 'Inventory'), ('notifications', 'Notifications'), ('audit', 'Audit'), ('reports', 'Reports'), ('Dashboard', 'Dashboard'), ('settings', 'Settings'), ('ai', 'Artificial Intelligence'), ('telemedicine', 'Telemedicine')], db_index=True, help_text='Application module.', max_length=64),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='module',
            field=models.CharField(choices=[('accounts', 'Accounts'), ('organizations', 'Organizations'), ('rbac', 'Role Based Access Control'), ('patients', 'Patients'), ('providers', 'Providers'), ('employees', 'Employees'), ('departments', 'Departments'), ('teams', 'Teams'), ('hr', 'Human Resources'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('shifts', 'Shifts'), ('holidays', 'Holidays'), ('onboarding', 'Onboarding'), ('payroll', 'Payroll'), ('performance', 'Performance'), ('recruitment', 'Recruitment'), ('hospital_operations', 'Hospital Operations'), ('devices', 'Connected Devices'), ('documents', 'Documents'), ('appointments', 'Appointments'), ('encounters', 'Encounters'), ('laboratories', 'Laboratories'), ('medications', 'Medications'), ('prescriptions', 'Prescriptions'), ('allergies', 'Allergies'), ('diagnoses', 'Diagnoses'), ('vitals', 'Vitals'), ('pharmacy', 'Pharmacy'), ('imaging', 'Imaging'), ('notes', 'Clinical Notes'), ('transcription', 'Transcription'), ('billing', 'Billing'), ('insurance', 'Insurance'), ('inventory', 'Inventory'), ('notifications', 'Notifications'), ('audit', 'Audit'), ('reports', 'Reports'), ('Dashboard', 'Dashboard'), ('settings', 'Settings'), ('ai', 'Artificial Intelligence'), ('telemedicine', 'Telemedicine')], db_index=True, help_text='Associated platform module.', max_length=64),
        ),
    ]
